first stage for lots of enhancements
git-svn-id: http://openqrm.svn.sourceforge.net/svnroot/openqrm@1382 f7cd0d49-994a-0410-81fc-ecfcdc9cdbae

diff --git a/trunk/src/plugins/local-storage/etc/init.d/openqrm-plugin-local-storage b/trunk/src/plugins/local-storage/etc/init.d/openqrm-plugin-local-storage
--- a/trunk/src/plugins/local-storage/etc/init.d/openqrm-plugin-local-storage
+++ b/trunk/src/plugins/local-storage/etc/init.d/openqrm-plugin-local-storage
@@ -8,6 +8,22 @@ OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $
 . $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/include/openqrm-plugin-local-storage-functions
 . $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/etc/openqrm-plugin-local-storage.conf
 
+PARTIMAGE_NG_LIBS="libparted,libext2fs,libntfs,libstdc++,libgcc_"
+
+function copy_lib_dependencies() {
+    local TARGET_LIB=$1
+    local TARGET_DIR=$2
+    LIB_FILE=`find /lib/ /usr/lib -maxdepth 2 -name $TARGET_LIB*so* -type f | grep -v vmware | grep -v "\-3g" | grep -v openqrm | head -n1`
+    if [ "$LIB_FILE" == "" ]; then
+    	echo "ERROR: Cloud not find $TARGET_LIB on this system ! Exiting..."
+        return 1
+    fi
+    cp -aRv $LIB_FILE $TARGET_DIR/
+    for LIB_LINK in `find /lib/ /usr/lib -maxdepth 2 -name $TARGET_LIB*so* -type l | grep -v vmware  | grep -v "\-3g" | grep -v openqrm`; do
+        cp -aRv $LIB_LINK $TARGET_DIR/
+    done
+}
+
 
 function openqrm_plugin_local_storage_start() {
 	echo "Starting the openQRM local-storage-plugin"
@@ -36,6 +52,8 @@ function openqrm_plugin_local_storage_uninstall() {
 	openqrm_server_remove_deployment_type $USERNAME $PASSWORD local-storage
 	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/local-storage
 	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/root-mount.local-storage
+    rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image.local-storage.php
+    rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/partimage-ng.tgz
 }
 
 function openqrm_plugin_local_storage_init() {
@@ -50,13 +68,37 @@ function openqrm_plugin_local_storage_init() {
 		echo
 	fi
 	echo "Initializing the openQRM local-storage-plugin"
+    # need to gather the lib dependencies for partimage-ng, for now in the init phase
+    rm -rf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/bs-tmp
+    mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/bs-tmp/bin
+    mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/bs-tmp/lib
+    cp -f $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/bin/partimage-ng $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/bs-tmp/bin/
+    # cp lib deps
+    OLDIFS=$IFS
+    IFS=','
+    for LIB_DEP in $PARTIMAGE_NG_LIBS; do
+        IFS=$OLDIFS
+        if ! copy_lib_dependencies $LIB_DEP $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/bs-tmp/lib/; then
+            return 1
+        fi
+    done
+    IFS=$OLDIFS
+    cd $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/bs-tmp/
+    tar -czvf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/web/partimage-ng.tgz bin include lib
+    cd - 1>/dev/null
+    rm -rf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/bs-tmp
+
 	openqrm_server_add_deployment_type $USERNAME $PASSWORD local-storage local-storage "Local-Disk deployment" local-storage "Local-Deployment Storage"
 	# linking the web dir
 	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/web $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/local-storage
 	# linking the boot-service
 	chmod +x $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/web/root-mount.local-storage
-	ln -s $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/web/root-mount.local-storage $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/root-mount.local-storage
-	ln -s $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/web/partimage $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/partimage
+	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/web/root-mount.local-storage $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/root-mount.local-storage
+	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/web/image.local-storage.php $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image.local-storage.php
+	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/web/partimage-ng.tgz $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/partimage-ng.tgz
+    # create storage dir for stat files
+    mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/web/storage
+    chmod 777 $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/web/storage
 }
 
 USER=$2
diff --git a/trunk/src/plugins/local-storage/include/openqrm-plugin-local-storage-functions b/trunk/src/plugins/local-storage/include/openqrm-plugin-local-storage-functions
--- a/trunk/src/plugins/local-storage/include/openqrm-plugin-local-storage-functions
+++ b/trunk/src/plugins/local-storage/include/openqrm-plugin-local-storage-functions
@@ -1,3 +1,147 @@
 #!/bin/bash
 # this is the functions file for the local-storage-plugin
 
+# some definitions
+DEFAULT_IMAGE_SIZE=5000
+LOCAL_MGMT_LOCK_FILE=/var/run/local-storage/local-storage-plugin.lock
+LOCAL_MGMT_LOCK_DELAY=5
+LOCAL_MGMT_LOCK_RETRY=100
+LOCAL_MGMT_LOCK_TIMEOUT=500
+MAX_UMOUNT_LOOP=5
+LV_SIZE_DEFAULT=5000
+
+################ common local-storage functions
+
+# logs for local_storage
+function local_storage_log() {
+	local COMPONENT=$1
+	shift
+	local MESSAGE=$@
+	logger -i -t "local-storage plug-in" "$COMPONENT : $MESSAGE"
+}
+
+
+# locking function
+function local_storage_lock() {
+	local COMMAND=$1
+	local RET=1
+
+	if [ ! -d `dirname $LOCAL_MGMT_LOCK_FILE` ]; then
+		mkdir -p `dirname $LOCAL_MGMT_LOCK_FILE`
+	fi
+	case "$COMMAND" in
+		aquire)
+				lockfile -s $LOCAL_MGMT_LOCK_DELAY -r $LOCAL_MGMT_LOCK_RETRY -l $LOCAL_MGMT_LOCK_TIMEOUT $LOCAL_MGMT_LOCK_FILE
+				RET=$?
+				local_storage_log local_storage_lock "Aquired the lock"
+				return $RET
+				;;
+		release)
+				/bin/rm -f $LOCAL_MGMT_LOCK_FILE
+				RET=$?
+				local_storage_log local_storage_lock "Released the lock"
+				return $RET
+				;;
+		*)
+			local_storage_log local_storage_lock "No such command. Try 'aquire' or 'release'"
+			return 1
+			;;
+	esac
+}
+
+
+
+################ local-storage functions
+
+################ local-nfs ###################################
+
+
+function manage_fstab() {
+	case "$1" in
+		add)
+			echo "/dev/$LOCAL_STORAGE_SERVER_VOLUME_GROUP/$LOCAL_IMAGE_NAME    /$LOCAL_STORAGE_SERVER_VOLUME_GROUP/$LOCAL_IMAGE_NAME      ext3    defaults        1 1" >> /etc/fstab
+			;;
+		remove)
+			sed -i -e "s#^/dev/$LOCAL_STORAGE_SERVER_VOLUME_GROUP/$LOCAL_IMAGE_NAME.*##g" /etc/fstab
+			;;
+	esac
+}
+
+
+function manage_nfs() {
+	case "$1" in
+		add)
+			OPENQRM_SERVER=$3
+			if [ "$2" != "snap" ]; then
+				local_storage_log manage_nfs "NOTICE: creating ext3 filesytem on /dev/$LOCAL_STORAGE_SERVER_VOLUME_GROUP/$LOCAL_IMAGE_NAME"
+				if ! mkfs.ext3 -F /dev/$LOCAL_STORAGE_SERVER_VOLUME_GROUP/$LOCAL_IMAGE_NAME; then
+					local_storage_log local-storage-functions "ERROR: Could not create ext3 filesytem on /dev/$LOCAL_STORAGE_SERVER_VOLUME_GROUP/$LOCAL_IMAGE_NAME"
+					manage_fstab remove
+					local_storage_lock release
+					return 1
+				fi
+			fi
+			mkdir -p /$LOCAL_STORAGE_SERVER_VOLUME_GROUP/$LOCAL_IMAGE_NAME
+			if ! `mount /dev/$LOCAL_STORAGE_SERVER_VOLUME_GROUP/$LOCAL_IMAGE_NAME /$LOCAL_STORAGE_SERVER_VOLUME_GROUP/$LOCAL_IMAGE_NAME`; then
+				local_storage_log local-storage-functions "ERROR: Could not mount /dev/$LOCAL_STORAGE_SERVER_VOLUME_GROUP/$LOCAL_IMAGE_NAME at /$LOCAL_STORAGE_SERVER_VOLUME_GROUP/$LOCAL_IMAGE_NAME"
+				manage_fstab remove
+				local_storage_lock release
+				return 1
+			fi
+			echo "/$LOCAL_STORAGE_SERVER_VOLUME_GROUP/$LOCAL_IMAGE_NAME	$OPENQRM_SERVER(rw,insecure,no_root_squash,async)" >> /etc/exports
+            # mark it as local-storage location
+            touch /$LOCAL_STORAGE_SERVER_VOLUME_GROUP/$LOCAL_IMAGE_NAME/local-storage
+			if [ -x /etc/init.d/nfs ]; then
+				/etc/init.d/nfs reload
+			elif [ -x /etc/init.d/nfs-kernel-server ]; then
+				/etc/init.d/nfs-kernel-server reload
+			else
+				local_storage_log local-storage-functions "WARNING: Could not find nfs-server init script !"
+				local_storage_lock release
+				return 1
+			fi
+			;;
+		remove)
+			sed -i -e "s#^/$LOCAL_STORAGE_SERVER_VOLUME_GROUP/$LOCAL_IMAGE_NAME.*##g" /etc/exports
+			if [ -x /etc/init.d/nfs ]; then
+				/etc/init.d/nfs reload
+			elif [ -x /etc/init.d/nfs-kernel-server ]; then
+				/etc/init.d/nfs-kernel-server reload
+			else
+				local_storage_log local-storage-functions "WARNING: Could not find nfs-server init script !"
+				local_storage_lock release
+				return 1
+			fi
+			while ! `umount /$LOCAL_STORAGE_SERVER_VOLUME_GROUP/$LOCAL_IMAGE_NAME`; do
+				echo "ERROR: Could not umount /$LOCAL_STORAGE_SERVER_VOLUME_GROUP/$LOCAL_IMAGE_NAME, trying again ..."
+				local_storage_log local-storage-functions "ERROR: Could not umount /$LOCAL_STORAGE_SERVER_VOLUME_GROUP/$LOCAL_IMAGE_NAME, trying again ..."
+				if [ "$UMOUNT_LOOP" = "$MAX_UMOUNT_LOOP" ]; then
+					echo "ERROR: Could not umount /$LOCAL_STORAGE_SERVER_VOLUME_GROUP/$LOCAL_IMAGE_NAME. Giving up !!!" 2>1
+					local_storage_log local-storage-functions "ERROR: Could not umount /$LOCAL_STORAGE_SERVER_VOLUME_GROUP/$LOCAL_IMAGE_NAME. Giving up !!!"
+					manage_fstab remove
+					local_storage_lock release
+					return 20
+				fi
+				UMOUNT_LOOP=$(( UMOUNT_LOOP + 1 ))
+				sleep 2
+			done
+			rmdir /$LOCAL_STORAGE_SERVER_VOLUME_GROUP/$LOCAL_IMAGE_NAME
+			;;
+		auth)
+			AUTH_IP=$2
+			sed -i -e "s#^$LOCAL_IMAGE_ROOTDEVICE.*#$LOCAL_IMAGE_ROOTDEVICE	$AUTH_IP(rw,insecure,no_root_squash,async)#g" /etc/exports
+			sed -i '/^$/d' /etc/exports
+			if [ -x /etc/init.d/nfs ]; then
+				/etc/init.d/nfs reload
+			elif [ -x /etc/init.d/nfs-kernel-server ]; then
+				/etc/init.d/nfs-kernel-server reload
+			else
+				local_storage_log local-storage-functions "WARNING: Could not find nfs-server init script !"
+				local_storage_lock release
+				return 1
+			fi
+			;;
+	esac
+}
+
+
