more updates on the netconfig
git-svn-id: http://openqrm.svn.sourceforge.net/svnroot/openqrm@1011 f7cd0d49-994a-0410-81fc-ecfcdc9cdbae

diff --git a/trunk/src/plugins/cloud/etc/init.d/cloud b/trunk/src/plugins/cloud/etc/init.d/cloud
--- a/trunk/src/plugins/cloud/etc/init.d/cloud
+++ b/trunk/src/plugins/cloud/etc/init.d/cloud
@@ -4,24 +4,58 @@
 OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
 . $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
 . $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/cloud/include/openqrm-plugin-cloud-functions
-if [ -f $OPENQRM_RESOURCE_PARAMETER_FILE ]; then
-	. $OPENQRM_RESOURCE_PARAMETER_FILE
-	OPENQRM_SERVER_IP=$resource_openqrmserver
-elif [ -f $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf ]; then
-	. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
-	. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
-	openqrm_server_get_config
-	OPENQRM_SERVER_IP=$OPENQRM_SERVER_IP_ADDRESS
-fi
+. $OPENQRM_RESOURCE_PARAMETER_FILE
+OPENQRM_SERVER_IP=$resource_openqrmserver
+NETWORK_CONF="/tmp/cloud-net.conf"
 
 # do not start on the intitrd
 if [ -f /etc/initrd-devices.conf ]; then
 	exit 0
 fi
+# and do not run on the openQRM server itself
+if [ -f $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf ]; then
+	exit 0
+fi
+
 
 function cloud_start() {
 	echo "Starting the openQRM cloud-plugin"
 	cloud_stop 1>/dev/null 2>&1
+
+	// get the ip-config from the cloud-network-config provider
+	rm -f $NETWORK_CONF
+	if ! wget -q -O $NETWORK_CONF "http://$resource_openqrmserver/cloud-portal/conf/cloud-network-provider.php?appliance_id=1&howmany=4"; then
+		echo "ERROR: Could not get Cloud network-config from openQRM-server $resource_openqrmserver"
+		return 1
+	fi
+	OPENQRM_INTERFACE=`ifconfig | grep $resource_mac | grep :oq | cut -d':' -f1`
+	EXTERNAL_INTERFACES_LIST=`ifconfig -a | grep eth | awk {' print $1 '} | grep -v $OPENQRM_INTERFACE`
+
+	// assign the network conf
+	for CONFIG in `cat $NETWORK_CONF`; do
+		IP=`echo $CONFIG | cut -d':' -f1`
+		SUBNET=`echo $CONFIG | cut -d':' -f2`
+		GATEWAY=`echo $CONFIG | cut -d':' -f3`
+		DNS1=`echo $CONFIG | cut -d':' -f4`
+		DNS2=`echo $CONFIG | cut -d':' -f5`
+		for INTERFACE in $EXTERNAL_INTERFACES_LIST; do
+			// here we set the interface
+			ifconfig $INTERFACE $IP netmask $SUBNET up
+			// set the dns server
+			> /etc/resolv.conf
+			echo "nameserver $DNS1" >> /etc/resolv.conf
+			echo "nameserver $DNS2" >> /etc/resolv.conf
+			// configure the route
+			route add default gw $GATEWAY
+			// remove interface from the list
+			EXTERNAL_INTERFACES_LIST=`echo $EXTERNAL_INTERFACES_LIST | sed -e "s/$INTERFACE//g"`
+			export EXTERNAL_INTERFACES_LIST
+			break
+		done
+	done
+
+
+
 }
 
 
