Creating script is less error-prone and since it's very static, that's actually the preferred way.
git-svn-id: http://openqrm.svn.sourceforge.net/svnroot/openqrm@1678 f7cd0d49-994a-0410-81fc-ecfcdc9cdbae

diff --git a/trunk/src/include/openqrm-build-functions b/trunk/src/include/openqrm-build-functions
--- a/trunk/src/include/openqrm-build-functions
+++ b/trunk/src/include/openqrm-build-functions
@@ -386,9 +386,37 @@ function openqrm_create_default_initrd_template() {
 		done
 	done
 
-	# copy default udhcpc script
+	# create default udhcpc script
 	mkdir -p $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/usr/share/udhcpc
-	cp -a $OPENQRM_BUILD_TMP_DIR/openqrm-build/busybox/busybox-$OPENQRM_SOURCE_VERSION/examples/udhcp/simple.script $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/usr/share/udhcpc/default.script 
+	cat >> $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/usr/share/udhcpc/default.script << EOF
+#!/bin/sh
+# udhcpc script edited by Tim Riker <Tim@Rikers.org>
+# changed by infernix <infernix@infernix.net>: we don't need to do resolv.conf again
+# because we only call this for additional interfaces
+[ -z "$1" ] && echo "Error: should be called from udhcpc" && exit 1
+[ -n "$broadcast" ] && BROADCAST="broadcast $broadcast"
+[ -n "$subnet" ] && NETMASK="netmask $subnet"
+
+case "$1" in
+	deconfig)
+		/sbin/ifconfig $interface 0.0.0.0
+		;;
+	renew|bound)
+		/sbin/ifconfig $interface $ip $BROADCAST $NETMASK
+		if [ -n "$router" ] ; then
+			echo "deleting routers"
+			while /sbin/route del default gw 0.0.0.0 dev $interface ; do
+				:
+			done
+			metric=0
+			for i in $router ; do
+				/sbin/route add default gw $i dev $interface metric $((metric++))
+			done
+		fi
+		;;
+esac
+exit 0
+EOF
 
     # take vol_id or blkid
     if [ -x  /lib/udev/vol_id ]; then
