* cosmetic changes to the build system: use colors and bold text to highlight some important messages that they don't get lost between the compiler outputs * add a new function for installing dependencies using the system's tools * on SUSE, use zypper instead of yum and work around some zypper specific idiocracies (no non-zero return code if the package cannot be found)
git-svn-id: http://openqrm.svn.sourceforge.net/svnroot/openqrm@502 f7cd0d49-994a-0410-81fc-ecfcdc9cdbae

diff --git a/trunk/src/include/openqrm-build-functions b/trunk/src/include/openqrm-build-functions
--- a/trunk/src/include/openqrm-build-functions
+++ b/trunk/src/include/openqrm-build-functions
@@ -13,7 +13,9 @@ if [ "$OPENQRM_SOURCE_DIR" == "" ]; then
 fi
 # source the openqrm-functions file for more features
 . $OPENQRM_SOURCE_DIR/include/openqrm-functions
-# source the openqrm-server.conf which resets the basedir again
+# include package functions for package management
+. $OPENQRM_SOURCE_DIR/include/openqrm-package-functions
+# source the openqrm-server.conf which resets the OPENQRM_SERVER_BASE_DIR again
 . $OPENQRM_SOURCE_DIR/etc/openqrm-server.conf
 
 OPENQRM_BUILD_DISTRIBUTION=`openqrm_get_distro`
@@ -25,10 +27,47 @@ else
 fi
 OPENQRM_INITRD_DIRECTORIES="bin etc etc/rc.d/init.d etc/sysconfig etc/X11 lib lib/modules lib/i686 loopfs mnt old_root proc sys sysroot usr usr/lib usr/bin usr/sbin var var/lock var/lock/subsys var/log var/run /var/lib /var/lib/nfs /var/lib/nfs/statd"
 
+# colorize/emphasize terminal output
+USE_COLORS=1
+
+#
+# Print a message to STDOUT
+#
+# $1: the message
+# $2: (optional) use "bold" to get bold-printed output
+#
+function print_message() {
+	bold="\033[1m"
+	esc="\033[m"
+	if [ $USE_COLORS == 1 -a "$2" == 'bold' ]; then
+		echo -e "${bold}${1}${esc}"
+	else
+		echo "$1"
+	fi
+}
+
+function print_error() {
+	bold="\033[1m"
+	red="\033[31m"
+	esc="\033[m"
+	if [ $USE_COLORS == 1 ]; then
+		echo -e "${red}ERROR: ${1}${esc}"
+	else
+		echo "ERROR: $1"
+	fi
+}
+
+function print_notice() {
+	echo "NOTICE: $1"
+}
 
 
-# function displaying the library files (not links) a binary depends on
+#
+# Display all library files (not links) a binary depends on
 # -> this is generic
+#
+# $1: path to the binary
+#
 function openqrm_build_find_libs() {
 	BINARY=$1
 	for LIBRARY in `ldd $BINARY | awk {' print $3 '}`; do
@@ -41,30 +80,26 @@ function openqrm_build_find_libs() {
 			echo $FULL_PATH_TO_LIBRARY/$REAL_LIBRARYFILE
 		fi
 	done
-
-
-
 }
 
 
 
-# function to check the requirements for the compile phase
-# -> this is for "make all" / comilation phase
+#
+# Check requirements for the compile phase
+# -> this is for "make all" / compilation phase
+#
 function openqrm_check_build_requirements() {
 	echo "Checking requirements for the compilation phase"
 	# check which command to use for checking the requirements
 	if [ -f /etc/debian_version ]; then
 		OPENQRM_PACKAGE_TYPE=deb
 		OPENQRM_REQUIREMENTS_CHECK_COMMAND="dpkg -L"
-		OPENQRM_PACKAGE_INSTALL_CMD="apt-get install"
 	elif [ -f /etc/redhat-release ]; then
 		OPENQRM_PACKAGE_TYPE=rpm
 		OPENQRM_REQUIREMENTS_CHECK_COMMAND="rpm -qs"
-		OPENQRM_PACKAGE_INSTALL_CMD="yum install"
 	elif [ -f /etc/SuSE-release ]; then
 		OPENQRM_PACKAGE_TYPE=rpm
 		OPENQRM_REQUIREMENTS_CHECK_COMMAND="rpm -qs"
-		OPENQRM_PACKAGE_INSTALL_CMD="yum install"
 	else
 		echo "NOTICE: Could not find out which compile-requirements to use"
 		echo "        Please make sure to have all needed components installed!"
@@ -73,45 +108,50 @@ function openqrm_check_build_requirements() {
 		return 0
 	fi
 
-	echo "openqrm-server requires : $OPENQRM_SERVER_BUILD_REQUIREMENTS"
+	# check for required packages and install them if possible
+	echo "openqrm-server requires: $OPENQRM_SERVER_BUILD_REQUIREMENTS"
 	for DEP in `echo $OPENQRM_SERVER_BUILD_REQUIREMENTS | sed -e "s/,//g"`; do
 		if $OPENQRM_REQUIREMENTS_CHECK_COMMAND $DEP 1>/dev/null 2>&1; then
-			echo "-> found $DEP installed"
+			print_message "found $DEP installed" bold
 		else
-			echo "NOTICE: Trying to automatically install $DEP ..."
-			if ! $OPENQRM_PACKAGE_INSTALL_CMD $DEP; then
-				echo "ERROR: $DEP could not be installed. Please install manually to continue"
+			print_notice "Trying to automatically install $DEP ..."
+			openqrm_install_os_dependency $DEP
+			if [ $? != 0 ]; then
+				print_error "$DEP could not be installed. Please install manually to continue"
 				return 1
 			fi
 		fi
 	done
 
-
 	# check if the build tmp directory is writable
 	if [ ! -d "$OPENQRM_BUILD_TMP_DIR" ]; then
 		if ! mkdir -p "$OPENQRM_BUILD_TMP_DIR"; then
-			echo "ERROR: $OPENQRM_BUILD_TMP_DIR could not be created by user `whoami`."
+			print_error "$OPENQRM_BUILD_TMP_DIR could not be created by user `whoami`."
 			return 1;
-		fi	
+		fi
 	elif [ ! -w "$OPENQRM_BUILD_TMP_DIR" -o ! -x "$OPENQRM_BUILD_TMP_DIR" ]; then
-		echo "ERROR: $OPENQRM_BUILD_TMP_DIR must exist and be writable by user `whoami`."
+		print_error "$OPENQRM_BUILD_TMP_DIR must exist and be writable by user `whoami`."
 		return 1;
 	fi
-
-
 
 	# get a list of plugins for checking their requirements
 	OPENQRM_PACKAGE_COMPONENT_LIST=`ls $OPENQRM_SOURCE_DIR/plugins | grep -v Makefile | grep -v CVS`
 	for OPENQRM_PLUGIN in $OPENQRM_PACKAGE_COMPONENT_LIST; do
-		. $OPENQRM_SOURCE_DIR/plugins/$OPENQRM_PLUGIN/etc/openqrm-plugin-$OPENQRM_PLUGIN"".conf
-		echo "openqrm-plugin-$OPENQRM_PLUGIN requires : `echo $OPENQRM_PLUGIN_BUILD_REQUIREMENTS`"
+		PLUGIN_CONF=$OPENQRM_SOURCE_DIR/plugins/$OPENQRM_PLUGIN/etc/openqrm-plugin-$OPENQRM_PLUGIN"".conf
+		if [ -f $PLUGIN_CONF ]; then
+			. $PLUGIN_CONF
+		else
+			print_notice "openqrm-plugin-$OPENQRM_PLUGIN has no config file. Unable to check dependencies!"
+			continue
+		fi
+		echo "openqrm-plugin-$OPENQRM_PLUGIN requires: `echo $OPENQRM_PLUGIN_BUILD_REQUIREMENTS`"
 		for DEP in `echo $OPENQRM_PLUGIN_BUILD_REQUIREMENTS | sed -e "s/,//g"`; do
 			if $OPENQRM_REQUIREMENTS_CHECK_COMMAND $DEP 1>/dev/null 2>&1; then
-				echo "-> found $DEP installed"
+				print_message "found $DEP installed" bold
 			else
 				echo "NOTICE: Trying to automatically install $DEP ..."
 				if ! $OPENQRM_PACKAGE_INSTALL_CMD $DEP; then
-					echo "ERROR: $DEP could not be installed. Please install manually to continue"
+					print_error "$DEP could not be installed. Please install manually to continue"
 					return 1
 				fi
 			fi
@@ -137,13 +177,16 @@ function openqrm_cache_or_download() {
 	OPENQRM_SOURCE_COMPONENT_FILE=`basename $OPENQRM_SOURCE_DOWNLOAD`
 	CURRENT_DIR=`pwd`
 	if [ -f $OPENQRM_BUILD_TMP_DIR/openqrm-build/$OPENQRM_SOURCE_COMPONENT_NAME/source/$OPENQRM_SOURCE_COMPONENT_FILE ]; then
-		echo "-> found component $OPENQRM_SOURCE_COMPONENT_NAME ($OPENQRM_SOURCE_COMPONENT_FILE) already downloaded"
+		print_message "-> found component $OPENQRM_SOURCE_COMPONENT_NAME ($OPENQRM_SOURCE_COMPONENT_FILE) already downloaded" bold
 	else
 		mkdir -p $OPENQRM_BUILD_TMP_DIR/openqrm-build/$OPENQRM_SOURCE_COMPONENT_NAME/source/
 		cd $OPENQRM_BUILD_TMP_DIR/openqrm-build/$OPENQRM_SOURCE_COMPONENT_NAME/source/
 		if ! wget $OPENQRM_SOURCE_DOWNLOAD; then
-			echo "ERROR: Could not download $OPENQRM_SOURCE_COMPONENT_NAME from $OPENQRM_SOURCE_DOWNLOAD"
-			echo "       Please put $OPENQRM_SOURCE_COMPONENT_FILE in $OPENQRM_BUILD_TMP_DIR/openqrm-build/$OPENQRM_SOURCE_COMPONENT_NAME/source/ and try again."
+			print_error "Could not download $OPENQRM_SOURCE_COMPONENT_NAME from " \
+				"$OPENQRM_SOURCE_DOWNLOAD" \
+			print_error "Please put $OPENQRM_SOURCE_COMPONENT_FILE in " \
+				"$OPENQRM_BUILD_TMP_DIR/openqrm-build/$OPENQRM_SOURCE_COMPONENT_NAME/source/" \
+				" and try again."
 			exit 1
 		fi
 	fi
@@ -205,8 +248,8 @@ function openqrm_compile_from_source() {
 		unset OPENQRM_CONFIGURE OPENQRM_PRE_MAKE OPENQRM_POST_MAKE
 		cd $CURRENT_DIR
 	else
-		echo "-> Found $OPENQRM_SOURCE_BINARY_RESULT already in the build-cache"
-		echo "-> Skipping compilation, taking the ready build component from the cache"
+		print_message "-> Found $OPENQRM_SOURCE_BINARY_RESULT already in the build-cache" bold
+		print_message "-> Skipping compilation, taking the ready built component from the cache" bold
 	fi
 }
 
@@ -244,7 +287,7 @@ function openqrm_create_default_initrd_template() {
 	. $OPENQRM_SOURCE_DIR/etc/build.conf/kudzu-knoppix.conf
 	OPENQRM_SOURCE_KUDZU_DIR="$OPENQRM_BUILD_TMP_DIR/openqrm-build/kudzu-knoppix/kudzu-knoppix-$OPENQRM_SOURCE_VERSION/"
 	. $OPENQRM_SOURCE_DIR/etc/build.conf/hwsetup.conf
-	
+
 	OPENQRM_SOURCE_HWSETUP_FILE=`basename $OPENQRM_SOURCE_DOWNLOAD`
 	OPENQRM_SOURCE_HWSETUP_DIR="$OPENQRM_BUILD_TMP_DIR/openqrm-build/hwsetup/hwsetup-$OPENQRM_SOURCE_VERSION/"
 	tar -C $OPENQRM_BUILD_TMP_DIR/openqrm-build/hwsetup/ -xzf $OPENQRM_BUILD_TMP_DIR/openqrm-build/hwsetup/$OPENQRM_SOURCE_HWSETUP_FILE
@@ -274,7 +317,7 @@ function openqrm_create_default_initrd_template() {
 		for LIB in `openqrm_build_find_libs $UTIL`; do
 			LIB=`echo $LIB | cut -d'-' -f1 | cut -d'.' -f1`
 			if [ "$LIB" != "/lib/" ]; then
-				cp -a $LIB""* $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/lib/
+				cp -af $LIB""* $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/lib/
 			fi
 		done
 	done
@@ -289,8 +332,8 @@ EOF
 	for DIR in $OPENQRM_INITRD_DIRECTORIES; do
 		mkdir -p $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/$DIR
 	done
-	touch $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/var/lib/nfs/rmtab 
-	touch $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/var/lib/nfs/xtab  
+	touch $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/var/lib/nfs/rmtab
+	touch $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/var/lib/nfs/xtab
 	touch $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/var/lib/nfs/etab
 	touch $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/var/lib/nfs/state
 	cd $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/etc
@@ -303,7 +346,7 @@ EOF
 	echo "shadow:     files" >> nsswitch.conf
 	echo "group:      files" >> nsswitch.conf
 	# cp libnss
-	cp -aR /lib/libnss_files* $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/lib/	
+	cp -aR /lib/libnss_files* $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/lib/
 	# installing hwdata, libkudzu and hwsetup
 	cp -aR $OPENQRM_BUILD_TMP_DIR/openqrm-build/hwdata-knoppix/hwdata-install/* $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/
 	cp -a $OPENQRM_SOURCE_KUDZU_DIR/libkudzu.a $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/lib/
diff --git a/trunk/src/include/openqrm-package-functions b/trunk/src/include/openqrm-package-functions
--- a/trunk/src/include/openqrm-package-functions
+++ b/trunk/src/include/openqrm-package-functions
@@ -21,66 +21,116 @@ done
 # get distribution
 export OPENQRM_PACKAGE_DISTRIBUTION=`openqrm_get_distro`
 
+#
+# Install a system dependency using the system's package manager
+#
+# $1: package name
+# returns the return code of the package manager; the only reliable check is
+# to check for a non-zero returncode (which means an error has occurred).
+#
+function openqrm_install_os_dependency() {
+	local PACKAGE=$1
+
+	# check which dependencies to use
+    if [ -f /etc/debian_version ]; then
+        local OPENQRM_PACKAGE_INSTALL_CMD="apt-get install"
+    elif [ -f /etc/redhat-release ]; then
+        local OPENQRM_PACKAGE_INSTALL_CMD="yum install"
+    elif [ -f /etc/SuSE-release ]; then
+        local OPENQRM_PACKAGE_INSTALL_CMD="zypper --non-interactive install"
+	fi
+
+	if [ ! -f /etc/SuSE-release ]; then
+		"$OPENQRM_PACKAGE_INSTALL_CMD" "$PACKAGE"
+		return $?
+	else
+		# special handling for SUSE and zypper. We get a 0 return code,
+		# even if the requested package is not available. This wrapper
+		# returns 1 if the package is not found.
+		local TMPFILE=$OPENQRM_BUILD_TMP_DIR/$(basename $0).$RANDOM.txt
+		LC_ALL=C $OPENQRM_PACKAGE_INSTALL_CMD "$PACKAGE" 2>&1 | tee "$TMPFILE"
+		local RETURNCODE=${PIPESTATUS[0]}
+		if cat "$TMPFILE" | grep -c "not found" >/dev/null ; then
+			rm "$TMPFILE"
+			return 1;
+		else
+			rm "$TMPFILE"
+			return $RETURNCODE
+		fi
+	fi
+}
+
+
 function openqrm_check_requirements() {
+	if [ ! -d "$OPENQRM_SERVER_BASE_DIR/openqrm/plugins" ]; then
+		print_error "$OPENQRM_SERVER_BASE_DIR/openqrm/plugins does not exist. Run make check after installing openQRM!"
+		return 1
+	fi
+
 	# check which dependencies to use
 	if [ -f /etc/debian_version ]; then
-		echo "Checking the requirements for Debian/Ubuntu based systems"
+		print_message "Checking the requirements for Debian/Ubuntu based systems ..."
 		OPENQRM_PACKAGE_TYPE=deb
 		OPENQRM_DEPENDENCY_CHECK_COMMAND="dpkg -L"
 		OPENQRM_PACKAGE_SYSTEM="debian"
-		OPENQRM_PACKAGE_INSTALL_CMD="apt-get install"
 	elif [ -f /etc/redhat-release ]; then
-		echo "Checking the requirements for Redhat based systems"
+		print_message "Checking the requirements for RedHat based systems ..."
 		OPENQRM_PACKAGE_TYPE=rpm
 		OPENQRM_DEPENDENCY_CHECK_COMMAND="rpm -qs"
 		OPENQRM_PACKAGE_SYSTEM="redhat"
-		OPENQRM_PACKAGE_INSTALL_CMD="yum install"
 	elif [ -f /etc/SuSE-release ]; then
-		echo "Checking the requirements for Suse based systems"
+		print_message "Checking the requirements for SUSE based systems ..."
 		OPENQRM_PACKAGE_TYPE=rpm
 		OPENQRM_DEPENDENCY_CHECK_COMMAND="rpm -qs"
 		OPENQRM_PACKAGE_SYSTEM="suse"
-		OPENQRM_PACKAGE_INSTALL_CMD="yum install"
 	else
-		echo "NOTICE: Could not find out which dependencies to use"
-		echo "        Please make sure to have all needed components installed!"
+		print_notice "NOTICE: Could not find out which dependencies to use" \
+			"Please make sure to have all needed components installed!"
 		sleep 4
-		echo "... Continuing anyway"
+		print_message "... Continuing anyway"
 		return 0
 	fi
 
-	echo "openqrm-server requires : $OPENQRM_SERVER_DEPENDENCIES"
+	print_message "openqrm-server requires: $OPENQRM_SERVER_DEPENDENCIES"
 	for DEP in `echo $OPENQRM_SERVER_DEPENDENCIES | sed -e "s/,//g"`; do
 		if $OPENQRM_DEPENDENCY_CHECK_COMMAND $DEP 1>/dev/null 2>&1; then
-			echo "-> found $DEP installed"
+			print_message "-> found $DEP installed"
 		else
-			echo "NOTICE: Trying to automatically install $DEP ..."
-			if ! $OPENQRM_PACKAGE_INSTALL_CMD $DEP; then
-				echo "ERROR: $DEP could not be installed. Please install manually to continue"
+			print_notice "Trying to automatically install $DEP ..."
+			openqrm_install_os_dependency $DEP
+			if [ $? != 0 ]; then
+				print_error "$DEP could not be installed. Please install manually to continue"
 				return 1
 			fi
 		fi
 	done
 
+
 	# get a list of plugins for checking their dependencies
 	OPENQRM_PACKAGE_COMPONENT_LIST=`ls $OPENQRM_SERVER_BASE_DIR/openqrm/plugins`
 	for OPENQRM_PLUGIN in $OPENQRM_PACKAGE_COMPONENT_LIST; do
-		. $OPENQRM_SOURCE_DIR/plugins/$OPENQRM_PLUGIN/etc/openqrm-plugin-$OPENQRM_PLUGIN"".conf
-		echo "openqrm-plugin-$OPENQRM_PLUGIN requires : `echo $OPENQRM_PLUGIN_DEPENDENCIES | sed -e "s/openqrm-server//g"`"
+		PLUGIN_CONF=$OPENQRM_SOURCE_DIR/plugins/$OPENQRM_PLUGIN/etc/openqrm-plugin-$OPENQRM_PLUGIN"".conf
+		if [ -f $PLUGIN_CONF ]; then
+			. $PLUGIN_CONF
+		else
+			print_notice "openqrm-plugin-$OPENQRM_PLUGIN has no config file. Unable to check dependencies!"
+			continue
+		fi
+		print_message "openqrm-plugin-$OPENQRM_PLUGIN requires: `echo $OPENQRM_PLUGIN_DEPENDENCIES | sed -e "s/openqrm-server//g"`"
 		for DEP in `echo $OPENQRM_PLUGIN_DEPENDENCIES | sed -e "s/,//g" | sed -e "s/openqrm-server//g"`; do
 			if $OPENQRM_DEPENDENCY_CHECK_COMMAND $DEP 1>/dev/null 2>&1; then
-				echo "-> found $DEP installed"
+				print_message "-> found $DEP installed"
 			else
-				echo "NOTICE: Trying to automatically install $DEP ..."
-				if ! $OPENQRM_PACKAGE_INSTALL_CMD $DEP; then
-					echo "ERROR: $DEP could not be installed. Please install manually to continue"
+				print_notice "Trying to automatically install $DEP ..."
+				openqrm_install_os_dependency $DEP
+				if [ $? != 0 ]; then
+					print_error "$DEP could not be installed. Please install manually to continue"
 					return 1
 				fi
 			fi
 		done
 	done
-	echo "Checking for required components finished successfully"
-
+	print_message "Checking for required components finished successfully"
 }
 
 
@@ -92,28 +142,28 @@ function openqrm_package() {
 	else
 		OPENQRM_PACKAGE_TYPE=rpm
 	fi
-	echo "Creating $OPENQRM_PACKAGE_TYPE packages for openQRM-server ver. $OPENQRM_SERVER_VERSION for $OPENQRM_PACKAGE_DISTRIBUTION"
+	print_message "Creating $OPENQRM_PACKAGE_TYPE packages for openQRM-server ver. $OPENQRM_SERVER_VERSION for $OPENQRM_PACKAGE_DISTRIBUTION"
 
 	# which components to build
 	OPENQRM_PACKAGE_COMPONENT_LIST=`ls $OPENQRM_SOURCE_DIR/plugins | grep -v Makefile`
 	OPENQRM_PACKAGE_COMPONENT_LIST="openqrm-server-entire openqrm-server "`echo $OPENQRM_PACKAGE_COMPONENT_LIST | sed -e "s/\n//g"`
-	echo "Packing the following components : $OPENQRM_PACKAGE_COMPONENT_LIST"
+	print_message "Packing the following components: $OPENQRM_PACKAGE_COMPONENT_LIST"
 
 	########################## RPM PACKAGING ##########################
-	
+
 	# decide on rpm or deb package
 	if [ "$OPENQRM_PACKAGE_TYPE" == "rpm" ]; then
-		
-		OPENQRM_PACKAGE_ARCHITECTURE=` uname -i`	
+
+		OPENQRM_PACKAGE_ARCHITECTURE=` uname -i`
 		for OPENQRM_PACKAGE_COMPONENT in $OPENQRM_PACKAGE_COMPONENT_LIST; do
 
-			echo "Starting rpm packaging for $OPENQRM_PACKAGE_COMPONENT"
+			print_message "Starting rpm packaging for $OPENQRM_PACKAGE_COMPONENT"
 			# check if to package the openqrm-server or plugins
 			if [ "$OPENQRM_PACKAGE_COMPONENT" == "openqrm-server" ] || [ "$OPENQRM_PACKAGE_COMPONENT" == "openqrm-server-entire" ]; then
 				# we package the server (without any plugins)
-				echo "Packaging the openQRM-server"
+				print_message "Packaging the openQRM-server"
 				OPENQRM_PACKAGE_NAME=$OPENQRM_PACKAGE_COMPONENT
-				
+
 				# set the server dependencies / decide on redhat or suse dependencies
 				OPENQRM_PACKAGE_DEPENDENCIES=$OPENQRM_SERVER_DEPENDENCIES
 				if [ -f /etc/redhat-release ]; then
@@ -164,7 +214,7 @@ function openqrm_package() {
 				cp -aR ../src/* $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_SERVER_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/source/openqrm-server-$OPENQRM_SERVER_VERSION/
 				rm -rf `find $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_SERVER_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/source/openqrm-server-$OPENQRM_SERVER_VERSION/ -name .svn`
 				rm -f /usr/src/$OPENQRM_PACKAGE_SUB_DIR/SOURCES/openqrm-server-$OPENQRM_SERVER_VERSION.tgz
-				tar -C $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_SERVER_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/source/ -czf /usr/src/$OPENQRM_PACKAGE_SUB_DIR/SOURCES/openqrm-server-$OPENQRM_SERVER_VERSION.tgz openqrm-server-$OPENQRM_SERVER_VERSION/ 
+				tar -C $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_SERVER_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/source/ -czf /usr/src/$OPENQRM_PACKAGE_SUB_DIR/SOURCES/openqrm-server-$OPENQRM_SERVER_VERSION.tgz openqrm-server-$OPENQRM_SERVER_VERSION/
 				rm -rf $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_SERVER_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/source/openqrm-server-$OPENQRM_SERVER_VERSION
 
 				# build the rpm package
@@ -173,7 +223,7 @@ function openqrm_package() {
 			else
 
 				# we package a plugin
-				echo "Packaging the openQRM plugin-$OPENQRM_PACKAGE_COMPONENT"
+				print_message "Packaging the openQRM plugin-$OPENQRM_PACKAGE_COMPONENT"
 				OPENQRM_PACKAGE_NAME=openqrm-plugin-$OPENQRM_PACKAGE_COMPONENT
 
 				# get the plugin configuration
@@ -216,7 +266,7 @@ function openqrm_package() {
 				cp -aR ../src/* $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_PLUGIN_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/source/openqrm-plugin-$OPENQRM_PACKAGE_COMPONENT-$OPENQRM_PLUGIN_VERSION/
 				rm -rf `find $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_PLUGIN_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/source/openqrm-plugin-$OPENQRM_PACKAGE_COMPONENT-$OPENQRM_PLUGIN_VERSION/ -name CVS`
 				rm -f /usr/src/$OPENQRM_PACKAGE_SUB_DIR/SOURCES/openqrm-plugin-$OPENQRM_PACKAGE_COMPONENT-$OPENQRM_PLUGIN_VERSION.tgz
-				tar -C $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_PLUGIN_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/source/ -czf /usr/src/$OPENQRM_PACKAGE_SUB_DIR/SOURCES/openqrm-plugin-$OPENQRM_PACKAGE_COMPONENT-$OPENQRM_PLUGIN_VERSION.tgz openqrm-plugin-$OPENQRM_PACKAGE_COMPONENT-$OPENQRM_PLUGIN_VERSION/ 
+				tar -C $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_PLUGIN_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/source/ -czf /usr/src/$OPENQRM_PACKAGE_SUB_DIR/SOURCES/openqrm-plugin-$OPENQRM_PACKAGE_COMPONENT-$OPENQRM_PLUGIN_VERSION.tgz openqrm-plugin-$OPENQRM_PACKAGE_COMPONENT-$OPENQRM_PLUGIN_VERSION/
 				rm -rf $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_PLUGIN_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/source/openqrm-plugin-$OPENQRM_PACKAGE_COMPONENT-$OPENQRM_SERVER_VERSION
 
 				# build the deb package
@@ -230,17 +280,17 @@ function openqrm_package() {
 
 	elif [ "$OPENQRM_PACKAGE_TYPE" == "deb" ]; then
 
-		OPENQRM_PACKAGE_ARCHITECTURE=`dpkg --print-architecture`	
+		OPENQRM_PACKAGE_ARCHITECTURE=`dpkg --print-architecture`
 		for OPENQRM_PACKAGE_COMPONENT in $OPENQRM_PACKAGE_COMPONENT_LIST; do
 
-			echo "Starting deb packaging for $OPENQRM_PACKAGE_COMPONENT"
+			print_message "Starting deb packaging for $OPENQRM_PACKAGE_COMPONENT"
 
 			# check if to package the openqrm-server or plugins
 			if [ "$OPENQRM_PACKAGE_COMPONENT" == "openqrm-server" ] || [ "$OPENQRM_PACKAGE_COMPONENT" == "openqrm-server-entire" ]; then
 				# we package the server (without any plugins)
-				echo "Packaging the openQRM-server"
+				print_message "Packaging the openQRM-server"
 				OPENQRM_PACKAGE_NAME=$OPENQRM_PACKAGE_COMPONENT
-				
+
 				# set the server dependencies
 				OPENQRM_PACKAGE_DEPENDENCIES=$OPENQRM_SERVER_DEPENDENCIES
 
@@ -249,7 +299,7 @@ function openqrm_package() {
 				mkdir -p $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_SERVER_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/DEBIAN
 
 				# create debian-binary file
-				echo "2.0" > $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_SERVER_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/DEBIAN/debian-binary
+				print_message "2.0" > $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_SERVER_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/DEBIAN/debian-binary
 
 				# create postinst + prerm
 				cp $OPENQRM_PACKAGE_TMP_DIR/packageroot/$OPENQRM_SERVER_BASE_DIR/openqrm/etc/init.d/openqrm-server.postinstall $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_SERVER_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/DEBIAN/postinst
@@ -291,7 +341,7 @@ function openqrm_package() {
 			else
 
 				# we package a plugin
-				echo "Packaging the openQRM plugin-$OPENQRM_PACKAGE_COMPONENT"
+				print_message "Packaging the openQRM plugin-$OPENQRM_PACKAGE_COMPONENT"
 				OPENQRM_PACKAGE_NAME=openqrm-plugin-$OPENQRM_PACKAGE_COMPONENT
 
 				# get the plugin configuration
@@ -313,7 +363,7 @@ function openqrm_package() {
 					> $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_PLUGIN_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/DEBIAN/control
 
 				# create debian-binary file
-				echo "2.0" > $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_PLUGIN_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/DEBIAN/debian-binary
+				print_message "2.0" > $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_PLUGIN_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/DEBIAN/debian-binary
 
 				# create postinst + prerm
 				cp $OPENQRM_PACKAGE_TMP_DIR/packageroot/$OPENQRM_SERVER_BASE_DIR/openqrm/plugins/$OPENQRM_PACKAGE_COMPONENT/etc/init.d/$OPENQRM_PACKAGE_NAME"".postinstall $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_PLUGIN_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/DEBIAN/postinst
@@ -331,9 +381,9 @@ function openqrm_package() {
 			fi
 
 		done
-	
+
 	else
-		echo "ERROR: package type $OPENQRM_PACKAGE_TYPE not supported yet"
+		print_error "package type $OPENQRM_PACKAGE_TYPE not supported yet"
 		exit 1
 	fi
 
