trying to resolve the dependencies automatically
git-svn-id: http://openqrm.svn.sourceforge.net/svnroot/openqrm@381 f7cd0d49-994a-0410-81fc-ecfcdc9cdbae

diff --git a/trunk/src/include/openqrm-build-functions b/trunk/src/include/openqrm-build-functions
--- a/trunk/src/include/openqrm-build-functions
+++ b/trunk/src/include/openqrm-build-functions
@@ -55,13 +55,16 @@ function openqrm_check_build_requirements() {
 	# check which command to use for checking the requirements
 	if [ -f /etc/debian_version ]; then
 		OPENQRM_PACKAGE_TYPE=deb
-		OPENQRM_REQUIREMENTS_CHECK_COMMAND="dpkg -s"
+		OPENQRM_REQUIREMENTS_CHECK_COMMAND="dpkg -L"
+		OPENQRM_PACKAGE_INSTALL_CMD="apt-get install"
 	elif [ -f /etc/redhat-release ]; then
 		OPENQRM_PACKAGE_TYPE=rpm
 		OPENQRM_REQUIREMENTS_CHECK_COMMAND="rpm -qs"
+		OPENQRM_PACKAGE_INSTALL_CMD="yum install"
 	elif [ -f /etc/SuSE-release ]; then
 		OPENQRM_PACKAGE_TYPE=rpm
 		OPENQRM_REQUIREMENTS_CHECK_COMMAND="rpm -qs"
+		OPENQRM_PACKAGE_INSTALL_CMD="yum install"
 	else
 		echo "NOTICE: Could not find out which compile-requirements to use"
 		echo "        Please make sure to have all needed components installed!"
@@ -75,8 +78,11 @@ function openqrm_check_build_requirements() {
 		if $OPENQRM_REQUIREMENTS_CHECK_COMMAND $DEP 1>/dev/null 2>&1; then
 			echo "-> found $DEP installed"
 		else
-			echo "ERROR: $DEP not installed. Please install to continue"
-			return 1
+			echo "NOTICE: Trying to automatically install $DEP ..."
+			if ! $OPENQRM_PACKAGE_INSTALL_CMD $DEP; then
+				echo "ERROR: $DEP could not be installed. Please install manually to continue"
+				return 1
+			fi
 		fi
 	done
 
@@ -89,8 +95,11 @@ function openqrm_check_build_requirements() {
 			if $OPENQRM_REQUIREMENTS_CHECK_COMMAND $DEP 1>/dev/null 2>&1; then
 				echo "-> found $DEP installed"
 			else
-				echo "ERROR: $DEP not installed. Please install to continue"
-				return 1
+				echo "NOTICE: Trying to automatically install $DEP ..."
+				if ! $OPENQRM_PACKAGE_INSTALL_CMD $DEP; then
+					echo "ERROR: $DEP could not be installed. Please install manually to continue"
+					return 1
+				fi
 			fi
 		done
 	done
diff --git a/trunk/src/include/openqrm-package-functions b/trunk/src/include/openqrm-package-functions
--- a/trunk/src/include/openqrm-package-functions
+++ b/trunk/src/include/openqrm-package-functions
@@ -26,18 +26,21 @@ function openqrm_check_requirements() {
 	if [ -f /etc/debian_version ]; then
 		echo "Checking the requirements for Debian/Ubuntu based systems"
 		OPENQRM_PACKAGE_TYPE=deb
-		OPENQRM_DEPENDENCY_CHECK_COMMAND="dpkg -s"
+		OPENQRM_DEPENDENCY_CHECK_COMMAND="dpkg -L"
 		OPENQRM_PACKAGE_SYSTEM="debian"
+		OPENQRM_PACKAGE_INSTALL_CMD="apt-get install"
 	elif [ -f /etc/redhat-release ]; then
 		echo "Checking the requirements for Redhat based systems"
 		OPENQRM_PACKAGE_TYPE=rpm
 		OPENQRM_DEPENDENCY_CHECK_COMMAND="rpm -qs"
 		OPENQRM_PACKAGE_SYSTEM="redhat"
+		OPENQRM_PACKAGE_INSTALL_CMD="yum install"
 	elif [ -f /etc/SuSE-release ]; then
 		echo "Checking the requirements for Suse based systems"
 		OPENQRM_PACKAGE_TYPE=rpm
 		OPENQRM_DEPENDENCY_CHECK_COMMAND="rpm -qs"
 		OPENQRM_PACKAGE_SYSTEM="suse"
+		OPENQRM_PACKAGE_INSTALL_CMD="yum install"
 	else
 		echo "NOTICE: Could not find out which dependencies to use"
 		echo "        Please make sure to have all needed components installed!"
@@ -51,8 +54,11 @@ function openqrm_check_requirements() {
 		if $OPENQRM_DEPENDENCY_CHECK_COMMAND $DEP 1>/dev/null 2>&1; then
 			echo "-> found $DEP installed"
 		else
-			echo "ERROR: $DEP not installed. Please install to continue"
-			return 1
+			echo "NOTICE: Trying to automatically install $DEP ..."
+			if ! $OPENQRM_PACKAGE_INSTALL_CMD $DEP; then
+				echo "ERROR: $DEP could not be installed. Please install manually to continue"
+				return 1
+			fi
 		fi
 	done
 
@@ -65,8 +71,11 @@ function openqrm_check_requirements() {
 			if $OPENQRM_DEPENDENCY_CHECK_COMMAND $DEP 1>/dev/null 2>&1; then
 				echo "-> found $DEP installed"
 			else
-				echo "ERROR: $DEP not installed. Please install to continue"
-				return 1
+				echo "NOTICE: Trying to automatically install $DEP ..."
+				if ! $OPENQRM_PACKAGE_INSTALL_CMD $DEP; then
+					echo "ERROR: $DEP could not be installed. Please install manually to continue"
+					return 1
+				fi
 			fi
 		done
 	done
