;) try to create if not exist
git-svn-id: http://openqrm.svn.sourceforge.net/svnroot/openqrm@432 f7cd0d49-994a-0410-81fc-ecfcdc9cdbae

diff --git a/trunk/src/include/openqrm-build-functions b/trunk/src/include/openqrm-build-functions
--- a/trunk/src/include/openqrm-build-functions
+++ b/trunk/src/include/openqrm-build-functions
@@ -88,7 +88,12 @@ function openqrm_check_build_requirements() {
 
 
 	# check if the build tmp directory is writable
-	if [ ! -d "$OPENQRM_BUILD_TMP_DIR" -o ! -w "$OPENQRM_BUILD_TMP_DIR" -o ! -x "$OPENQRM_BUILD_TMP_DIR" ]; then
+	if [ ! -d "$OPENQRM_BUILD_TMP_DIR" ]; then
+		if ! mkdir -p "$OPENQRM_BUILD_TMP_DIR"; then
+			echo "ERROR: $OPENQRM_BUILD_TMP_DIR could not be created by user `whoami`."
+			return 1;
+		fi	
+	elif [ ! -w "$OPENQRM_BUILD_TMP_DIR" -o ! -x "$OPENQRM_BUILD_TMP_DIR" ]; then
 		echo "ERROR: $OPENQRM_BUILD_TMP_DIR must exist and be writable by user `whoami`."
 		return 1;
 	fi
