improved locking enhanced virtualization plugins so that they are also able to run on the openQRM-server as virtualization host.
git-svn-id: http://openqrm.svn.sourceforge.net/svnroot/openqrm@571 f7cd0d49-994a-0410-81fc-ecfcdc9cdbae

diff --git a/trunk/src/plugins/linux-vserver/bin/openqrm-linux-vserver b/trunk/src/plugins/linux-vserver/bin/openqrm-linux-vserver
--- a/trunk/src/plugins/linux-vserver/bin/openqrm-linux-vserver
+++ b/trunk/src/plugins/linux-vserver/bin/openqrm-linux-vserver
@@ -5,7 +5,19 @@ OPENQRM_SERVER_BASE_DIR=$(dirname $0)/../../../..
 OPENQRM_SERVER_BASE_DIR=$(pushd $OPENQRM_SERVER_BASE_DIR > /dev/null && echo $PWD && popd > /dev/null)
 . $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
 . $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/linux-vserver/include/openqrm-plugin-linux-vserver-functions
-OPENQRM_POSTENCODE="$resource_basedir/openqrm/sbin/openqrm-postencode.py"
+if [ -f $OPENQRM_RESOURCE_PARAMETER_FILE ]; then
+	. $OPENQRM_RESOURCE_PARAMETER_FILE
+	OPENQRM_SERVER_IP=$resource_openqrmserver
+	SYSTEM_IP=$resource_ip
+elif [ -f $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf ]; then
+	. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
+	. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
+	openqrm_server_get_config
+	OPENQRM_SERVER_IP=$OPENQRM_SERVER_IP_ADDRESS
+	SYSTEM_IP=$OPENQRM_SERVER_IP_ADDRESS
+	resource_id=0
+fi
+OPENQRM_POSTENCODE="$OPENQRM_SERVER_BASE_DIR/openqrm/sbin/openqrm-postencode.py"
 OPENQRM_LINUX_VSERVER_IDLE_TEMPLATE="$OPENQRM_SERVER_BASE_DIR/openqrm/plugins/linux-vserver/etc/templates/openqrm-initrd-default.tgz"
 export LANG=C
 
@@ -109,17 +121,19 @@ case "$LINUX_VSERVER_COMMAND" in
 			linux_vserver_usage
 		fi
 		CURRENT_DIR=`pwd`
+		linux_vserver_lock aquire
 		echo "Creating Linux-VServer vm $LINUX_VSERVER_VM_NAME -> /etc/vservers/$LINUX_VSERVER_VM_NAME"
 		# gathering some infos
 		if [ "$LINUX_VSERVER_VM_IP" == "dhcp" ]; then
 			echo "-> gathering an ip-address for $LINUX_VSERVER_VM_MAC ..."
 			if ! linux_vserver_get_next_ip $LINUX_VSERVER_VM_MAC; then
+				linux_vserver_lock release
 				exit 1			
 			fi
 			export LINUX_VSERVER_VM_IP=$PARTITION_IP
 			export OPENQRM_LINUX_VSERVER_SUBNET_MASK=$PARTITION_SUBNET
 		else
-			export OPENQRM_LINUX_VSERVER_SUBNET_MASK=`ifconfig | grep $resource_ip | cut -d':' -f3 | awk {' print $1 '}`
+			export OPENQRM_LINUX_VSERVER_SUBNET_MASK=`ifconfig | grep $SYSTEM_IP | cut -d':' -f3 | awk {' print $1 '}`
 		fi
 		export OPENQRM_LINUX_VSERVER_DEFAULT_GATEWAY=`route -n | grep ^0.0.0.0 | head -n1 | awk {' print $2 '}`
 		export OPENQRM_RESOURCE_ID=-1
@@ -214,31 +228,34 @@ EOF
 
 		# send new resource to openQRM to get resource-config
 		mkdir -p `dirname $OPENQRM_VM_DIR/$LINUX_VSERVER_VM_NAME/$OPENQRM_RESOURCE_PARAMETER_FILE`
-		wget -q -O $OPENQRM_VM_DIR/$LINUX_VSERVER_VM_NAME/$OPENQRM_RESOURCE_PARAMETER_FILE "http://$resource_openqrmserver/openqrm/action/resource-monitor.php?resource_command=get_parameter&resource_id=$OPENQRM_RESOURCE_ID&resource_mac=$LINUX_VSERVER_VM_MAC&resource_ip=$LINUX_VSERVER_VM_IP"
+		wget -q -O $OPENQRM_VM_DIR/$LINUX_VSERVER_VM_NAME/$OPENQRM_RESOURCE_PARAMETER_FILE "http://$OPENQRM_SERVER_IP/openqrm/action/resource-monitor.php?resource_command=get_parameter&resource_id=$OPENQRM_RESOURCE_ID&resource_mac=$LINUX_VSERVER_VM_MAC&resource_ip=$LINUX_VSERVER_VM_IP"
 
 		# add to a main vif config file, start all at init
 		echo "$LINUX_VSERVER_VM_INTERFACE $LINUX_VSERVER_VM_NAME" >> $OPENQRM_VIF_CONFIG
 		# bring up vethd interface
 		if ! linux_vserver_manage_vif start $LINUX_VSERVER_VM_NAME; then
+			linux_vserver_lock release
 			exit 1
 		fi
 		# start as idle
 		nohup vserver $LINUX_VSERVER_VM_NAME start &
 		# restart openqrm-exec
 		linux_vserver_restart_exec
+		linux_vserver_lock release
 		;;
 	start)
+		linux_vserver_lock aquire
 		echo "Starting Linux-VServer vm $LINUX_VSERVER_VM_NAME"
 		# source current parameters of the vm
 		. $OPENQRM_VM_DIR/$LINUX_VSERVER_VM_NAME/$OPENQRM_RESOURCE_PARAMETER_FILE
 		# update parameters for the resource
-		wget -q -O $OPENQRM_VM_DIR/$LINUX_VSERVER_VM_NAME/$OPENQRM_RESOURCE_PARAMETER_FILE "http://$resource_openqrmserver/openqrm/action/resource-monitor.php?resource_command=get_parameter&resource_id=$resource_id&resource_mac=$resource_mac&resource_ip=$resource_ip"
+		wget -q -O $OPENQRM_VM_DIR/$LINUX_VSERVER_VM_NAME/$OPENQRM_RESOURCE_PARAMETER_FILE "http://$OPENQRM_SERVER_IP/openqrm/action/resource-monitor.php?resource_command=get_parameter&resource_id=$resource_id&resource_mac=$resource_mac&resource_ip=$resource_ip"
 		. $OPENQRM_VM_DIR/$LINUX_VSERVER_VM_NAME/$OPENQRM_RESOURCE_PARAMETER_FILE
 		# check if assigned to an appliance or idle 
 		if [ "$image_type" != "ram" ]; then
 			eval $image_deployment_parameter
 			# get the root-mount functions according the deployment type
-			wget -q -O $OPENQRM_VM_CONFIG_DIR/$LINUX_VSERVER_VM_NAME/root-mount.$image_type-deployment "http://$resource_openqrmserver/openqrm/boot-service/root-mount.$image_type-deployment"
+			wget -q -O $OPENQRM_VM_CONFIG_DIR/$LINUX_VSERVER_VM_NAME/root-mount.$image_type-deployment "http://$OPENQRM_SERVER_IP/openqrm/boot-service/root-mount.$image_type-deployment"
 			# adapt root-mount functions of the deployment method
 			sed -i -e "s#/mnt2#XXXXX#g" $OPENQRM_VM_CONFIG_DIR/$LINUX_VSERVER_VM_NAME/root-mount.$image_type-deployment
 			sed -i -e "s#/mnt#$OPENQRM_VM_DIR/$LINUX_VSERVER_VM_NAME#g" $OPENQRM_VM_CONFIG_DIR/$LINUX_VSERVER_VM_NAME/root-mount.$image_type-deployment
@@ -263,8 +280,10 @@ EOF
 		nohup vserver $LINUX_VSERVER_VM_NAME start &
 		# restart openqrm-exec
 		linux_vserver_restart_exec
+		linux_vserver_lock release
 		;;
 	stop)
+		linux_vserver_lock aquire
 		echo "Stopping Linux-VServer vm $LINUX_VSERVER_VM_NAME"
 		# source current parameters of the vm
 		. $OPENQRM_VM_DIR/$LINUX_VSERVER_VM_NAME/$OPENQRM_RESOURCE_PARAMETER_FILE
@@ -279,13 +298,17 @@ EOF
 			# umount
 			umount $OPENQRM_VM_DIR/$LINUX_VSERVER_VM_NAME
 		fi
+		linux_vserver_lock release
 		;;
 	reboot)
+		linux_vserver_lock aquire
 		echo "Rebooting Linux-VServer vm $LINUX_VSERVER_VM_NAME"
 		nohup vserver $LINUX_VSERVER_VM_NAME restart &
 		linux_vserver_restart_exec
+		linux_vserver_lock release
 		;;
 	delete)
+		linux_vserver_lock aquire
 		echo "Removing Linux-VServer vm $LINUX_VSERVER_VM_NAME"
 		LINUX_VSERVER_VM_INTERFACE=`cat $OPENQRM_VM_CONFIG_DIR/$LINUX_VSERVER_VM_NAME/interfaces/0/dev`
 		vserver $LINUX_VSERVER_VM_NAME stop
@@ -295,14 +318,17 @@ EOF
 		# bring down vethd interface
 		if ! linux_vserver_manage_vif stop $LINUX_VSERVER_VM_NAME; then
 			exit 1			
+			linux_vserver_lock release
 		fi
 		sed -i -e "s/$LINUX_VSERVER_VM_INTERFACE.*//g" $OPENQRM_VIF_CONFIG
+		linux_vserver_lock release
 		;;
 	list)
 		echo "Listing Linux-VServer vms"
 		vserver-stat
 		;;
 	post_vm_list)
+		linux_vserver_lock aquire
 		echo "Posting vm list to the openQRM-server"
 		VM_LIST_TMP=$resource_id.vm_list
 		vserver-stat > $VM_LIST_TMP
@@ -310,12 +336,13 @@ EOF
 		cat $VM_LIST_TMP | sed -e "s/^/#/g" > $VM_LIST_TMP.up
 		mv -f $VM_LIST_TMP.up $VM_LIST_TMP
 		ls /etc/vservers/ | grep -v newvserver-vars | grep -v openqrm-vif.conf >> $VM_LIST_TMP
-		if ! wget -q -O /dev/null --http-user=$LINUX_VSERVER_OPENQRM_USERNAME --http-password=$LINUX_VSERVER_OPENQRM_PASSWORD  --post-file=`$OPENQRM_POSTENCODE $VM_LIST_TMP` http://$resource_openqrmserver/openqrm/base/plugins/linux-vserver/linux-vserver-action.php?linux_vserver_command=get_linux_vserver; then
-			echo "ERROR: Could not post vm list to the openQRM-server at $resource_openqrmserver!"
-			echo "ERROR: Could not post vm list to the openQRM-server at $resource_openqrmserver!" | logger
+		if ! wget -q -O /dev/null --http-user=$LINUX_VSERVER_OPENQRM_USERNAME --http-password=$LINUX_VSERVER_OPENQRM_PASSWORD  --post-file=`$OPENQRM_POSTENCODE $VM_LIST_TMP` http://$OPENQRM_SERVER_IP/openqrm/base/plugins/linux-vserver/linux-vserver-action.php?linux_vserver_command=get_linux_vserver; then
+			echo "ERROR: Could not post vm list to the openQRM-server at $OPENQRM_SERVER_IP!"
+			echo "ERROR: Could not post vm list to the openQRM-server at $OPENQRM_SERVER_IP!" | logger
 		fi
 		rm -f $VM_LIST_TMP
 		rm -f $VM_LIST_TMP.post
+		linux_vserver_lock release
 		;;
 	*)
 		linux_vserver_usage
diff --git a/trunk/src/plugins/linux-vserver/etc/init.d/linux-vserver b/trunk/src/plugins/linux-vserver/etc/init.d/linux-vserver
--- a/trunk/src/plugins/linux-vserver/etc/init.d/linux-vserver
+++ b/trunk/src/plugins/linux-vserver/etc/init.d/linux-vserver
@@ -1,11 +1,18 @@
 #!/bin/bash
 # this is the boot-service init script for the Linux-VServer-hosts
 
-export `eval cat /proc/cmdline`	
-. /var/openqrm/openqrm-resource.conf
-export OPENQRM_SERVER_BASE_DIR=$resource_basedir
+OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
 . $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
 . $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/linux-vserver/include/openqrm-plugin-linux-vserver-functions
+if [ -f $OPENQRM_RESOURCE_PARAMETER_FILE ]; then
+	. $OPENQRM_RESOURCE_PARAMETER_FILE
+	OPENQRM_SERVER_IP=$resource_openqrmserver
+elif [ -f $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf ]; then
+	. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
+	. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
+	openqrm_server_get_config
+	OPENQRM_SERVER_IP=$OPENQRM_SERVER_IP_ADDRESS
+fi
 
 
 function linux_vserver_start() {
@@ -13,8 +20,8 @@ function linux_vserver_start() {
 	linux_vserver_stop 1>/dev/null 2>&1
 	# download the initrd
 	mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/linux-vserver/etc/templates
-	if ! wget -q -O $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/linux-vserver/etc/templates/openqrm-initrd-default.tgz http://$resource_openqrmserver/openqrm/boot-service/openqrm-initrd-default.tgz; then
-		echo "ERROR: Could not download http://$resource_openqrmserver/openqrm/boot-service/openqrm-initrd-default.tgz"
+	if ! wget -q -O $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/linux-vserver/etc/templates/openqrm-initrd-default.tgz http://$OPENQRM_SERVER_IP/openqrm/boot-service/openqrm-initrd-default.tgz; then
+		echo "ERROR: Could not download http://$OPENQRM_SERVER_IP/openqrm/boot-service/openqrm-initrd-default.tgz"
 		return 1
 	fi
 	# start all vifs
diff --git a/trunk/src/plugins/linux-vserver/include/openqrm-plugin-linux-vserver-functions b/trunk/src/plugins/linux-vserver/include/openqrm-plugin-linux-vserver-functions
--- a/trunk/src/plugins/linux-vserver/include/openqrm-plugin-linux-vserver-functions
+++ b/trunk/src/plugins/linux-vserver/include/openqrm-plugin-linux-vserver-functions
@@ -1,16 +1,22 @@
 #!/bin/bash
 # this is the functions file for the linux-vserver-plugin
 
-if [ -f /var/openqrm/openqrm-resource.conf ]; then
-	. /var/openqrm/openqrm-resource.conf
+export LANG=C
+if [ "$OPENQRM_SERVER_BASE_DIR" == "" ]; then
+	echo "ERROR: Please export OPENQRM_SERVER_BASE_DIR before sourcing $0"
+	exit 1
 fi
-VETH="$resource_basedir/openqrm/plugins/linux-vserver/bin/vethd"
+
+VETH="$OPENQRM_SERVER_BASE_DIR/openqrm/plugins/linux-vserver/bin/vethd"
 LINUX_VSERVER_VDEVICE_NAME="lvif"
 # using the linux-vserver-tools domain location
 OPENQRM_VM_DIR=/var/lib/vservers/
 OPENQRM_VM_CONFIG_DIR=/etc/vservers/
 OPENQRM_VIF_CONFIG="$OPENQRM_VM_CONFIG_DIR/openqrm-vif.conf"
-
+LINUX_VSERVER_LOCK_FILE=/var/run/lvm-storage/lvm-storage-plugin.lock
+LINUX_VSERVER_LOCK_DELAY=5
+LINUX_VSERVER_LOCK_RETRY=100
+LINUX_VSERVER_LOCK_TIMEOUT=500
 ################ common linux-vserver functions
 
 # logs for linux-vserver
@@ -27,18 +33,18 @@ function linux_vserver_lock() {
 	local COMMAND=$1
 	local RET=1
 	
-	if [ ! -d `dirname $LVM_MGMT_LOCK_FILE` ]; then
-		mkdir -p `dirname $LVM_MGMT_LOCK_FILE`
+	if [ ! -d `dirname $LINUX_VSERVER_LOCK_FILE` ]; then
+		mkdir -p `dirname $LINUX_VSERVER_LOCK_FILE`
 	fi
 	case "$COMMAND" in
 		aquire)
-				lockfile -s $LVM_MGMT_LOCK_DELAY -r $LVM_MGMT_LOCK_RETRY -l $LVM_MGMT_LOCK_TIMEOUT $LVM_MGMT_LOCK_FILE
+				lockfile -s $LINUX_VSERVER_LOCK_DELAY -r $LINUX_VSERVER_LOCK_RETRY -l $LINUX_VSERVER_LOCK_TIMEOUT $LINUX_VSERVER_LOCK_FILE
 				RET=$?
 				linux_vserver_log linux_vserver_lock "Aquired the lock"
 				return $RET
 				;;
 		release)
-				/bin/rm -f $LVM_MGMT_LOCK_FILE
+				/bin/rm -f $LINUX_VSERVER_LOCK_FILE
 				RET=$?
 				linux_vserver_log linux_vserver_lock "Released the lock"
 				return $RET
diff --git a/trunk/src/plugins/vmware-server/bin/openqrm-vmware-server b/trunk/src/plugins/vmware-server/bin/openqrm-vmware-server
--- a/trunk/src/plugins/vmware-server/bin/openqrm-vmware-server
+++ b/trunk/src/plugins/vmware-server/bin/openqrm-vmware-server
@@ -3,9 +3,19 @@
 # this script automatically manages vmware-server
 OPENQRM_SERVER_BASE_DIR=$(dirname $0)/../../../..
 OPENQRM_SERVER_BASE_DIR=$(pushd $OPENQRM_SERVER_BASE_DIR > /dev/null && echo $PWD && popd > /dev/null)
+. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
 . $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/vmware-server/include/openqrm-plugin-vmware-server-functions
-. /var/openqrm/openqrm-resource.conf
-OPENQRM_POSTENCODE="$resource_basedir/openqrm/sbin/openqrm-postencode.py"
+if [ -f $OPENQRM_RESOURCE_PARAMETER_FILE ]; then
+	. $OPENQRM_RESOURCE_PARAMETER_FILE
+	OPENQRM_SERVER_IP=$resource_openqrmserver
+elif [ -f $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf ]; then
+	. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
+	. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
+	openqrm_server_get_config
+	OPENQRM_SERVER_IP=$OPENQRM_SERVER_IP_ADDRESS
+	resource_id=0
+fi
+OPENQRM_POSTENCODE="$OPENQRM_SERVER_BASE_DIR/openqrm/sbin/openqrm-postencode.py"
 OPENQRM_VMWARE_SERVER_VM_TEMPLATE="$OPENQRM_SERVER_BASE_DIR/openqrm/plugins/vmware-server/etc/templates/openqrm-vmware-server-vm"
 # using the vmware-server-tools domain location
 OPENQRM_VM_DIR="/var/lib/vmware/openqrm/"
@@ -98,6 +108,7 @@ case "$VMWARE_SERVER_COMMAND" in
 		if [ "$VMWARE_SERVER_VM_RAM" == "" ]; then
 			vmware-server_usage
 		fi
+		vmware_server_lock aquire
 		echo "Creating VMware vm $VMWARE_SERVER_VM_NAME -> $OPENQRM_VM_DIR/$VMWARE_SERVER_VM_NAME/$VMWARE_SERVER_VM_NAME.vmx"
 		# creating the vmx
 		mkdir -p $OPENQRM_VM_DIR/$VMWARE_SERVER_VM_NAME/
@@ -127,47 +138,62 @@ EOF
 		vmware-cmd -s register $OPENQRM_VM_DIR/$VMWARE_SERVER_VM_NAME/$VMWARE_SERVER_VM_NAME.vmx
 		# start
 		vmware-cmd $OPENQRM_VM_DIR/$VMWARE_SERVER_VM_NAME/$VMWARE_SERVER_VM_NAME.vmx start
+		vmware_server_lock release
 		;;
 	add)
+		vmware_server_lock aquire
 		echo "Adding VMware vm $VMWARE_SERVER_VM_NAME"
 		vmware-cmd -s register $VMWARE_SERVER_VM_NAME
+		vmware_server_lock release
 		;;
 	start)
+		vmware_server_lock aquire
 		echo "Starting VMware vm $VMWARE_SERVER_VM_NAME"
 		vmware-cmd $VMWARE_SERVER_VM_NAME start
+		vmware_server_lock release
 		;;
 	stop)
+		vmware_server_lock aquire
 		echo "Stopping VMware vm $VMWARE_SERVER_VM_NAME"
 		vmware-cmd $VMWARE_SERVER_VM_NAME stop hard
+		vmware_server_lock release
 		;;
 	reboot)
+		vmware_server_lock aquire
 		echo "Rebooting VMware vm $VMWARE_SERVER_VM_NAME"
 		vmware-cmd $VMWARE_SERVER_VM_NAME reset hard
+		vmware_server_lock release
 		;;
 	remove)
+		vmware_server_lock aquire
 		echo "Removing VMware vm $VMWARE_SERVER_VM_NAME"
 		vmware-cmd -s unregister $VMWARE_SERVER_VM_NAME
+		vmware_server_lock release
 		;;
 	delete)
+		vmware_server_lock aquire
 		echo "Deleting VMware vm $VMWARE_SERVER_VM_NAME"
 		rm -rf `dirname $VMWARE_SERVER_VM_NAME`
+		vmware_server_lock release
 		;;
 	list)
 		echo "Listing VMware vms"
 		vmware-cmd -l
 		;;
 	post_vm_list)
+		vmware_server_lock aquire
 		echo "Posting vm list to the openQRM-server"
 		VM_LIST_TMP=$resource_id.vm_list
 		vmware-cmd -l > $VM_LIST_TMP
 		# and the not active vms
 		find $OPENQRM_VM_DIR/../* -name *.vmx | sed -e "s/^/#/g" >> $VM_LIST_TMP
-		if ! wget -q -O /dev/null --http-user=$VMWARE_SERVER_OPENQRM_USERNAME --http-password=$VMWARE_SERVER_OPENQRM_PASSWORD  --post-file=`$OPENQRM_POSTENCODE $VM_LIST_TMP` http://$resource_openqrmserver/openqrm/base/plugins/vmware-server/vmware-server-action.php?vmware_server_command=get_vmware_server; then
-			echo "ERROR: Could not post vm list to the openQRM-server at $resource_openqrmserver!"
-			echo "ERROR: Could not post vm list to the openQRM-server at $resource_openqrmserver!" | logger
+		if ! wget -q -O /dev/null --http-user=$VMWARE_SERVER_OPENQRM_USERNAME --http-password=$VMWARE_SERVER_OPENQRM_PASSWORD  --post-file=`$OPENQRM_POSTENCODE $VM_LIST_TMP` http://$OPENQRM_SERVER_IP/openqrm/base/plugins/vmware-server/vmware-server-action.php?vmware_server_command=get_vmware_server; then
+			echo "ERROR: Could not post vm list to the openQRM-server at $OPENQRM_SERVER_IP!"
+			echo "ERROR: Could not post vm list to the openQRM-server at $OPENQRM_SERVER_IP!" | logger
 		fi
 		rm -f $VM_LIST_TMP
 		rm -f $VM_LIST_TMP.post
+		vmware_server_lock release
 		;;
 	*)
 		vmware-server_usage
diff --git a/trunk/src/plugins/xen/etc/init.d/xen b/trunk/src/plugins/xen/etc/init.d/xen
--- a/trunk/src/plugins/xen/etc/init.d/xen
+++ b/trunk/src/plugins/xen/etc/init.d/xen
@@ -1,11 +1,21 @@
 #!/bin/bash
 # this is the boot-service init script for the Xen-hosts
 
-export `eval cat /proc/cmdline`	
-. /var/openqrm/openqrm-resource.conf
-export OPENQRM_SERVER_BASE_DIR=$resource_basedir
-. $resource_basedir/openqrm/include/openqrm-functions
-
+OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
+. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
+. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/xen/include/openqrm-plugin-xen-functions
+if [ -f $OPENQRM_RESOURCE_PARAMETER_FILE ]; then
+	. $OPENQRM_RESOURCE_PARAMETER_FILE
+	OPENQRM_SERVER_IP=$resource_openqrmserver
+	OPENQRM_INTERFACE=`ifconfig | grep $resource_mac | grep :oq | cut -d':' -f1`
+elif [ -f $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf ]; then
+	. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
+	. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
+	openqrm_server_get_config
+	OPENQRM_SERVER_IP=$OPENQRM_SERVER_IP_ADDRESS
+	OPENQRM_INTERFACE=$OPENQRM_SERVER_INTERFACE
+	resource_kernel=xen
+fi
 # only run on xen hosts
 grep -q "control_d" /proc/xen/capabilities 2>/dev/null || exit 0
 
@@ -14,15 +24,14 @@ function xen_start() {
 	xen_stop 1>/dev/null 2>&1
 
 	# xen interface -> the one not bounded to the rootfs
-	OPENQRM_INTERFACE=`ifconfig | grep $resource_mac | grep :oq | cut -d':' -f1`
 	XEN_INTERFACE=`ifconfig | grep ^eth | grep -v $OPENQRM_INTERFACE | head -n1 | awk {' print $1 '}`
 	if [ -x /etc/xen/scripts/network-bridge ]; then
 		/etc/xen/scripts/network-bridge start vifnum=0 bridge=xenbr0 netdev=$XEN_INTERFACE 
 	fi
 
 	# download the initrd
-	if ! wget -q -O /boot/initrd-$resource_kernel.img http://$resource_openqrmserver/openqrm/boot-service/initrd-$resource_kernel.img; then
-		echo "ERROR: Could not download http://$resource_openqrmserver/openqrm/boot-service/initrd-$resource_kernel.img"
+	if ! wget -q -O /boot/initrd-$resource_kernel.img http://$OPENQRM_SERVER_IP/openqrm/boot-service/initrd-$resource_kernel.img; then
+		echo "ERROR: Could not download http://$OPENQRM_SERVER_IP/openqrm/boot-service/initrd-$resource_kernel.img"
 		return 1
 	fi
 	# adjust Xen-config	and enable migration
diff --git a/trunk/src/plugins/xen/include/openqrm-plugin-xen-functions b/trunk/src/plugins/xen/include/openqrm-plugin-xen-functions
--- a/trunk/src/plugins/xen/include/openqrm-plugin-xen-functions
+++ b/trunk/src/plugins/xen/include/openqrm-plugin-xen-functions
@@ -1,11 +1,18 @@
 #!/bin/bash
 # this is the functions file for the xen-plugin
 
-if [ -f /var/openqrm/openqrm-resource.conf ]; then
-	. /var/openqrm/openqrm-resource.conf
+export LANG=C
+if [ "$OPENQRM_SERVER_BASE_DIR" == "" ]; then
+	echo "ERROR: Please export OPENQRM_SERVER_BASE_DIR before sourcing $0"
+	exit 1
 fi
-VETH="$resource_basedir/openqrm/plugins/xen/bin/vethd"
+
+VETH="$OPENQRM_SERVER_BASE_DIR/openqrm/plugins/xen/bin/vethd"
 XEN_VDEVICE_NAME="xendhcp"
+XEN_LOCK_FILE=/var/run/lvm-storage/lvm-storage-plugin.lock
+XEN_LOCK_DELAY=5
+XEN_LOCK_RETRY=100
+XEN_LOCK_TIMEOUT=500
 
 ################ common xen functions
 
@@ -23,18 +30,18 @@ function xen_lock() {
 	local COMMAND=$1
 	local RET=1
 	
-	if [ ! -d `dirname $LVM_MGMT_LOCK_FILE` ]; then
-		mkdir -p `dirname $LVM_MGMT_LOCK_FILE`
+	if [ ! -d `dirname $XEN_LOCK_FILE` ]; then
+		mkdir -p `dirname $XEN_LOCK_FILE`
 	fi
 	case "$COMMAND" in
 		aquire)
-				lockfile -s $LVM_MGMT_LOCK_DELAY -r $LVM_MGMT_LOCK_RETRY -l $LVM_MGMT_LOCK_TIMEOUT $LVM_MGMT_LOCK_FILE
+				lockfile -s $XEN_LOCK_DELAY -r $XEN_LOCK_RETRY -l $XEN_LOCK_TIMEOUT $XEN_LOCK_FILE
 				RET=$?
 				xen_log xen_lock "Aquired the lock"
 				return $RET
 				;;
 		release)
-				/bin/rm -f $LVM_MGMT_LOCK_FILE
+				/bin/rm -f $XEN_LOCK_FILE
 				RET=$?
 				xen_log xen_lock "Released the lock"
 				return $RET
