aoe is easy too now
git-svn-id: http://openqrm.svn.sourceforge.net/svnroot/openqrm@1050 f7cd0d49-994a-0410-81fc-ecfcdc9cdbae

diff --git a/trunk/src/plugins/aoe-storage/bin/openqrm-aoe-storage b/trunk/src/plugins/aoe-storage/bin/openqrm-aoe-storage
--- a/trunk/src/plugins/aoe-storage/bin/openqrm-aoe-storage
+++ b/trunk/src/plugins/aoe-storage/bin/openqrm-aoe-storage
@@ -28,6 +28,7 @@ function aoe_storage_usage() {
 	echo "             [-m size in MB]"
 	echo "             [-s image-snapshot-name]"
 	echo "        $0 post_luns <-u username> <-p password>"
+	echo "        $0 post_identifier <-u username> <-p password>"
 	exit 1
 }
 
@@ -89,7 +90,7 @@ if [ "$AOE_COMMAND" == "" ]; then
 	aoe_storage_usage
 fi
 
-if [ "$AOE_COMMAND" == "post_luns" ]; then
+if [ "$AOE_COMMAND" == "post_luns" ] || [ "$AOE_COMMAND" == "post_identifier" ]; then
 	if [ "$AOE_OPENQRM_USERNAME" == "" ]; then
 		aoe_storage_usage
 	fi
@@ -169,8 +170,33 @@ case "$AOE_COMMAND" in
 	post_luns)
 		echo "Posting current aoe-luns to the openQRM-server"
 		STORAGE_STATUS_TMP=$resource_id.aoe.stat
-		cat $VBLADECONF > $STORAGE_STATUS_TMP
+		cat $VBLADECONF | grep -v '#' | sed '/^$/d' > $STORAGE_STATUS_TMP
 		if ! wget -q -O /dev/null --http-user=$AOE_OPENQRM_USERNAME --http-password=$AOE_OPENQRM_PASSWORD  --post-file=`$OPENQRM_POSTENCODE $STORAGE_STATUS_TMP` http://$OPENQRM_SERVER_IP/openqrm/base/plugins/aoe-storage/aoe-storage-action.php?aoe_storage_command=get_storage; then
+			echo "ERROR: Could not post the aoe-export status to the openQRM-server at $resource_openqrmserver!"
+			echo "ERROR: Could not post the aoe-export status to the openQRM-server at $resource_openqrmserver!" | logger
+		fi
+		rm -f $STORAGE_STATUS_TMP
+		rm -f $STORAGE_STATUS_TMP.post
+		;;
+	post_identifier)
+		echo "Posting current aoe-identifier to the openQRM-server"
+		STORAGE_STATUS_TMP=$resource_id.aoe.ident
+		> $STORAGE_STATUS_TMP
+		OLD_IFS=$IFS
+IFS='
+'
+		for SHELF_STR in `cat $VBLADECONF | grep -v '#' | sed '/^$/d'`; do
+			INTERFACE=`echo $SHELF_STR | awk {'print $1	'}`
+			V_SHELF=`echo $SHELF_STR | awk {' print $2 '}`
+			V_SLOT=`echo $SHELF_STR | awk {' print $3 '}`
+			V_IMAGE=`echo $SHELF_STR | awk {' print $4 '}`
+			V_ALLOWED_MAC=`echo $SHELF_STR | awk {' print $5 '}`
+
+			echo "$V_IMAGE,/dev/etherd/e$V_SHELF.$V_SLOT"
+			echo "$V_IMAGE,/dev/etherd/e$V_SHELF.$V_SLOT" >> $STORAGE_STATUS_TMP
+		done
+		IFS=$OLD_IFS
+		if ! wget -q -O /dev/null --http-user=$AOE_OPENQRM_USERNAME --http-password=$AOE_OPENQRM_PASSWORD  --post-file=`$OPENQRM_POSTENCODE $STORAGE_STATUS_TMP` http://$OPENQRM_SERVER_IP/openqrm/base/plugins/aoe-storage/aoe-storage-action.php?aoe_storage_command=get_ident; then
 			echo "ERROR: Could not post the aoe-export status to the openQRM-server at $resource_openqrmserver!"
 			echo "ERROR: Could not post the aoe-export status to the openQRM-server at $resource_openqrmserver!" | logger
 		fi
