improved boot-image creation
git-svn-id: http://openqrm.svn.sourceforge.net/svnroot/openqrm@460 f7cd0d49-994a-0410-81fc-ecfcdc9cdbae

diff --git a/trunk/src/bin/openqrm b/trunk/src/bin/openqrm
--- a/trunk/src/bin/openqrm
+++ b/trunk/src/bin/openqrm
@@ -12,22 +12,119 @@ fi
 function openqrm_usage() {
 	echo "Usage:"
 	echo "`basename $0` help			- This help screen"
-	echo "`basename $0` bootimage		- Managing boot-images"
+	echo "- Managing boot-images -"
+	echo "`basename $0` bootimage add -n <name> -v <version> -u <username> -p <password> [-l <location> -i <initramfs/ext2>]"
+	echo "`basename $0` bootimage remove -n <name> -u <username> -p <password>"
 }
 
 
-BOOT_IMAGE_NAME=$2
-BOOT_IMAGE_VERSION=$3
-BOOT_IMAGE_LOCATION=$4
-BOOT_IMAGE_INITRD_TYPE=$5
 
-
+# main
 case "$1" in
-
 	bootimage)
-		openqrm_server_create_kernel $BOOT_IMAGE_NAME $BOOT_IMAGE_VERSION $BOOT_IMAGE_LOCATION $BOOT_IMAGE_INITRD_TYPE
+		shift
+		if [ $# == 0 ]; then
+			openqrm_usage
+			exit 0
+		fi
+
+		case "$1" in
+			add)
+				shift
+				if [ $# == 0 ]; then
+					openqrm_usage
+					exit 0
+				fi
+				while [ $# -ne 0 ]; do
+					case "$1" in
+						-n)
+							BOOT_IMAGE_NAME=$2
+							shift
+							;;
+						-v)
+							BOOT_IMAGE_VERSION=$2
+							shift
+							;;			
+						-l)
+							BOOT_IMAGE_LOCATION=$2
+							shift
+							;;
+						-i)
+							BOOT_IMAGE_INITRD_TYPE=$2
+							shift
+							;;
+						-u)
+							OPENQRM_USERNAME=$2
+							shift
+							;;
+						-p)
+							OPENQRM_PASSWORD=$2
+							shift
+							;;
+					esac
+					shift
+				done
+				if [ "$BOOT_IMAGE_NAME" == "" ] || [ "$BOOT_IMAGE_VERSION" == "" ] || [ "$OPENQRM_USERNAME" == "" ] || [ "$OPENQRM_PASSWORD" == "" ]; then
+					openqrm_usage
+					exit 1
+				fi
+				if [ "$BOOT_IMAGE_LOCATION" == "" ]; then
+					BOOT_IMAGE_LOCATION=/
+				fi
+				openqrm_server_create_kernel $BOOT_IMAGE_NAME $BOOT_IMAGE_VERSION $BOOT_IMAGE_LOCATION $BOOT_IMAGE_INITRD_TYPE
+				if ! openqrm_server_manage_kernel add $OPENQRM_USERNAME $OPENQRM_PASSWORD $BOOT_IMAGE_NAME $BOOT_IMAGE_VERSION; then
+					echo "WARNING: Could not add the kernel to the openQRM-server!"
+					exit -1
+				fi
+				;;
+
+			remove)
+				shift
+				if [ $# == 0 ]; then
+					openqrm_usage
+					exit 0
+				fi
+				while [ $# -ne 0 ]; do
+					case "$1" in
+						-n)
+							BOOT_IMAGE_NAME=$2
+							shift
+							;;
+						-u)
+							OPENQRM_USERNAME=$2
+							shift
+							;;
+						-p)
+							OPENQRM_PASSWORD=$2
+							shift
+							;;
+					esac
+					shift
+				done
+				if [ "$BOOT_IMAGE_NAME" == "" ] || [ "$OPENQRM_USERNAME" == "" ] || [ "$OPENQRM_PASSWORD" == "" ]; then
+					openqrm_usage
+					exit 1
+				fi
+				rm -f $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/boot/vmlinuz-$BOOT_IMAGE_NAME
+				rm -f $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/boot/System.map-$BOOT_IMAGE_NAME
+				rm -f $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/boot/modules-$BOOT_IMAGE_NAME.tgz
+				rm -f $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/boot/initrd-$BOOT_IMAGE_NAME.img
+				if ! openqrm_server_manage_kernel remove $OPENQRM_USERNAME $OPENQRM_PASSWORD $BOOT_IMAGE_NAME $BOOT_IMAGE_VERSION; then
+					echo "WARNING: Could not remove the kernel to the openQRM-server!"
+					exit -1
+				fi
+				;;
+
+		esac
 		;;
+
+
+
+
 	*)
 		openqrm_usage
 		;;
+
 esac
+
+
diff --git a/trunk/src/include/openqrm-server-functions b/trunk/src/include/openqrm-server-functions
--- a/trunk/src/include/openqrm-server-functions
+++ b/trunk/src/include/openqrm-server-functions
@@ -138,20 +138,35 @@ function openqrm_server_create_kernel() {
 
 
 
-# function to add a kernel to the openQRM-server db
-# param 1	: kernel name
-# param 2	: kernel-version
-function openqrm_server_add_kernel() {
-	OPENQRM_USER=$1
-	OPENQRM_USER_PASSWORD=$2
-	OPENQRM_SERVER_KERNEL_NAME=$3
-	OPENQRM_SERVER_KERNEL_VERSION=$4
-	echo "openQRM-server: Adding kernel $OPENQRM_SERVER_KERNEL_NAME version $OPENQRM_SERVER_KERNEL_VERSION" | logger
-	if ! wget -O /dev/null -q --http-user=$OPENQRM_USER --http-password=$OPENQRM_USER_PASSWORD "http://localhost/openqrm/base/server/kernel/kernel-action.php?kernel_command=new_kernel&kernel_name=$OPENQRM_SERVER_KERNEL_NAME&kernel_version=$OPENQRM_SERVER_KERNEL_VERSION"; then
-		echo "ERROR: Could not add kernel $OPENQRM_SERVER_KERNEL_NAME to the openQRM-server!" | logger
-		return 1
-	fi
-	return 0
+# function to add/remove a kernel to the openQRM-server db
+# param 1	: add/remove
+# param 2	: user
+# param 3	: password
+# param 4	: kernel name
+# param 5	: kernel-version
+function openqrm_server_manage_kernel() {
+	OPENQRM_USER=$2
+	OPENQRM_USER_PASSWORD=$3
+	OPENQRM_SERVER_KERNEL_NAME=$4
+	OPENQRM_SERVER_KERNEL_VERSION=$5
+	case "$1" in
+		add)
+			echo "openQRM-server: Adding kernel $OPENQRM_SERVER_KERNEL_NAME version $OPENQRM_SERVER_KERNEL_VERSION" | logger
+			if ! wget -O /dev/null -q --http-user=$OPENQRM_USER --http-password=$OPENQRM_USER_PASSWORD "http://localhost/openqrm/base/server/kernel/kernel-action.php?kernel_command=new_kernel&kernel_name=$OPENQRM_SERVER_KERNEL_NAME&kernel_version=$OPENQRM_SERVER_KERNEL_VERSION"; then
+				echo "ERROR: Could not add kernel $OPENQRM_SERVER_KERNEL_NAME to the openQRM-server!" | logger
+				return 1
+			fi
+			return 0
+			;;
+		remove)
+			echo "openQRM-server: Removing kernel $OPENQRM_SERVER_KERNEL_NAME" | logger
+			if ! wget -O /dev/null -q --http-user=$OPENQRM_USER --http-password=$OPENQRM_USER_PASSWORD "http://localhost/openqrm/base/server/kernel/kernel-action.php?kernel_command=remove_by_name&kernel_name=$OPENQRM_SERVER_KERNEL_NAME"; then
+				echo "ERROR: Could not remove kernel $OPENQRM_SERVER_KERNEL_NAME to the openQRM-server!" | logger
+				return 1
+			fi
+			return 0
+			;;
+	esac
 }
 
 
