set of updates to enhance debian/ubuntu packages
git-svn-id: http://openqrm.svn.sourceforge.net/svnroot/openqrm@1525 f7cd0d49-994a-0410-81fc-ecfcdc9cdbae

diff --git a/trunk/src/bin/openqrm b/trunk/src/bin/openqrm
--- a/trunk/src/bin/openqrm
+++ b/trunk/src/bin/openqrm
@@ -9,6 +9,14 @@ fi
 . $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
 
 
+# let only root run this script
+WHOAMI=`whoami`
+if [ "$WHOAMI" != "root" ]; then
+	echo "ERROR: Please run this script as root!"
+	exit 6
+fi
+
+
 function openqrm_usage() {
 	echo
 	echo "Usage:"
