added transform
git-svn-id: http://openqrm.svn.sourceforge.net/svnroot/openqrm@995 f7cd0d49-994a-0410-81fc-ecfcdc9cdbae

diff --git a/trunk/src/plugins/lvm-storage/include/openqrm-plugin-lvm-storage-functions b/trunk/src/plugins/lvm-storage/include/openqrm-plugin-lvm-storage-functions
--- a/trunk/src/plugins/lvm-storage/include/openqrm-plugin-lvm-storage-functions
+++ b/trunk/src/plugins/lvm-storage/include/openqrm-plugin-lvm-storage-functions
@@ -140,6 +140,23 @@ function manage_nfs() {
 			done
 			rmdir /$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME
 			;;
+		transform)
+			# here please check before if the devices was already added to the iscsi-conf
+			if ! `mount /dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME /$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME`; then
+				lvm_storage_log lvm-storage-functions "ERROR: Could not mount /dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME at /$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME"
+				manage_fstab remove
+				lvm_storage_lock release
+				return 1
+			fi
+			echo "/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME	*(rw,insecure,no_root_squash,async)" >> /etc/exports
+			if [ -x /etc/init.d/nfs ]; then
+				/etc/init.d/nfs reload
+			elif [ -x /etc/init.d/nfs-kernel-server ]; then
+				/etc/init.d/nfs-kernel-server reload
+			else
+				echo "WARNING: Could not find nfs-server init script !"
+			fi
+			;;
 	esac
 }
 
@@ -162,6 +179,13 @@ function manage_iscsi() {
 		remove)
 			cat $IETDCONF | sed -e "s#.*$LVM_STORAGE_SERVER_VOLUME_GROUP-$LVM_IMAGE_NAME.*##g" > /tmp/ietd.conf.tmp-update
 			/bin/mv -f /tmp/ietd.conf.tmp-update $IETDCONF
+			nohup /etc/init.d/iscsi-target restart
+			;;
+		transform)
+			# here please check before if the devices was already added to the iscsi-conf
+					IMAGE_LUN=`cat $IETDCONF | grep Lun | awk {' print $2 '} | sort -n -r | head -n 1`
+			IMAGE_LUN=$(( IMAGE_LUN + 1 ))
+			echo "	Lun $IMAGE_LUN Path=/dev/mapper/$LVM_STORAGE_SERVER_VOLUME_GROUP-$LVM_IMAGE_NAME,Type=fileio" >> $IETDCONF
 			nohup /etc/init.d/iscsi-target restart
 			;;
 	esac
@@ -219,6 +243,22 @@ function manage_vblade() {
 			sync			
 			cat $VBLADECONF | sed -e "s#.*$LVM_STORAGE_SERVER_VOLUME_GROUP-$LVM_IMAGE_NAME.*##g" > /tmp/vblade.conf.tmp-update
 			/bin/mv -f /tmp/vblade.conf.tmp-update $VBLADECONF
+			;;
+		transform)
+			# currently just one static shelf !
+			AOE_SHELF=1
+			# slots are dynamic
+			AOE_SLOT=`cat $VBLADECONF | grep disk | awk {' print $3 '} | sort -n -r | head -n 1`
+			AOE_SLOT=$(( AOE_SLOT + 1 ))
+			if [ -f $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf ]; then
+				. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
+				AOE_INTERFACE=$OPENQRM_SERVER_INTERFACE
+			else
+				AOE_INTERFACE=`ifconfig | grep $resource_mac | awk {' print $1 '} | tail -1`
+			fi
+			echo "disk $AOE_SHELF $AOE_SLOT $AOE_INTERFACE $LVM_DISK" >> $VBLADECONF
+			# start vbladed
+			vbladed $AOE_SHELF $AOE_SLOT $AOE_INTERFACE $LVM_DISK
 			;;
 	esac
 }
