generic deployment for linux-vserver
git-svn-id: http://openqrm.svn.sourceforge.net/svnroot/openqrm@389 f7cd0d49-994a-0410-81fc-ecfcdc9cdbae

diff --git a/trunk/src/plugins/linux-vserver/etc/init.d/linux-vserver b/trunk/src/plugins/linux-vserver/etc/init.d/linux-vserver
--- a/trunk/src/plugins/linux-vserver/etc/init.d/linux-vserver
+++ b/trunk/src/plugins/linux-vserver/etc/init.d/linux-vserver
@@ -17,6 +17,14 @@ function linux_vserver_start() {
 		echo "ERROR: Could not download http://$resource_openqrmserver/openqrm/boot-service/openqrm-initrd-default.tgz"
 		return 1
 	fi
+	# start all vifs
+	for VIF in `cat $OPENQRM_VIF_CONFIG |  awk {' print $2 '}`; do
+		if ! linux_vserver_manage_vif start $LINUX_VSERVER_VM_NAME; then
+			echo "ERROR: Could not start vif for Linux-VServer vm $LINUX_VSERVER_VM_NAME"
+		else
+			echo "NOTICE: Starting vif for Linux-VServer vm $LINUX_VSERVER_VM_NAME"
+		fi
+	done
 }
 
 
