added a xen vm configuration editor
git-svn-id: http://openqrm.svn.sourceforge.net/svnroot/openqrm@1336 f7cd0d49-994a-0410-81fc-ecfcdc9cdbae

diff --git a/trunk/src/plugins/xen/bin/openqrm-xen b/trunk/src/plugins/xen/bin/openqrm-xen
--- a/trunk/src/plugins/xen/bin/openqrm-xen
+++ b/trunk/src/plugins/xen/bin/openqrm-xen
@@ -56,6 +56,13 @@ function xen_usage() {
 	echo "Usage : $0 create <-n vm-name> <-m mac-address> <-i ip-address> <-r memory> [-d disk-size -s swap-size]"
 	echo "Usage : $0 migrate <-n vm-name> <-i ip-address> <-t live/regular>"
 	echo "        $0 post_vm_list <-u username> <-p password>"
+	echo "        $0 post_vm_config <-n vm-name> <-u username> <-p password>"
+	echo "        $0 update_vm_ram <-r memory> <-n vm-name>"
+	echo "        $0 update_vm_cpu <-c cpu-number> <-n vm-name>"
+	echo "        $0 add_vm_nic <-x nic-number> <-m mac-address> <-n vm-name>"
+	echo "        $0 remove_vm_nic <-x nic-number> <-n vm-name>"
+	echo "        $0 add_vm_disk <-x disk-number> <-d disk-size> <-n vm-name>"
+	echo "        $0 remove_vm_disk <-x disk-number> <-n vm-name>"
 	exit 1
 }
 
@@ -65,28 +72,36 @@ function xen_generate_vm_config() {
     VM_NAME=$1
     VM_BASE_DIR=$OPENQRM_VM_DIR/$VM_NAME
     # source the components config
-    vm_kernel=`cat $VM_BASE_DIR/kernel`
-    vm_builder=`cat $VM_BASE_DIR/builder`
-    vm_memory=`cat $VM_BASE_DIR/memory`
-    vm_device_model=`cat $VM_BASE_DIR/device_model`
-    vm_name=`cat $VM_BASE_DIR/name`
-    vm_mac1=`cat $VM_BASE_DIR/mac1`
-    vm_bridge1=`cat $VM_BASE_DIR/bridge1`
-    vm_mac2=`cat $VM_BASE_DIR/mac2`
-    vm_bridge2=`cat $VM_BASE_DIR/bridge2`
-    vm_mac3=`cat $VM_BASE_DIR/mac3`
-    vm_bridge3=`cat $VM_BASE_DIR/bridge3`
-    vm_mac4=`cat $VM_BASE_DIR/mac4`
-    vm_bridge4=`cat $VM_BASE_DIR/bridge4`
-    vm_boot=`cat $VM_BASE_DIR/boot`
-    vm_root=`cat $VM_BASE_DIR/root`
-    vm_swap=`cat $VM_BASE_DIR/swap`
-    vm_disk1=`cat $VM_BASE_DIR/disk1`
-    vm_vnc=`cat $VM_BASE_DIR/vnc`
-    vm_vncviewer=`cat $VM_BASE_DIR/vncviewer`
-    vm_vnc_display=`cat $VM_BASE_DIR/vncdisplay`
-    vm_sdl=`cat $VM_BASE_DIR/sdl`
-
+    vm_kernel=`cat $VM_BASE_DIR/kernel 2>/dev/null`
+    vm_builder=`cat $VM_BASE_DIR/builder 2>/dev/null`
+    vm_memory=`cat $VM_BASE_DIR/memory 2>/dev/null`
+    vm_vcpu=`cat $VM_BASE_DIR/vcpu 2>/dev/null`
+    vm_device_model=`cat $VM_BASE_DIR/device_model 2>/dev/null`
+    vm_name=`cat $VM_BASE_DIR/name 2>/dev/null`
+    vm_mac1=`cat $VM_BASE_DIR/mac1 2>/dev/null`
+    vm_bridge1=`cat $VM_BASE_DIR/bridge1 2>/dev/null`
+    vm_mac2=`cat $VM_BASE_DIR/mac2 2>/dev/null`
+    vm_bridge2=`cat $VM_BASE_DIR/bridge2 2>/dev/null`
+    vm_mac3=`cat $VM_BASE_DIR/mac3 2>/dev/null`
+    vm_bridge3=`cat $VM_BASE_DIR/bridge3 2>/dev/null`
+    vm_mac4=`cat $VM_BASE_DIR/mac4 2>/dev/null`
+    vm_bridge4=`cat $VM_BASE_DIR/bridge4 2>/dev/null`
+    vm_boot=`cat $VM_BASE_DIR/boot 2>/dev/null`
+    vm_root=`cat $VM_BASE_DIR/root 2>/dev/null`
+    vm_swap=`cat $VM_BASE_DIR/swap 2>/dev/null`
+    vm_swapsize=`cat $VM_BASE_DIR/swapsize 2>/dev/null`
+    vm_disk1=`cat $VM_BASE_DIR/disk1 2>/dev/null`
+    vm_disksize1=`cat $VM_BASE_DIR/disksize1 2>/dev/null`
+    vm_disk2=`cat $VM_BASE_DIR/disk2 2>/dev/null`
+    vm_disksize2=`cat $VM_BASE_DIR/disksize2 2>/dev/null`
+    vm_disk3=`cat $VM_BASE_DIR/disk3 2>/dev/null`
+    vm_disksize3=`cat $VM_BASE_DIR/disksize3 2>/dev/null`
+    vm_disk4=`cat $VM_BASE_DIR/disk4 2>/dev/null`
+    vm_disksize4=`cat $VM_BASE_DIR/disksize4 2>/dev/null`
+    vm_vnc=`cat $VM_BASE_DIR/vnc 2>/dev/null`
+    vm_vncviewer=`cat $VM_BASE_DIR/vncviewer 2>/dev/null`
+    vm_vnc_display=`cat $VM_BASE_DIR/vncdisplay 2>/dev/null`
+    vm_sdl=`cat $VM_BASE_DIR/sdl 2>/dev/null`
 
     > $OPENQRM_PLUGIN_XEN_VM_CONFIG_DIR/$VM_NAME.cfg
     cat >> $OPENQRM_PLUGIN_XEN_VM_CONFIG_DIR/$VM_NAME.cfg << EOF
@@ -95,14 +110,31 @@ builder = "$vm_builder"
 memory = "$vm_memory"
 device_model="$vm_device_model"
 name = "$vm_name"
-vif = ["mac=$vm_mac1, type=ioemu, bridge=$vm_bridge1"]
 boot="$vm_boot"
+vcpu="$vm_vcpu"
 vnc=$vm_vnc
 vncviewer=$vm_vncviewer
 vncdisplay=$vm_vnc_display
 sdl=$vm_sdl
 EOF
 
+
+    # add nics
+    VM_NIC_CONF="$VM_DISK_CONF \"mac=$vm_mac1, type=ioemu, bridge=$vm_bridge1\","
+    if [ "$vm_mac2" != "" ]; then
+        VM_NIC_CONF="$VM_NIC_CONF \"mac=$vm_mac2, type=ioemu, bridge=$vm_bridge2\","
+    fi
+    if [ "$vm_mac3" != "" ]; then
+        VM_NIC_CONF="$VM_NIC_CONF \"mac=$vm_mac3, type=ioemu, bridge=$vm_bridge3\","
+    fi
+    if [ "$vm_mac4" != "" ]; then
+        VM_NIC_CONF="$VM_NIC_CONF \"mac=$vm_mac4, type=ioemu, bridge=$vm_bridge4\","
+    fi
+    cat >> $OPENQRM_PLUGIN_XEN_VM_CONFIG_DIR/$VM_NAME.cfg << EOF
+vif = [ $VM_NIC_CONF ]
+EOF
+
+    # add disk + swap
     ADD_DISK=false
     if [ "$vm_disk1" != "" ]; then
         VM_DISK_CONF="$VM_DISK_CONF \"$vm_disk1\","
@@ -110,6 +142,18 @@ EOF
         cat >> $OPENQRM_PLUGIN_XEN_VM_CONFIG_DIR/$VM_NAME.cfg << EOF
 root = "$vm_root"
 EOF
+    fi
+    if [ "$vm_disk2" != "" ]; then
+        VM_DISK_CONF="$VM_DISK_CONF \"$vm_disk2\","
+        ADD_DISK=true
+    fi
+    if [ "$vm_disk3" != "" ]; then
+        VM_DISK_CONF="$VM_DISK_CONF \"$vm_disk3\","
+        ADD_DISK=true
+    fi
+    if [ "$vm_disk4" != "" ]; then
+        VM_DISK_CONF="$VM_DISK_CONF \"$vm_disk4\","
+        ADD_DISK=true
     fi
     if [ "$vm_swap" != "" ]; then
         VM_DISK_CONF="$VM_DISK_CONF \"$vm_swap\","
@@ -148,6 +192,10 @@ while [ $# -ne 0 ]; do
 			XEN_VM_RAM=$2
 			shift
 			;;
+		-c)
+			XEN_VM_CPU=$2
+			shift
+			;;
 		-d)
 			XEN_VM_DISK=$2
 			shift
@@ -166,6 +214,10 @@ while [ $# -ne 0 ]; do
 			;;
 		-p)
 			XEN_OPENQRM_PASSWORD=$2
+			shift
+			;;
+		-x)
+			XEN_VM_COMPONENT_NUMBER=$2
 			shift
 			;;
 		*)
@@ -249,6 +301,8 @@ case "$XEN_COMMAND" in
         echo "1" > $XEN_VM_BASE_DIR/vnc
         echo "1" > $XEN_VM_BASE_DIR/vncviewer
         echo "0" > $XEN_VM_BASE_DIR/sdl
+        # one cpu by default
+        echo "1" > $XEN_VM_BASE_DIR/vcpu
 
         # find the next free vncdisplay
         for VNCD in `find $OPENQRM_VM_DIR/* -name vncdisplay 2>/dev/null`; do
@@ -269,13 +323,15 @@ case "$XEN_COMMAND" in
 			mkfs.ext3 -F $OPENQRM_VM_DIR/$XEN_VM_NAME/disk1.img
             echo "/dev/hda1 ro" > $XEN_VM_BASE_DIR/root
             echo "file:$OPENQRM_VM_DIR/$XEN_VM_NAME/disk1.img,ioemu:hda1,w" > $XEN_VM_BASE_DIR/disk1
+            echo "$XEN_VM_DISK" > $XEN_VM_BASE_DIR/disksize1
 		fi
 		# swap
 		if [ "$XEN_VM_SWAP" != "" ]; then
 			echo "-> Creating swap"
 			dd if=/dev/zero of=$OPENQRM_VM_DIR/$XEN_VM_NAME/swap.img bs=1M seek=$XEN_VM_SWAP count=1
 			mkswap -f $OPENQRM_VM_DIR/$XEN_VM_NAME/swap.img
-            echo "file:$OPENQRM_VM_DIR/$XEN_VM_NAME/swap.img,hda2,w" > $XEN_VM_BASE_DIR/swap
+            echo "file:$OPENQRM_VM_DIR/$XEN_VM_NAME/swap.img,hdb1,w" > $XEN_VM_BASE_DIR/swap
+            echo "$XEN_VM_SWAP" > $XEN_VM_BASE_DIR/swapsize
 		fi
 
 		# creating the cfg
@@ -471,6 +527,174 @@ case "$XEN_COMMAND" in
 		rm -f $VM_LIST_TMP
 		rm -f $VM_LIST_TMP.post
 		;;
+
+	post_vm_config)
+		if [ "$XEN_VM_NAME" == "" ]; then
+			xen_usage
+		fi
+		xen_lock aquire
+		echo "Posting vm config for $XEN_VM_NAME to the openQRM-server"
+		VM_CONFIG_TMP=$resource_id.$XEN_VM_NAME.vm_config
+        VM_BASE_DIR=$OPENQRM_VM_DIR/$XEN_VM_NAME
+        vm_memory=`cat $VM_BASE_DIR/memory 2>/dev/null`
+        vm_cpu=`cat $VM_BASE_DIR/vcpu 2>/dev/null`
+        vm_mac1=`cat $VM_BASE_DIR/mac1 2>/dev/null`
+        vm_bridge1=`cat $VM_BASE_DIR/bridge1 2>/dev/null`
+        vm_mac2=`cat $VM_BASE_DIR/mac2 2>/dev/null`
+        vm_bridge2=`cat $VM_BASE_DIR/bridge2 2>/dev/null`
+        vm_mac3=`cat $VM_BASE_DIR/mac3 2>/dev/null`
+        vm_bridge3=`cat $VM_BASE_DIR/bridge3 2>/dev/null`
+        vm_mac4=`cat $VM_BASE_DIR/mac4 2>/dev/null`
+        vm_bridge4=`cat $VM_BASE_DIR/bridge4 2>/dev/null`
+        vm_swap=`cat $VM_BASE_DIR/swap 2>/dev/null`
+        vm_swapsize=`cat $VM_BASE_DIR/swapsize 2>/dev/null`
+        vm_disk1=`cat $VM_BASE_DIR/disk1 2>/dev/null`
+        vm_disksize1=`cat $VM_BASE_DIR/disksize1 2>/dev/null`
+        vm_disk2=`cat $VM_BASE_DIR/disk2 2>/dev/null`
+        vm_disksize2=`cat $VM_BASE_DIR/disksize2 2>/dev/null`
+        vm_disk3=`cat $VM_BASE_DIR/disk3 2>/dev/null`
+        vm_disksize3=`cat $VM_BASE_DIR/disksize3 2>/dev/null`
+        vm_disk4=`cat $VM_BASE_DIR/disk4 2>/dev/null`
+        vm_disksize4=`cat $VM_BASE_DIR/disksize4 2>/dev/null`
+        vm_vnc_display=`cat $VM_BASE_DIR/vncdisplay`
+		echo "OPENQRM_XEN_VM_RAM=\"$vm_memory\"" > $VM_CONFIG_TMP
+		echo "OPENQRM_XEN_VM_CPU=\"$vm_cpu\"" >> $VM_CONFIG_TMP
+		echo "OPENQRM_XEN_VM_NET_1=\"$vm_bridge1\"" >> $VM_CONFIG_TMP
+		echo "OPENQRM_XEN_VM_MAC_1=\"$vm_mac1\"" >> $VM_CONFIG_TMP
+		echo "OPENQRM_XEN_VM_NET_2=\"$vm_bridge2\"" >> $VM_CONFIG_TMP
+		echo "OPENQRM_XEN_VM_MAC_2=\"$vm_mac2\"" >> $VM_CONFIG_TMP
+		echo "OPENQRM_XEN_VM_NET_3=\"$vm_bridge3\"" >> $VM_CONFIG_TMP
+		echo "OPENQRM_XEN_VM_MAC_3=\"$vm_mac3\"" >> $VM_CONFIG_TMP
+		echo "OPENQRM_XEN_VM_NET_4=\"$vm_bridge4\"" >> $VM_CONFIG_TMP
+		echo "OPENQRM_XEN_VM_MAC_4=\"$vm_mac4\"" >> $VM_CONFIG_TMP
+		echo "OPENQRM_XEN_VM_SWAP=\"$vm_swap\"" >> $VM_CONFIG_TMP
+		echo "OPENQRM_XEN_VM_SWAPSIZE=\"$vm_swapsize\"" >> $VM_CONFIG_TMP
+		echo "OPENQRM_XEN_VM_DISK_1=\"$vm_disk1\"" >> $VM_CONFIG_TMP
+		echo "OPENQRM_XEN_VM_DISK_SIZE_1=\"$vm_disksize1\"" >> $VM_CONFIG_TMP
+		echo "OPENQRM_XEN_VM_DISK_2=\"$vm_disk2\"" >> $VM_CONFIG_TMP
+		echo "OPENQRM_XEN_VM_DISK_SIZE_2=\"$vm_disksize2\"" >> $VM_CONFIG_TMP
+		echo "OPENQRM_XEN_VM_DISK_3=\"$vm_disk3\"" >> $VM_CONFIG_TMP
+		echo "OPENQRM_XEN_VM_DISK_SIZE_3=\"$vm_disksize3\"" >> $VM_CONFIG_TMP
+		echo "OPENQRM_XEN_VM_DISK_4=\"$vm_disk4\"" >> $VM_CONFIG_TMP
+		echo "OPENQRM_XEN_VM_DISK_SIZE_4=\"$vm_disksize4\"" >> $VM_CONFIG_TMP
+		echo "OPENQRM_XEN_VM_VNC=\"$vm_vnc_display\"" >> $VM_CONFIG_TMP
+		if ! wget -q -O /dev/null --http-user=$XEN_OPENQRM_USERNAME --http-password=$XEN_OPENQRM_PASSWORD  --post-file=`$OPENQRM_POSTENCODE $VM_CONFIG_TMP` http://$OPENQRM_SERVER_IP/openqrm/base/plugins/xen/xen-action.php?xen_command=get_xen_config; then
+			echo "ERROR: Could not post vm config to the openQRM-server at $OPENQRM_SERVER_IP!"
+			echo "ERROR: Could not post vm config to the openQRM-server at $OPENQRM_SERVER_IP!" | logger
+		fi
+		rm -f $VM_CONFIG_TMP
+		rm -f $VM_CONFIG_TMP.post
+		xen_lock release
+		;;
+
+
+	update_vm_ram)
+		if [ "$XEN_VM_NAME" == "" ]; then
+			xen_usage
+		fi
+		if [ "$XEN_VM_RAM" == "" ]; then
+			xen_usage
+		fi
+		xen_lock aquire
+		echo "Updating XEN vm $XEN_VM_NAME with $XEN_VM_RAM Memory"
+        VM_BASE_DIR=$OPENQRM_VM_DIR/$XEN_VM_NAME
+        echo "$XEN_VM_RAM" > $VM_BASE_DIR/memory
+		# creating the cfg
+        xen_generate_vm_config $XEN_VM_NAME
+		xen_lock release
+		;;
+
+	update_vm_cpu)
+		if [ "$XEN_VM_NAME" == "" ]; then
+			xen_usage
+		fi
+		if [ "$XEN_VM_CPU" == "" ]; then
+			xen_usage
+		fi
+		xen_lock aquire
+		echo "Updating XEN vm $XEN_VM_NAME with $XEN_VM_CPU CPUs"
+        VM_BASE_DIR=$OPENQRM_VM_DIR/$XEN_VM_NAME
+        echo "$XEN_VM_CPU" > $VM_BASE_DIR/vcpu
+		# creating the cfg
+        xen_generate_vm_config $XEN_VM_NAME
+		xen_lock release
+		;;
+
+
+	add_vm_nic)
+		if [ "$XEN_VM_NAME" == "" ]; then
+			xen_usage
+		fi
+		if [ "$XEN_VM_MAC" == "" ]; then
+			xen_usage
+		fi
+		if [ "$XEN_VM_COMPONENT_NUMBER" == "" ]; then
+			xen_usage
+		fi
+		xen_lock aquire
+		echo "Adding nic $XEN_VM_COMPONENT_NUMBER mac-address $XEN_VM_MAC to XEN vm $XEN_VM_NAME"
+        VM_BASE_DIR=$OPENQRM_VM_DIR/$XEN_VM_NAME
+        echo "$XEN_VM_MAC" > $VM_BASE_DIR/mac$XEN_VM_COMPONENT_NUMBER
+		# creating the cfg
+        xen_generate_vm_config $XEN_VM_NAME
+		xen_lock release
+		;;
+	remove_vm_nic)
+		if [ "$XEN_VM_NAME" == "" ]; then
+			xen_usage
+		fi
+		if [ "$XEN_VM_COMPONENT_NUMBER" == "" ]; then
+			xen_usage
+		fi
+		xen_lock aquire
+		echo "Removing nic $XEN_VM_COMPONENT_NUMBER from XEN vm $XEN_VM_NAME"
+        VM_BASE_DIR=$OPENQRM_VM_DIR/$XEN_VM_NAME
+        > $VM_BASE_DIR/mac$XEN_VM_COMPONENT_NUMBER
+		# creating the cfg
+        xen_generate_vm_config $XEN_VM_NAME
+		xen_lock release
+		;;
+
+
+	add_vm_disk)
+		if [ "$XEN_VM_NAME" == "" ]; then
+			xen_usage
+		fi
+		if [ "$XEN_VM_DISK" == "" ]; then
+			xen_usage
+		fi
+		if [ "$XEN_VM_COMPONENT_NUMBER" == "" ]; then
+			xen_usage
+		fi
+		xen_lock aquire
+		echo "Adding disk $XEN_VM_COMPONENT_NUMBER size $XEN_VM_DISK to XEN vm $XEN_VM_NAME"
+        VM_BASE_DIR=$OPENQRM_VM_DIR/$XEN_VM_NAME
+        dd if=/dev/zero of=$OPENQRM_VM_DIR/$XEN_VM_NAME/disk$XEN_VM_COMPONENT_NUMBER.img bs=1M seek=$XEN_VM_DISK count=1
+        mkfs.ext3 -F $OPENQRM_VM_DIR/$XEN_VM_NAME/disk$XEN_VM_COMPONENT_NUMBER.img
+        echo "file:$OPENQRM_VM_DIR/$XEN_VM_NAME/disk$XEN_VM_COMPONENT_NUMBER.img,ioemu:hda$XEN_VM_COMPONENT_NUMBER,w" > $VM_BASE_DIR/disk$XEN_VM_COMPONENT_NUMBER
+        echo "$XEN_VM_DISK" > $VM_BASE_DIR/disksize$XEN_VM_COMPONENT_NUMBER
+		# creating the cfg
+        xen_generate_vm_config $XEN_VM_NAME
+		xen_lock release
+		;;
+	remove_vm_disk)
+		if [ "$XEN_VM_NAME" == "" ]; then
+			xen_usage
+		fi
+		if [ "$XEN_VM_COMPONENT_NUMBER" == "" ]; then
+			xen_usage
+		fi
+		xen_lock aquire
+		echo "Removing disk $XEN_VM_COMPONENT_NUMBER from XEN vm $XEN_VM_NAME"
+        VM_BASE_DIR=$OPENQRM_VM_DIR/$XEN_VM_NAME
+        > $VM_BASE_DIR/disk$XEN_VM_COMPONENT_NUMBER
+        > $VM_BASE_DIR/disksize$XEN_VM_COMPONENT_NUMBER
+		rm -f $OPENQRM_VM_DIR/$XEN_VM_NAME/disk$XEN_VM_COMPONENT_NUMBER.img
+		# creating the cfg
+        xen_generate_vm_config $XEN_VM_NAME
+		xen_lock release
+		;;
+
 	*)
 		xen_usage
 		;;
