first working version :)
git-svn-id: http://openqrm.svn.sourceforge.net/svnroot/openqrm@797 f7cd0d49-994a-0410-81fc-ecfcdc9cdbae

diff --git a/trunk/src/plugins/image-shelf/bin/openqrm-image-shelf b/trunk/src/plugins/image-shelf/bin/openqrm-image-shelf
--- a/trunk/src/plugins/image-shelf/bin/openqrm-image-shelf
+++ b/trunk/src/plugins/image-shelf/bin/openqrm-image-shelf
@@ -18,8 +18,8 @@ if [ "$WHOAMI" != "root" ]; then
 fi
 
 function image-shelf_usage() {
-	echo "Usage : $0 list <-u image-shelf-url>"
-	echo "Usage : $0 get <-u image-shelf-url> <-f filename> <-n storage-server-ip:/path-to-image-dir/>"
+	echo "Usage : $0 list <-i image-shelf-url>"
+	echo "Usage : $0 get <-i image-shelf-url> <-f filename> <-n storage-server-ip:/path-to-image-dir/> <-u username> <-p password>"
 	exit 1
 }
 
@@ -29,7 +29,7 @@ shift
 
 while [ $# -ne 0 ]; do
 	case "$1" in
-		-u)
+		-i)
 			IMAGE_SHELF_URL=$2
 			shift
 			;;
@@ -39,6 +39,14 @@ while [ $# -ne 0 ]; do
 			;;
 		-n)
 			NFS_STORAGE_SERVER_EXPORT=$2
+			shift
+			;;
+		-u)
+			OPENQRM_USERNAME=$2
+			shift
+			;;
+		-p)
+			OPENQRM_PASSWORD=$2
 			shift
 			;;
 		*)
@@ -89,6 +97,58 @@ case "$IMAGE_SHELF_COMMAND" in
 		fi
 
 		IMAGE_SHELF_NAME=`echo $IMAGE_SHELF_URL | sed -e "s#http://##g" | cut -d'/' -f1`
+		
+		# prepare a temporary mount point
+		MOUNTPOINT=`mktemp -d /tmp/$IMAGE_SHELF_NAME.XXXXXXXXXX` || exit 1
+		if ! mount -t nfs $NFS_STORAGE_SERVER_EXPORT $MOUNTPOINT; then
+			image_shelf_log "ERROR: Could not mount $NFS_STORAGE_SERVER_EXPORT!"
+			exit 1
+		else
+			image_shelf_log "NOTICE: Mounted $NFS_STORAGE_SERVER_EXPORT. Starting the download."
+		fi
+		
+		# wget the image from the shelf
+		if ! wget -O $MOUNTPOINT/$IMAGE_SHELF_FILE $IMAGE_SHELF_URL/$IMAGE_SHELF_FILE; then
+			image_shelf_log "ERROR: Could not download Image-template from $IMAGE_SHELF_URL/$IMAGE_SHELF_FILE."
+			umount $MOUNTPOINT
+			rmdir $MOUNTPOINT
+			exit 1
+		else
+			image_shelf_log "NOTICE: Downloaded $IMAGE_SHELF_URL/$IMAGE_SHELF_FILE to $MOUNTPOINT/$IMAGE_SHELF_FILE."
+		fi
+
+		cp -aRv /root/$IMAGE_SHELF_FILE $MOUNTPOINT/$IMAGE_SHELF_FILE
+
+		# unpack
+		if ! tar -C $MOUNTPOINT/ -xzf $MOUNTPOINT/$IMAGE_SHELF_FILE; then
+			image_shelf_log "ERROR: Could not unpack Image-template from $IMAGE_SHELF_FILE!"
+			umount $MOUNTPOINT
+			rmdir $MOUNTPOINT
+			exit 1
+		else
+			image_shelf_log "NOTICE: Unpacked $IMAGE_SHELF_FILE"
+		fi
+		# clean up
+		rm -f $MOUNTPOINT/$IMAGE_SHELF_FILE
+		
+		# create kernel
+		# check for initrd-template
+		# check for initrd type
+
+		# check for kernel-version
+		KERNEL_VERSION=`ls $MOUNTPOINT/lib/modules/ | sort | tail -n1`
+		if ! $OPENQRM_SERVER_BASE_DIR/openqrm/bin/openqrm kernel add -n ubuntu -v $KERNEL_VERSION -u $OPENQRM_USERNAME -p $OPENQRM_PASSWORD -l $MOUNTPOINT/ -i initramfs; then
+			image_shelf_log "ERROR: Could not create kernel from Image-template $IMAGE_SHELF_FILE!"
+			umount $MOUNTPOINT
+			exit 1
+		else
+			image_shelf_log "NOTICE: Created kernel from Image-template $IMAGE_SHELF_FILE"
+		fi
+		
+		umount $MOUNTPOINT
+		rmdir $MOUNTPOINT
+		image_shelf_log "NOTICE: Successfully created Server-image from $IMAGE_SHELF_FILE"
+	
 		;;
 
 
