decreased senddelay from 30 to 10 secs added install check for hostname settings for the ssl cert reduced rpm package deps to make installation easier fixed missing collected + sshterm plugin defines for packaging
git-svn-id: http://openqrm.svn.sourceforge.net/svnroot/openqrm@1861 f7cd0d49-994a-0410-81fc-ecfcdc9cdbae

diff --git a/trunk/src/debian/openqrm.postinst b/trunk/src/debian/openqrm.postinst
--- a/trunk/src/debian/openqrm.postinst
+++ b/trunk/src/debian/openqrm.postinst
@@ -35,6 +35,35 @@ export OPENQRM_SERVER_BASE_DIR
 set -e
 
 
+# a function to validate an ip address
+openqrm_validate_ip() {
+	IP_A=$1
+	OLDIFS=$IFS
+	IFS=.
+	set -- $IP_A
+	if [ "$#" -ne "4" ]; then
+		return 1
+	fi
+
+	for oct in $1 $2 $3 $4; do
+		echo $oct | egrep "^[0-9]+$" >/dev/null 2>&1
+		if [ "$?" -ne "0" ]; then
+			return 1
+		else
+			if [ "$oct" -lt "0" -o "$oct" -gt "255" ]; then
+				return 1
+			fi
+		fi
+	done
+	echo "$IP_A" | grep "\.$" >/dev/null 2>&1
+	if [ "$?" -eq "0" ]; then
+		return 1
+	fi
+	IFS=$OLDIFS
+	return 0
+}
+
+
 case "$1" in
     configure)
         # copy pxelinux.0, tftdp does not support sym-linking it
@@ -69,6 +98,44 @@ case "$1" in
                 echo "ERROR: Could not enable SSL in the Apache webserver ! Exiting."
                 exit 1
             fi
+            # check for hostname settings
+            ETCHOSTS=/etc/hosts
+            MYHOSTNAME=`hostname`
+            if grep $MYHOSTNAME $ETCHOSTS | grep 127.0. 1>/dev/null; then
+                echo "Found system hostname $MYHOSTNAME connected to loopback interface"
+                echo "! This causes troubles while enabling SSL for the apache webserver !"
+                AVAIL_IPS=`ifconfig -a | grep -v inet6  | grep -B1 inet | grep -i -A1 link | grep -v lo | grep inet | grep -v 127.0.0.1 | cut -d':' -f2 | awk {' print $1 '}`
+                while (true); do
+                    echo "Please select one of the following ip-addresses"
+                    echo "to be connected to the systems hostname $MYHOSTNAME :"
+                    echo "$AVAIL_IPS"
+                    echo -n " : "
+                    read HOSTIP
+                    if openqrm_validate_ip "$HOSTIP"; then
+                        if echo $AVAIL_IPS | grep "$HOSTIP" 1>/dev/null; then
+                            break;
+                        else
+                            echo "$HOSTIP is not available on this system!"
+                        fi
+                    else
+                        echo "$HOSTIP is invalid!"
+                    fi
+                    done
+                echo "Connecting $HOSTIP to $MYHOSTNAME in $ETCHOSTS"
+                # remove first
+                sed -i -e "s/.*$MYHOSTNAME.*//g" $ETCHOSTS
+                sed -i -e "s/.*openQRM.*//g" $ETCHOSTS
+                # make sure we did not remove the loopback entry copmletely
+                if ! grep "127.0.*.localhost" $ETCHOSTS 1>/dev/null; then
+                    echo "127.0.0.1	localhost" >> $ETCHOSTS.new
+                    cat $ETCHOSTS >> $ETCHOSTS.new
+                    mv -f $ETCHOSTS.new $ETCHOSTS
+                fi
+                echo "# added by openQRM" >> $ETCHOSTS
+                echo "$HOSTIP	$MYHOSTNAME" >> $ETCHOSTS
+
+            fi
+
             # creating the cert + key
             PRIVATE_KEY=$OPENQRM_SERVER_BASE_DIR/openqrm/etc/ssl/private/openqrm-private.key
             CERTIFICATE_FILE=$OPENQRM_SERVER_BASE_DIR/openqrm/etc/ssl/cert/openqrm.crt
diff --git a/trunk/src/etc/init.d/openqrm b/trunk/src/etc/init.d/openqrm
--- a/trunk/src/etc/init.d/openqrm
+++ b/trunk/src/etc/init.d/openqrm
@@ -163,6 +163,46 @@ function openqrm_server_init() {
                 return 1
             fi
         fi
+
+        # check for hostname settings
+        ETCHOSTS=/etc/hosts
+        MYHOSTNAME=`hostname`
+
+        if grep $MYHOSTNAME $ETCHOSTS | grep 127.0. 1>/dev/null; then
+            echo "Found system hostname $MYHOSTNAME connected to loopback interface"
+            echo "! This causes troubles while enabling SSL for the apache webserver !"
+            AVAIL_IPS=`ifconfig -a | grep -v inet6  | grep -B1 inet | grep -i -A1 link | grep -v lo | grep inet | grep -v 127.0.0.1 | cut -d':' -f2 | awk {' print $1 '}`
+            while (true); do
+                echo "Please select one of the following ip-addresses"
+                echo "to be connected to the systems hostname $MYHOSTNAME :"
+                echo "$AVAIL_IPS"
+                echo -n " : "
+                read HOSTIP
+                if openqrm_validate_ip "$HOSTIP"; then
+                    if echo $AVAIL_IPS | grep "$HOSTIP" 1>/dev/null; then
+                        break;
+                    else
+                        echo "$HOSTIP is not available on this system!"
+                    fi
+                else
+                    echo "$HOSTIP is invalid!"
+                fi
+                done
+            echo "Connecting $HOSTIP to $MYHOSTNAME in $ETCHOSTS"
+            # remove first
+            sed -i -e "s/.*$MYHOSTNAME.*//g" $ETCHOSTS
+            sed -i -e "s/.*openQRM.*//g" $ETCHOSTS
+                # make sure we did not remove the loopback entry copmletely
+                if ! grep "127.0.*.localhost" $ETCHOSTS 1>/dev/null; then
+                        echo "127.0.0.1 localhost" >> $ETCHOSTS.new
+                        cat $ETCHOSTS >> $ETCHOSTS.new
+                        mv -f $ETCHOSTS.new $ETCHOSTS
+                fi
+            echo "# added by openQRM" >> $ETCHOSTS
+            echo "$HOSTIP	$MYHOSTNAME" >> $ETCHOSTS
+
+        fi
+
         # creating the cert + key
         PRIVATE_KEY=$OPENQRM_SERVER_BASE_DIR/openqrm/etc/ssl/private/openqrm-private.key
         CERTIFICATE_FILE=$OPENQRM_SERVER_BASE_DIR/openqrm/etc/ssl/cert/openqrm.crt
