smaller package fixes
git-svn-id: http://openqrm.svn.sourceforge.net/svnroot/openqrm@1841 f7cd0d49-994a-0410-81fc-ecfcdc9cdbae

diff --git a/trunk/src/debian/openqrm.postinst b/trunk/src/debian/openqrm.postinst
--- a/trunk/src/debian/openqrm.postinst
+++ b/trunk/src/debian/openqrm.postinst
@@ -60,6 +60,34 @@ case "$1" in
         # the default apache config normally does not allow to override the authconfig (needed for basic auth)
         # so we allow it for the openqrm directory
         cat $OPENQRM_SERVER_BASE_DIR/openqrm/etc/httpd/openqrm-httpd.conf | sed -e "s#OPENQRM_WEBSERVER_DOCUMENT_ROOT#$OPENQRM_WEBSERVER_DOCUMENT_ROOT#g" > /etc/apache2/conf.d/openqrm-httpd.conf
+
+        # ssl ?
+        if [ "$OPENQRM_WEB_PROTOCOL" == "https" ]; then
+            echo "Setting up SSL secured openQRM Website"
+            # apache ssl setup
+            if ! a2enmod ssl; then
+                echo "ERROR: Could not enable SSL in the Apache webserver ! Exiting."
+                exit 1
+            fi
+            # creating the cert + key
+            PRIVATE_KEY=$OPENQRM_SERVER_BASE_DIR/openqrm/etc/ssl/private/openqrm-private.key
+            CERTIFICATE_FILE=$OPENQRM_SERVER_BASE_DIR/openqrm/etc/ssl/cert/openqrm.crt
+            VALID_DAYS=3650
+            mkdir -p `dirname $PRIVATE_KEY`
+            mkdir -p `dirname $CERTIFICATE_FILE`
+            echo "-> Creating new private/public-keys without passphrase for server"
+            rm -f $PRIVATE_KEY
+            openssl genrsa -out $PRIVATE_KEY 1024
+            echo "-> Creating selfsigned certificate"
+            rm -f $CERTIFICATE_FILE
+            openssl req -new -days $VALID_DAYS -key $PRIVATE_KEY -x509 -out $CERTIFICATE_FILE
+            # openQRM apache ssl config
+            cat $OPENQRM_SERVER_BASE_DIR/openqrm/etc/httpd/openqrm-https.conf | \
+                sed -e "s#@@OPENQRM_SERVER_BASE_DIR@@#$OPENQRM_SERVER_BASE_DIR#g" | \
+                sed -e "s#@@OPENQRM_WEBSERVER_DOCUMENT_ROOT@@#$OPENQRM_WEBSERVER_DOCUMENT_ROOT#g" \
+                > $APACHE_CUSTOM_CONFIG_DIR/openqrm-https.conf
+        fi
+
         $OPENQRM_WEBSERVER_INIT reload
 
         # create the .htaccess file
diff --git a/trunk/src/etc/init.d/openqrm b/trunk/src/etc/init.d/openqrm
--- a/trunk/src/etc/init.d/openqrm
+++ b/trunk/src/etc/init.d/openqrm
@@ -156,10 +156,12 @@ function openqrm_server_init() {
     # ssl ?
     if [ "$OPENQRM_WEB_PROTOCOL" == "https" ]; then
         echo "Setting up SSL secured openQRM Website"
-        # apache ssl setup
-        if ! a2enmod ssl; then
-            echo "ERROR: Could not enable SSL in the Apache webserver ! Exiting."
-            return 1
+        # apache ssl setup, on centos it is enabled by default
+        if [ -f /etc/debian_version ]; then
+            if ! a2enmod ssl; then
+                echo "ERROR: Could not enable SSL in the Apache webserver ! Exiting."
+                return 1
+            fi
         fi
         # creating the cert + key
         PRIVATE_KEY=$OPENQRM_SERVER_BASE_DIR/openqrm/etc/ssl/private/openqrm-private.key
@@ -178,7 +180,10 @@ function openqrm_server_init() {
             sed -e "s#@@OPENQRM_SERVER_BASE_DIR@@#$OPENQRM_SERVER_BASE_DIR#g" | \
             sed -e "s#@@OPENQRM_WEBSERVER_DOCUMENT_ROOT@@#$OPENQRM_WEBSERVER_DOCUMENT_ROOT#g" \
             > $APACHE_CUSTOM_CONFIG_DIR/openqrm-https.conf
-
+        # check if to adjust the error log location
+        if [ -f /etc/redhat-release ]; then
+            sed -i -e "s/apache2/httpd/g" $APACHE_CUSTOM_CONFIG_DIR/openqrm-https.conf
+        fi
     fi
 
     $OPENQRM_WEBSERVER_INIT reload
