:) auto-generated nagios config
git-svn-id: http://openqrm.svn.sourceforge.net/svnroot/openqrm@828 f7cd0d49-994a-0410-81fc-ecfcdc9cdbae

diff --git a/trunk/src/plugins/nagios2/bin/openqrm-nagios-manager b/trunk/src/plugins/nagios2/bin/openqrm-nagios-manager
--- a/trunk/src/plugins/nagios2/bin/openqrm-nagios-manager
+++ b/trunk/src/plugins/nagios2/bin/openqrm-nagios-manager
@@ -17,6 +17,26 @@ CURRENTDIR=`pwd`
 export LANG=C
 
 
+# let only root run this script
+WHOAMI=`whoami`
+if [ "$WHOAMI" != "root" ]; then
+	echo "ERROR: Please run this script as root!"
+	exit 6
+fi
+
+if ! which screen 1>/dev/null; then
+	echo "ERROR: The 'screen' utility is not installed! Please install and try again."
+	image_shelf_log "ERROR: The 'screen' utility is not installed! Please install and try again."
+	exit 6
+fi
+
+# re-run in background via screen
+if [ "$RUN_IN_BACKGROUND" != "true" ]; then
+	export RUN_IN_BACKGROUND=true
+	SCREEN_NAME=`date +%T%x | sed -e "s/://g" | sed -e "s#/##g"`
+	screen -dmS $SCREEN_NAME $0 $@
+	exit	
+fi
 
 # get the ip config
 openqrm_server_get_config
@@ -27,8 +47,10 @@ case "$NAGIOS_CHECK_CMD" in
 		echo "Mapping the openQRM network"
 		# for now quite simple gathering of which network to map
 		OPENQRM_NETWORK=`echo $OPENQRM_SERVER_IP_ADDRESS | cut -d'.' -f1-3`".*"
+		nagios_manager_lock aquire
 		if ! nmap -sS -O -oX $SUBNETFILE $OPENQRM_NETWORK; then
 			nagios2_log openqrm-nagios-manager "ERROR while running nmap !"
+			nagios_manager_lock release
 			exit 1
 		fi
 		cd $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nagios2/bin
@@ -37,12 +59,13 @@ case "$NAGIOS_CHECK_CMD" in
 
 		if nagios2 -v /etc/nagios2/nagios.cfg; then
 			/etc/init.d/nagios2 restart
+			nagios_manager_lock release
 		else
 			rm -f $NAGIOS_GENERATED_CONF
 			nagios2_log openqrm-nagios-manager "ERROR: Generated nagios-configuration contains errors!"
+			nagios_manager_lock release
 			exit 1
 		fi
-
 		;;
 	*)
 		echo "Usage: $0 [map]"
