seamless supprt for different server architectures
git-svn-id: http://openqrm.svn.sourceforge.net/svnroot/openqrm@1507 f7cd0d49-994a-0410-81fc-ecfcdc9cdbae

diff --git a/trunk/src/etc/templates/openqrm-linuxrc b/trunk/src/etc/templates/openqrm-linuxrc
--- a/trunk/src/etc/templates/openqrm-linuxrc
+++ b/trunk/src/etc/templates/openqrm-linuxrc
@@ -278,9 +278,20 @@ echo "Importing kernel files"
 import_kernel
 
 # run default openqrm-client boot-service
-echo "Getting openqrm-client package"
+KERNEL_ARCH=`uname -m`
+if echo $KERNEL_ARCH | grep i.*86 1>/dev/null; then
+    # i386
+    OPENQRM_CLIENT_ARCH=i386
+else
+    OPENQRM_CLIENT_ARCH=$KERNEL_ARCH
+fi
+echo "Getting openqrm-client package $OPENQRM_CLIENT_ARCH"
 cd /
-wget -q "http://$OPENQRM_SERVER_IP_ADDRESS/openqrm/boot-service/openqrm-client.tgz"
+if ! wget -q -O openqrm-client.tgz "http://$OPENQRM_SERVER_IP_ADDRESS/openqrm/boot-service/openqrm-client.$OPENQRM_CLIENT_ARCH.tgz"; then
+    rm -f openqrm-client.tgz
+    echo "WARNING: Failed to get the openqrm-client package arch $OPENQRM_CLIENT_ARCH ! Using default one ..."
+    wget -q -O openqrm-client.tgz "http://$OPENQRM_SERVER_IP_ADDRESS/openqrm/boot-service/openqrm-client.tgz"
+fi
 tar -xzf openqrm-client.tgz
 rm -f openqrm-client.tgz
 # copy dropbear to its final destination inside the basedir
