better init script
git-svn-id: http://openqrm.svn.sourceforge.net/svnroot/openqrm@1633 f7cd0d49-994a-0410-81fc-ecfcdc9cdbae

diff --git a/trunk/src/etc/init.d/openqrm b/trunk/src/etc/init.d/openqrm
--- a/trunk/src/etc/init.d/openqrm
+++ b/trunk/src/etc/init.d/openqrm
@@ -73,11 +73,18 @@ export OPENQRM_SERVER_BASE_DIR=`pushd \`dirname $SCRIPT\`/../../../ 1>/dev/null 
 
 # functions
 
+function stop_exec_subsystem_force() {
+    kill `ps ax | grep dropbear | grep -v grep | grep openqrm | awk {' print $1 '}` 2>/dev/null || true
+    kill `ps ax | grep openqrm-cmd-queue | grep -v grep | awk {' print $1 '}` 2>/dev/null || true
+    kill `ps ax | grep openqrm-monitord | grep -v grep | awk {' print $1 '}` 2>/dev/null || true
+    return 0
+}
+
+
 
 function openqrm_server_init() {
 
 	echo "First startup detected. Running initialization."
-    /bin/rm -f ${LOCKFILE}
 	# make sure to have all enabled plugins stopped and uninstalled
 	if [ -d $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/ ]; then
 		for OPENQRM_PLUGIN in `ls $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/`; do
@@ -105,21 +112,6 @@ function openqrm_server_init() {
             exit 1
         fi
     fi
-
-    # make sure apache and db are up
-	if [ -f /etc/debian_version ]; then
-        if ! ps ax | grep apache2 | grep -v grep 1>/dev/null; then
-            $OPENQRM_WEBSERVER_INIT start
-        fi
-	elif [ -f /etc/redhat-release ]; then
-        if ! ps ax | grep httpd | grep -v grep 1>/dev/null; then
-            $OPENQRM_WEBSERVER_INIT start
-        fi
-	elif [ -f /etc/SuSE-release ]; then
-        if ! ps ax | grep apache | grep -v grep 1>/dev/null; then
-            $OPENQRM_WEBSERVER_INIT start
-        fi
-	fi
 
 	# link the web application directory to the documentroot
 	HTPASSWD="htpasswd"
@@ -181,7 +173,7 @@ function openqrm_server_init() {
     cd - 1>/dev/null
 
 
-    # init and start the remote execution layer
+    # init the remote execution layer
 	case "$OPENQRM_EXECUTION_LAYER" in
 		dropbear)
 			# init the openQRM exec-mechanism via dropbear
@@ -210,12 +202,6 @@ function openqrm_server_init() {
 			# create the comman-queue dir
 			mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/var/spool/
 			chmod 777 $OPENQRM_SERVER_BASE_DIR/openqrm/var/spool
-
-			# start the openqrm-execd daemon
-			$OPENQRM_SERVER_BASE_DIR/openqrm/sbin/dropbear -p $OPENQRM_EXEC_PORT -r $OPENQRM_SERVER_BASE_DIR/openqrm/etc/dropbear/dropbear_rsa_host_key
-			# start the openqrm-cmd-queue
-			$OPENQRM_SERVER_BASE_DIR/openqrm/sbin/openqrm-cmd-queue &
-
 			;;
 		*)
 			echo "ERROR: Un-supported command execution layer $openqrm_execution_layer ! Exiting."
@@ -225,19 +211,6 @@ function openqrm_server_init() {
 
     # create unconfigured file containing a list of available network cards to setup openQRM on
     ifconfig -a | grep -v inet6  | grep -B1 inet | grep -i link | grep -v lo | awk {' print $1 '} > $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/unconfigured
-    echo
-    if [ "$OPENQRM_SERVER_IP_ADDRESS" != "" ]; then
-        echo "Please configure your openQRM Server at : http://$OPENQRM_SERVER_IP_ADDRESS/openqrm/"
-    else
-        echo "Please configure your openQRM Server at : http://[server-ip-address]/openqrm/"
-    fi
-    echo
-    echo "-> User : openqrm"
-    echo "-> Password : openqrm"
-    echo
-    echo "Please make sure to change the default password after startup !"
-    echo
-    sleep 2
 }
 
 
@@ -245,18 +218,12 @@ function openqrm_server_init() {
 function openqrm_server_uninstall() {
 
 	echo "Uninstalling openQRM-server ver. $OPENQRM_SERVER_VERSION"
-
 	# backup state
     chmod +x $OPENQRM_SERVER_BASE_DIR/openqrm/etc/db/$OPENQRM_DATABASE_TYPE/openqrm-$OPENQRM_DATABASE_TYPE-functions
 	openqrm_server_state backup uninstall
 
-	# stopping and uninstalling all enabled plugins
-	for OPENQRM_PLUGIN in `ls $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/`; do
-		if [ -x $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/$OPENQRM_PLUGIN/etc/init.d/openqrm-plugin-$OPENQRM_PLUGIN ]; then
-			$OPENQRM_SERVER_BASE_DIR/openqrm/plugins/$OPENQRM_PLUGIN/etc/init.d/openqrm-plugin-$OPENQRM_PLUGIN stop
-			rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/$OPENQRM_PLUGIN
-		fi
-	done
+    # stop first
+    openqrm_server_stop
 
 	# drop db
 	$OPENQRM_SERVER_BASE_DIR/openqrm/etc/db/$OPENQRM_DATABASE_TYPE/openqrm-$OPENQRM_DATABASE_TYPE-functions drop
@@ -296,14 +263,58 @@ function openqrm_server_start() {
 		echo "openQRM-server ver. $OPENQRM_SERVER_VERSION is already running"
         return 1
     fi
+
+    # make sure apache is up
+	if [ -f /etc/debian_version ]; then
+        if ! ps ax | grep apache2 | grep -v grep 1>/dev/null; then
+            $OPENQRM_WEBSERVER_INIT start
+        fi
+	elif [ -f /etc/redhat-release ]; then
+        if ! ps ax | grep httpd | grep -v grep 1>/dev/null; then
+            $OPENQRM_WEBSERVER_INIT start
+        fi
+	elif [ -f /etc/SuSE-release ]; then
+        if ! ps ax | grep apache | grep -v grep 1>/dev/null; then
+            $OPENQRM_WEBSERVER_INIT start
+        fi
+	fi
+
     # check if we are at first-startup, if yes do initialization
     if [ ! -f $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/pxelinux.cfg/default ]; then
         openqrm_server_init
     fi
+    echo "Starting the openQRM-server ver. $OPENQRM_SERVER_VERSION"
+
+    # start the execution layer
+    stop_exec_subsystem_force
+    case "$OPENQRM_EXECUTION_LAYER" in
+        dropbear)
+            # start the openqrm-execd daemon
+            $OPENQRM_SERVER_BASE_DIR/openqrm/sbin/dropbear -p $OPENQRM_EXEC_PORT -r $OPENQRM_SERVER_BASE_DIR/openqrm/etc/dropbear/dropbear_rsa_host_key
+            # start the openqrm-cmd-queue
+            $OPENQRM_SERVER_BASE_DIR/openqrm/sbin/openqrm-cmd-queue &
+            ;;
+        *)
+            echo "ERROR: Un-supported command execution layer $openqrm_execution_layer ! Exiting."
+            return 1
+            ;;
+    esac
+    touch ${LOCKFILE}
+
     if [ -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/unconfigured ]; then
-        echo "Skipping startup. This openQRM-server ver. $OPENQRM_SERVER_VERSION is not configured yet."
+        echo
+        if [ "$OPENQRM_SERVER_IP_ADDRESS" != "" ]; then
+            echo "Please configure your openQRM Server at : http://$OPENQRM_SERVER_IP_ADDRESS/openqrm/"
+        else
+            echo "Please configure your openQRM Server at : http://[server-ip-address]/openqrm/"
+        fi
+        echo
+        echo "-> User : openqrm"
+        echo "-> Password : openqrm"
+        echo
+        sleep 2
+
     else
-        echo "Starting the openQRM-server ver. $OPENQRM_SERVER_VERSION"
         # check openqrm-interface
         ifconfig "$OPENQRM_SERVER_INTERFACE" | grep inet 1>/dev/null 2>&1 || \
             { echo "Interface $OPENQRM_SERVER_INTERFACE is down. Please configure and activate it and try again"; return 1; }
@@ -325,25 +336,8 @@ function openqrm_server_start() {
             return 1
         fi
 
-        # start the execution layer
-        case "$OPENQRM_EXECUTION_LAYER" in
-            dropbear)
-                killall dropbear 1>/dev/null 2>&1
-                killall openqrm-cmd-queue 1>/dev/null 2>&1
-                # start the openqrm-execd daemon
-                $OPENQRM_SERVER_BASE_DIR/openqrm/sbin/dropbear -p $OPENQRM_EXEC_PORT -r $OPENQRM_SERVER_BASE_DIR/openqrm/etc/dropbear/dropbear_rsa_host_key
-                # start the openqrm-cmd-queue
-                $OPENQRM_SERVER_BASE_DIR/openqrm/sbin/openqrm-cmd-queue &
-                ;;
-            *)
-                echo "ERROR: Un-supported command execution layer $openqrm_execution_layer ! Exiting."
-                return 1
-                ;;
-        esac
-
         # and the monitoring infra-structure
         $OPENQRM_SERVER_BASE_DIR/openqrm/sbin/openqrm-monitord &
-
         # start all enabled plugins
         echo "Starting enabled openQRM-server plugins"
         for OPENQRM_PLUGIN in `ls $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/`; do
@@ -351,8 +345,6 @@ function openqrm_server_start() {
                 $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/$OPENQRM_PLUGIN/etc/init.d/openqrm-plugin-$OPENQRM_PLUGIN start
             fi
         done
-
-        touch ${LOCKFILE}
     fi
 
 }
@@ -372,23 +364,7 @@ function openqrm_server_stop() {
         done
 
         echo "Stopping the openQRM-server ver. $OPENQRM_SERVER_VERSION"
-
-        case "$OPENQRM_EXECUTION_LAYER" in
-            dropbear)
-                killall dropbear 1>/dev/null 2>&1
-                killall openqrm-cmd-queue 1>/dev/null 2>&1
-                ;;
-            openqrm-execd)
-                killall openqrm-exec-port-monitor 1>/dev/null 2>&1
-                killall openqrm-execd 1>/dev/null 2>&1
-                ;;
-            *)
-                echo "ERROR: Un-supported command execution layer $openqrm_execution_layer ! Exiting."
-                return 1
-                ;;
-        esac
-
-        killall openqrm-monitord 1>/dev/null 2>&1
+        stop_exec_subsystem_force
         /bin/rm -f ${LOCKFILE}
     fi
 }
@@ -434,9 +410,6 @@ case "$1" in
 		;;
 	init)
 		openqrm_server_init
-		;;
-	init_config)
-		openqrm_server_init_config $ADDITIONAL_PARAM
 		;;
 	uninstall)
 		openqrm_server_uninstall
