implemented 2053329 removed runtime dependency for mysql-server
git-svn-id: http://openqrm.svn.sourceforge.net/svnroot/openqrm@1496 f7cd0d49-994a-0410-81fc-ecfcdc9cdbae

diff --git a/trunk/src/etc/init.d/openqrm-server b/trunk/src/etc/init.d/openqrm-server
--- a/trunk/src/etc/init.d/openqrm-server
+++ b/trunk/src/etc/init.d/openqrm-server
@@ -71,41 +71,37 @@ function openqrm_server_init() {
 		done
 	fi
 
+    # here we start the init
+
+	# need to copy pxelinux.0 to the tftpboot dir
+	# sym-linking it does not work because the tftpd-server does not support symlinks
+    if [ ! -f $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/pxelinux.0 ]; then
+        if [ -f /usr/lib/syslinux/pxelinux.0 ]; then
+            cp -a /usr/lib/syslinux/pxelinux.0 $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/pxelinux.0
+        elif [ -f /usr/share/syslinux/pxelinux.0 ]; then
+            cp -a /usr/share/syslinux/pxelinux.0 $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/pxelinux.0
+        else
+            echo "ERROR: Could not find syslinux pxelinux.0 file!"
+            echo "       Please copy it manually to $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/"
+            echo "       and try again ..."
+            exit 1
+        fi
+    fi
+
     # make sure apache and db are up
 	if [ -f /etc/debian_version ]; then
         if ! ps ax | grep apache2 | grep -v grep 1>/dev/null; then
             $OPENQRM_WEBSERVER_INIT start
         fi
-        OPENQRM_DATABASE_INIT="/etc/init.d/mysql"
 	elif [ -f /etc/redhat-release ]; then
         if ! ps ax | grep httpd | grep -v grep 1>/dev/null; then
             $OPENQRM_WEBSERVER_INIT start
         fi
-        OPENQRM_DATABASE_INIT="/etc/init.d/mysqld"
 	elif [ -f /etc/SuSE-release ]; then
         if ! ps ax | grep apache | grep -v grep 1>/dev/null; then
             $OPENQRM_WEBSERVER_INIT start
         fi
-        OPENQRM_DATABASE_INIT="/etc/init.d/mysql"
-
 	fi
-    if [ "$OPENQRM_DATABASE_TYPE" == "mysql" ]; then
-        if ! ps ax | grep mysqld | grep -v grep 1>/dev/null; then
-            if [ -x "$OPENQRM_DATABASE_INIT" ]; then
-                $OPENQRM_DATABASE_INIT start
-            else
-                echo "ERROR: Could not start MySQL !"
-                echo "Please start MySQL manually and try again"
-                exit -1
-            fi
-        fi
-    fi
-    # let the db come up
-    sleep 2
-
-	# initialyze the database
-	chmod +x $OPENQRM_SERVER_BASE_DIR/openqrm/etc/db/$OPENQRM_DATABASE_TYPE/openqrm-$OPENQRM_DATABASE_TYPE-functions
-	$OPENQRM_SERVER_BASE_DIR/openqrm/etc/db/$OPENQRM_DATABASE_TYPE/openqrm-$OPENQRM_DATABASE_TYPE-functions init
 
 	# link the web application directory to the documentroot
 	HTPASSWD="htpasswd"
@@ -148,14 +144,13 @@ function openqrm_server_init() {
 	cat $OPENQRM_SERVER_BASE_DIR/openqrm/etc/httpd/openqrm-htaccess.conf | sed -e "s#OPENQRM_WEBSERVER_DOCUMENT_ROOT#$OPENQRM_WEBSERVER_DOCUMENT_ROOT#g" > $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/.htaccess
 	# create the default admin user
 	$HTPASSWD -bc $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/.htpasswd openqrm openqrm
-	# create the default anonymous user
-	$HTPASSWD -b $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/.htpasswd anonymous openqrm
 	chmod 666 $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/.htpasswd
 
 	# create the image-auth dir
 	mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/web/action/image-auth
 	chmod 777 $OPENQRM_SERVER_BASE_DIR/openqrm/web/action/image-auth
 
+    # init and start the remote execution layer
 	case "$OPENQRM_EXECUTION_LAYER" in
 		dropbear)
 			# init the openQRM exec-mechanism via dropbear
@@ -184,67 +179,137 @@ function openqrm_server_init() {
 			# create the comman-queue dir
 			mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/var/spool/
 			chmod 777 $OPENQRM_SERVER_BASE_DIR/openqrm/var/spool
+
+			# start the openqrm-execd daemon
+			$OPENQRM_SERVER_BASE_DIR/openqrm/sbin/dropbear -p $OPENQRM_EXEC_PORT -r $OPENQRM_SERVER_BASE_DIR/openqrm/etc/dropbear/dropbear_rsa_host_key
+			# start the openqrm-cmd-queue
+			$OPENQRM_SERVER_BASE_DIR/openqrm/sbin/openqrm-cmd-queue &
+
+			;;
+		*)
+			echo "ERROR: Un-supported command execution layer $openqrm_execution_layer ! Exiting."
+			return 1
 			;;
 	esac
 
-	# here we create + add the default kernel+kernel-version to the openQRM-server
-	# via the kernel-action.form. If this returns bad something is wrong
-	DEFAULT_KERNEL_VERSION=`uname -r`
-	echo "Creating the default kernel version $DEFAULT_KERNEL_VERSION"
-	if [ -f /etc/debian_version ]; then
-		INITRD_TYPE="initramfs"
-	elif [ -f /etc/SuSE-release ]; then
-		INITRD_TYPE="initramfs"
-	elif [ -f /etc/fedora-release ]; then
-		INITRD_TYPE="initramfs"
-	else
-		INITRD_TYPE="ext2"
-	fi
-	openqrm_server_create_kernel default $DEFAULT_KERNEL_VERSION / $INITRD_TYPE
-	if ! openqrm_server_manage_kernel add openqrm openqrm default $DEFAULT_KERNEL_VERSION; then
-		echo "WARNING: Could not add the default kernel!"
-		echo "         Please check your Apache-configuration according openQRM"
-		exit -1
-	fi
+    # create unconfigured file containing a list of available network cards to setup openQRM on
+    ifconfig -a | grep -v inet6  | grep -B1 inet | grep -i link | grep -v lo | awk {' print $1 '} > $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/unconfigured
+    echo
+    if [ "$OPENQRM_SERVER_IP_ADDRESS" != "" ]; then
+        echo "Please configure your openQRM Server at : http://$OPENQRM_SERVER_IP_ADDRESS/openqrm/"
+    else
+        echo "Please configure your openQRM Server at : http://[server-ip-address]/openqrm/"
+    fi
+    echo
+    echo "-> User : openqrm"
+    echo "-> Password : openqrm"
+    echo
+    echo "Please make sure to change the default password after startup !"
+    echo
+    sleep 2
+}
 
-	# create $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/pxelinux.cfg/default
-	mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/pxelinux.cfg/
-	openqrm_server_create_pxe_config -1 default default
 
-	# add automatic startup to init
-	openqrm_chkconfig add openqrm-server
-	
-	# need to copy pxelinux.0 to the tftpboot dir
-	# sym-linking it does not work because the tftpd-server does not support symlinks
-	if [ -f /usr/lib/syslinux/pxelinux.0 ]; then
-		cp -a /usr/lib/syslinux/pxelinux.0 $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/pxelinux.0
-	elif [ -f /usr/share/syslinux/pxelinux.0 ]; then
-		cp -a /usr/share/syslinux/pxelinux.0 $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/pxelinux.0
-	else
-		echo "ERROR: Could not find syslinux pxelinux.0 file!"
-		echo "       Please copy it manually to $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/"
-		echo "       and try again ..."
-		exit 1		
-	fi
-	
-	# check if backups are not locked
-	if [ ! -f $OPENQRM_SERVER_STATE_DIR/locked ]; then
-		if [ "$OPENQRM_RESTORE_STATE" != "false" ]; then
-			# check if there is a server state to restore
-			LAST_SERVER_STATE_BACKUP=`ls -tr $OPENQRM_SERVER_STATE_DIR/uninstall-* 2>/dev/null | tail -n1 | sed -s "s/\.tgz//g"`
-			if [ "$LAST_SERVER_STATE_BACKUP" != "" ]; then
-				LAST_SERVER_STATE_BACKUP=`basename $LAST_SERVER_STATE_BACKUP`
-				echo "NOTICE: Found backup of last openQRM-server state $LAST_SERVER_STATE_BACKUP, restoring it"
-				openqrm_server_state restore $LAST_SERVER_STATE_BACKUP
-			fi
-		fi
-	else
-		echo "NOTICE: Found openQRM-server state backups locked by $OPENQRM_SERVER_STATE_DIR/locked"
-		echo "        To enable automatic state restore please remove this lockfile."
-		echo "NOTICE: Skipping openQRM-server state restore"
-	fi
+
+
+# this function is being ran from the ui after
+# openqrm-server.conf is being setup correctly
+function openqrm_server_init_config() {
+    RESTORE_LAST_STATE=$1
+
+    if [ -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/unconfigured ]; then
+        echo "NOTICE: Initialyzing the openQRM Database ..."
+        echo "NOTICE: Initialyzing the openQRM Database ..." | logger
+
+
+        # initialyze the database
+        chmod +x $OPENQRM_SERVER_BASE_DIR/openqrm/etc/db/$OPENQRM_DATABASE_TYPE/openqrm-$OPENQRM_DATABASE_TYPE-functions
+        if ! $OPENQRM_SERVER_BASE_DIR/openqrm/etc/db/$OPENQRM_DATABASE_TYPE/openqrm-$OPENQRM_DATABASE_TYPE-functions init; then
+            echo "ERROR: Could not initialyze the openQRM Database !"
+            echo "       Please check your Database-configuration"
+            echo "ERROR: Could not initialyze the openQRM Database !" | logger
+            echo "       Please check your Database-configuration" | logger
+            return -1
+        fi
+
+        # check if we should restore the last state
+        if [ "$RESTORE_LAST_STATE" == "restore" ]; then
+            echo "NOTICE: Restoring last openQRM state backup ..."
+            echo "NOTICE: Restoring last openQRM state backup ..." | logger
+            # check if backups are not locked
+            if [ ! -f $OPENQRM_SERVER_STATE_DIR/locked ]; then
+                if [ "$OPENQRM_RESTORE_STATE" != "false" ]; then
+                    # check if there is a server state to restore
+                    LAST_SERVER_STATE_BACKUP=`ls -tr $OPENQRM_SERVER_STATE_DIR/uninstall-* 2>/dev/null | tail -n1 | sed -s "s/\.tgz//g"`
+                    if [ "$LAST_SERVER_STATE_BACKUP" != "" ]; then
+                        LAST_SERVER_STATE_BACKUP=`basename $LAST_SERVER_STATE_BACKUP`
+                        echo "NOTICE: Found backup of last openQRM-server state $LAST_SERVER_STATE_BACKUP, restoring it"
+                        echo "NOTICE: Found backup of last openQRM-server state $LAST_SERVER_STATE_BACKUP, restoring it" | logger
+                        openqrm_server_state restore $LAST_SERVER_STATE_BACKUP
+                    fi
+                fi
+            else
+                echo "NOTICE: Found openQRM-server state backups locked by $OPENQRM_SERVER_STATE_DIR/locked"
+                echo "        To enable automatic state restore please remove this lockfile."
+                echo "NOTICE: Skipping openQRM-server state restore"
+                echo "NOTICE: Found openQRM-server state backups locked by $OPENQRM_SERVER_STATE_DIR/locked" | logger
+                echo "NOTICE: Skipping openQRM-server state restore" | logger
+            fi
+        else
+            echo "NOTICE: Skipping openQRM state restore ..."
+            echo "NOTICE: Skipping openQRM state restore ..." | logger
+        fi
+
+        # create $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/pxelinux.cfg/default
+        echo "NOTICE: Creating default PXE-configuration"
+        echo "NOTICE: Creating default PXE-configuration" | logger
+        mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/pxelinux.cfg/
+        openqrm_server_create_pxe_config -1 default default
+
+        # add automatic startup to init
+        openqrm_chkconfig add openqrm-server
+
+        # here we create + add the default kernel+kernel-version to the openQRM-server
+        # via the kernel-action.form. If this returns bad something is wrong
+        DEFAULT_KERNEL_VERSION=`uname -r`
+        echo "NOTICE: Creating the default kernel version $DEFAULT_KERNEL_VERSION"
+        echo "NOTICE: Creating the default kernel version $DEFAULT_KERNEL_VERSION" | logger
+        if [ -f /etc/debian_version ]; then
+            INITRD_TYPE="initramfs"
+        elif [ -f /etc/SuSE-release ]; then
+            INITRD_TYPE="initramfs"
+        elif [ -f /etc/fedora-release ]; then
+            INITRD_TYPE="initramfs"
+        else
+            INITRD_TYPE="ext2"
+        fi
+        openqrm_server_create_kernel default $DEFAULT_KERNEL_VERSION / $INITRD_TYPE
+        if ! openqrm_server_manage_kernel add openqrm openqrm default $DEFAULT_KERNEL_VERSION; then
+            echo "ERROR: Could not add the default kernel!"
+            echo "         Please check your Apache-configuration according openQRM"
+            echo "ERROR: Could not add the default kernel! Please check your Apache-configuration according openQRM" | logger
+            return -1
+        fi
+
+        # remove configure lock
+        rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/unconfigured
+
+        # (re-) start
+        $0 start
+        echo "NOTICE: Successfully initialyzed and started the openQRM Server"
+        echo "NOTICE: Successfully initialyzed and started the openQRM Server" | logger
+        return 0
+
+    else
+        echo "NOTICE: This openQRM Server is already configured. Skipping re-init"
+        echo "NOTICE: This openQRM Server is already configured. Skipping re-init" | logger
+        return 0
+    fi
 
 }
+
+
+
 
 
 function openqrm_server_uninstall() {
@@ -252,6 +317,7 @@ function openqrm_server_uninstall() {
 	echo "Uninstalling openQRM-server ver. $OPENQRM_SERVER_VERSION"
 
 	# backup state
+    chmod +x $OPENQRM_SERVER_BASE_DIR/openqrm/etc/db/$OPENQRM_DATABASE_TYPE/openqrm-$OPENQRM_DATABASE_TYPE-functions
 	openqrm_server_state backup uninstall
 
 	# stopping and uninstalling all enabled plugins
@@ -296,53 +362,65 @@ function openqrm_server_uninstall() {
 
 
 function openqrm_server_start() {
-	echo "Starting the openQRM-server ver. $OPENQRM_SERVER_VERSION"
-	# check if we are at first-startup, if yes do initialization
-	if [ ! -f $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/pxelinux.cfg/default ]; then
-		openqrm_server_init
-	fi
-		
-	# check openqrm-interface
-	ifconfig "$OPENQRM_SERVER_INTERFACE" | grep inet 1>/dev/null 2>&1 || \
-		{ echo "Interface $OPENQRM_SERVER_INTERFACE is down. Please configure and activate it and try again"; return 1; }
-	CONFIGURED_IP=$(cat $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/pxelinux.cfg/default | grep "openqrm=" | sed -e "s/.*openqrm=//" | awk {' print $1 '})
-	if [ "$OPENQRM_SERVER_IP_ADDRESS" != "$CONFIGURED_IP" ]; then
-		echo -e "Interface $OPENQRM_SERVER_INTERFACE has the wrong ip-configuration.\n" \
-			  "       The openQRM-server is configured to have the ip-address $CONFIGURED_IP\n" \
-  			  "       but the interface $OPENQRM_SERVER_INTERFACE is running with the ip-address $OPENQRM_SERVER_IP_ADDRESS"
-		return 1
-	fi
 
-	# start the execution layer
-	case "$OPENQRM_EXECUTION_LAYER" in
-		dropbear)
-			# start the openqrm-execd daemon
-			$OPENQRM_SERVER_BASE_DIR/openqrm/sbin/dropbear -p $OPENQRM_EXEC_PORT -r $OPENQRM_SERVER_BASE_DIR/openqrm/etc/dropbear/dropbear_rsa_host_key
-			# start the openqrm-cmd-queue
-			$OPENQRM_SERVER_BASE_DIR/openqrm/sbin/openqrm-cmd-queue &
-			;;
-		openqrm-execd)
-			# start the openqrm-execd daemon
-			$OPENQRM_SERVER_BASE_DIR/openqrm/sbin/openqrm-exec-port-monitor $OPENQRM_SERVER_IP_ADDRESS $OPENQRM_EXEC_PORT | $OPENQRM_SERVER_BASE_DIR/openqrm/sbin/openqrm-execd &
-			;;
-		*)
-			echo "ERROR: Un-supported command execution layer $openqrm_execution_layer ! Exiting."
-			return 1
-			;;
-	esac
+    # check if we are at first-startup, if yes do initialization
+    if [ ! -f $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/pxelinux.cfg/default ]; then
+        openqrm_server_init
+    fi
+    if [ -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/unconfigured ]; then
+        echo "Skipping startup. This openQRM-server ver. $OPENQRM_SERVER_VERSION is not configured yet."
+    else
+        echo "Starting the openQRM-server ver. $OPENQRM_SERVER_VERSION"
+        # check openqrm-interface
+        ifconfig "$OPENQRM_SERVER_INTERFACE" | grep inet 1>/dev/null 2>&1 || \
+            { echo "Interface $OPENQRM_SERVER_INTERFACE is down. Please configure and activate it and try again"; return 1; }
+        CONFIGURED_IP=$(cat $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/pxelinux.cfg/default | grep "openqrm=" | sed -e "s/.*openqrm=//" | awk {' print $1 '})
+        if [ "$OPENQRM_SERVER_IP_ADDRESS" != "$CONFIGURED_IP" ]; then
+            echo -e "Interface $OPENQRM_SERVER_INTERFACE has the wrong ip-configuration.\n" \
+                  "       The openQRM-server is configured to have the ip-address $CONFIGURED_IP\n" \
+                  "       but the interface $OPENQRM_SERVER_INTERFACE is running with the ip-address $OPENQRM_SERVER_IP_ADDRESS"
+            # create lockfile again to forcre re-configuration
+            touch $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/unconfigured
+            echo
+            if [ "$OPENQRM_SERVER_IP_ADDRESS" != "" ]; then
+                echo "Please re-configure your openQRM Server at : http://$OPENQRM_SERVER_IP_ADDRESS/openqrm/"
+            else
+                echo "Please re-configure your openQRM Server at : http://[server-ip-address]/openqrm/"
+            fi
+            echo
+            sleep 2
+            return 1
+        fi
 
-	# and the monitoring infra-structure	
-	$OPENQRM_SERVER_BASE_DIR/openqrm/sbin/openqrm-monitord &
+        # start the execution layer
+        case "$OPENQRM_EXECUTION_LAYER" in
+            dropbear)
+                killall dropbear 1>/dev/null 2>&1
+                killall openqrm-cmd-queue 1>/dev/null 2>&1
+                # start the openqrm-execd daemon
+                $OPENQRM_SERVER_BASE_DIR/openqrm/sbin/dropbear -p $OPENQRM_EXEC_PORT -r $OPENQRM_SERVER_BASE_DIR/openqrm/etc/dropbear/dropbear_rsa_host_key
+                # start the openqrm-cmd-queue
+                $OPENQRM_SERVER_BASE_DIR/openqrm/sbin/openqrm-cmd-queue &
+                ;;
+            *)
+                echo "ERROR: Un-supported command execution layer $openqrm_execution_layer ! Exiting."
+                return 1
+                ;;
+        esac
 
-	# start all enabled plugins
-	echo "Starting enabled openQRM-server plugins"
-	for OPENQRM_PLUGIN in `ls $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/`; do
-		if [ -x $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/$OPENQRM_PLUGIN/etc/init.d/openqrm-plugin-$OPENQRM_PLUGIN ]; then
-			$OPENQRM_SERVER_BASE_DIR/openqrm/plugins/$OPENQRM_PLUGIN/etc/init.d/openqrm-plugin-$OPENQRM_PLUGIN start
-		fi
-	done
+        # and the monitoring infra-structure
+        $OPENQRM_SERVER_BASE_DIR/openqrm/sbin/openqrm-monitord &
 
-	touch ${LOCKFILE}
+        # start all enabled plugins
+        echo "Starting enabled openQRM-server plugins"
+        for OPENQRM_PLUGIN in `ls $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/`; do
+            if [ -x $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/$OPENQRM_PLUGIN/etc/init.d/openqrm-plugin-$OPENQRM_PLUGIN ]; then
+                $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/$OPENQRM_PLUGIN/etc/init.d/openqrm-plugin-$OPENQRM_PLUGIN start
+            fi
+        done
+
+        touch ${LOCKFILE}
+    fi
 	
 }
 
@@ -391,6 +469,7 @@ function openqrm_server_status() {
 
 
 # main
+ADDITIONAL_PARAM=$2
 case "$1" in
 	start)
 		openqrm_server_start
@@ -408,6 +487,9 @@ case "$1" in
 		;;
 	init)
 		openqrm_server_init
+		;;
+	init_config)
+		openqrm_server_init_config $ADDITIONAL_PARAM
 		;;
 	uninstall)
 		openqrm_server_uninstall
