Feature reqeust 2874621 moved openQRM to https
git-svn-id: http://openqrm.svn.sourceforge.net/svnroot/openqrm@1769 f7cd0d49-994a-0410-81fc-ecfcdc9cdbae

diff --git a/trunk/src/etc/init.d/openqrm b/trunk/src/etc/init.d/openqrm
--- a/trunk/src/etc/init.d/openqrm
+++ b/trunk/src/etc/init.d/openqrm
@@ -120,14 +120,17 @@ function openqrm_server_init() {
 		ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/web/ $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm
 		# the default apache config normally does not allow to override the authconfig (needed for basic auth)
 		# so we allow it for the openqrm directory
-		cat $OPENQRM_SERVER_BASE_DIR/openqrm/etc/httpd/openqrm-httpd.conf | sed -e "s#OPENQRM_WEBSERVER_DOCUMENT_ROOT#$OPENQRM_WEBSERVER_DOCUMENT_ROOT#g" >> /etc/apache2/conf.d/openqrm-httpd.conf
+        APACHE_CUSTOM_CONFIG_DIR="/etc/apache2/conf.d"
+		cat $OPENQRM_SERVER_BASE_DIR/openqrm/etc/httpd/openqrm-httpd.conf | sed -e "s#OPENQRM_WEBSERVER_DOCUMENT_ROOT#$OPENQRM_WEBSERVER_DOCUMENT_ROOT#g" >> $APACHE_CUSTOM_CONFIG_DIR/openqrm-httpd.conf
 	elif [ -f /etc/redhat-release ]; then
+        APACHE_CUSTOM_CONFIG_DIR="/etc/httpd/conf.d"
 		ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/web/ $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm
-		cat $OPENQRM_SERVER_BASE_DIR/openqrm/etc/httpd/openqrm-httpd.conf | sed -e "s#OPENQRM_WEBSERVER_DOCUMENT_ROOT#$OPENQRM_WEBSERVER_DOCUMENT_ROOT#g" >> /etc/httpd/conf.d/openqrm-httpd.conf
+		cat $OPENQRM_SERVER_BASE_DIR/openqrm/etc/httpd/openqrm-httpd.conf | sed -e "s#OPENQRM_WEBSERVER_DOCUMENT_ROOT#$OPENQRM_WEBSERVER_DOCUMENT_ROOT#g" >> $APACHE_CUSTOM_CONFIG_DIR/openqrm-httpd.conf
 	elif [ -f /etc/SuSE-release ]; then
+        APACHE_CUSTOM_CONFIG_DIR="/etc/apache2/conf.d"
 		HTPASSWD="htpasswd2"
 		ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/web/ $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm
-		cat $OPENQRM_SERVER_BASE_DIR/openqrm/etc/httpd/openqrm-httpd.conf | sed -e "s#OPENQRM_WEBSERVER_DOCUMENT_ROOT#$OPENQRM_WEBSERVER_DOCUMENT_ROOT#g" >> /etc/apache2/conf.d/openqrm-httpd.conf
+		cat $OPENQRM_SERVER_BASE_DIR/openqrm/etc/httpd/openqrm-httpd.conf | sed -e "s#OPENQRM_WEBSERVER_DOCUMENT_ROOT#$OPENQRM_WEBSERVER_DOCUMENT_ROOT#g" >> $APACHE_CUSTOM_CONFIG_DIR/openqrm-httpd.conf
 		# we need a special treatment for suse to allow followsymlinks in the default-setup
 		DEFAULT_CONF=/etc/apache2/default-server.conf
 		NEW_CONF=/etc/apache2/default-server.conf.new
@@ -149,7 +152,36 @@ function openqrm_server_init() {
 			fi
 		fi
 	fi
-	$OPENQRM_WEBSERVER_INIT reload
+
+    # ssl ?
+    if [ "$OPENQRM_WEB_PROTOCOL" == "https" ]; then
+        echo "Setting up SSL secured openQRM Website"
+        # apache ssl setup
+        if ! a2enmod ssl; then
+            echo "ERROR: Could not enable SSL in the Apache webserver ! Exiting."
+            return 1
+        fi
+        # creating the cert + key
+        PRIVATE_KEY=$OPENQRM_SERVER_BASE_DIR/openqrm/etc/ssl/private/openqrm-private.key
+        CERTIFICATE_FILE=$OPENQRM_SERVER_BASE_DIR/openqrm/etc/ssl/cert/openqrm.crt
+        VALID_DAYS=3650
+        mkdir -p `dirname $PRIVATE_KEY`
+        mkdir -p `dirname $CERTIFICATE_FILE`
+        echo "-> Creating new private/public-keys without passphrase for server"
+        rm -f $PRIVATE_KEY
+        openssl genrsa -out $PRIVATE_KEY 1024
+        echo "-> Creating selfsigned certificate"
+        rm -f $CERTIFICATE_FILE
+        openssl req -new -days $VALID_DAYS -key $PRIVATE_KEY -x509 -out $CERTIFICATE_FILE
+        # openQRM apache ssl config
+		cat $OPENQRM_SERVER_BASE_DIR/openqrm/etc/httpd/openqrm-https.conf | \
+            sed -e "s#@@OPENQRM_SERVER_BASE_DIR@@#$OPENQRM_SERVER_BASE_DIR#g" | \
+            sed -e "s#@@OPENQRM_WEBSERVER_DOCUMENT_ROOT@@#$OPENQRM_WEBSERVER_DOCUMENT_ROOT#g" \
+            > $APACHE_CUSTOM_CONFIG_DIR/openqrm-https.conf
+
+    fi
+
+    $OPENQRM_WEBSERVER_INIT reload
 
 	# create the .htaccess file
 	cat $OPENQRM_SERVER_BASE_DIR/openqrm/etc/httpd/openqrm-htaccess.conf | sed -e "s#OPENQRM_WEBSERVER_DOCUMENT_ROOT#$OPENQRM_WEBSERVER_DOCUMENT_ROOT#g" > $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/.htaccess
@@ -312,9 +344,9 @@ function openqrm_server_start() {
     if [ -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/unconfigured ]; then
         echo
         if [ "$OPENQRM_SERVER_IP_ADDRESS" != "" ]; then
-            echo "Please configure your openQRM Server at : http://$OPENQRM_SERVER_IP_ADDRESS/openqrm/"
+            echo "Please configure your openQRM Server at : $OPENQRM_WEB_PROTOCOL://$OPENQRM_SERVER_IP_ADDRESS/openqrm/"
         else
-            echo "Please configure your openQRM Server at : http://[server-ip-address]/openqrm/"
+            echo "Please configure your openQRM Server at : $OPENQRM_WEB_PROTOCOL://[server-ip-address]/openqrm/"
         fi
         echo
         echo "-> User : openqrm"
diff --git a/trunk/src/plugins/iscsi-storage/bin/openqrm-iscsi-storage b/trunk/src/plugins/iscsi-storage/bin/openqrm-iscsi-storage
--- a/trunk/src/plugins/iscsi-storage/bin/openqrm-iscsi-storage
+++ b/trunk/src/plugins/iscsi-storage/bin/openqrm-iscsi-storage
@@ -30,9 +30,13 @@ elif [ -f $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf ]; then
 	OPENQRM_SERVER_IP=localhost
 	resource_id=0
 	resource_openqrmserver=$OPENQRM_SERVER_IP_ADDRESS
+    openqrm_web_protocol=$OPENQRM_WEB_PROTOCOL
 fi
 export LANG=C
-
+# define wget to use with https
+if [ "$openqrm_web_protocol" == "https" ]; then
+    WGET_NO_CERT_CHECK="--no-check-certificate"
+fi
 # let only root run this script
 WHOAMI=`whoami`
 if [ "$WHOAMI" != "root" ]; then
@@ -228,7 +232,7 @@ IFS='
 		done
 		IFS=$OLD_IFS
         sed -i -e "s/ \{1,\}/@/g" $STORAGE_STATUS_TMP
-		if ! wget -q -O /dev/null --http-user=$ISCSI_OPENQRM_USERNAME --http-password=$ISCSI_OPENQRM_PASSWORD  --post-file=`$OPENQRM_POSTENCODE $STORAGE_STATUS_TMP` http://$OPENQRM_SERVER_IP/openqrm/base/plugins/iscsi-storage/iscsi-storage-action.php?iscsi_storage_command=get_storage; then
+		if ! wget -q $WGET_NO_CERT_CHECK -O /dev/null --http-user=$ISCSI_OPENQRM_USERNAME --http-password=$ISCSI_OPENQRM_PASSWORD  --post-file=`$OPENQRM_POSTENCODE $STORAGE_STATUS_TMP` $openqrm_web_protocol://$OPENQRM_SERVER_IP/openqrm/base/plugins/iscsi-storage/iscsi-storage-action.php?iscsi_storage_command=get_storage; then
 			echo "ERROR: Could not post the iscsi-export status to the openQRM-server at $resource_openqrmserver!"
 			echo "ERROR: Could not post the iscsi-export status to the openQRM-server at $resource_openqrmserver!" | logger
 		fi
@@ -250,7 +254,8 @@ IFS='
 			echo "$IMAGE_NAME,/dev/$IMAGE_NAME/$LUN" >> $STORAGE_STATUS_TMP
 		done
 		IFS=$OLD_IFS
-		if ! wget -q -O /dev/null --http-user=$ISCSI_OPENQRM_USERNAME --http-password=$ISCSI_OPENQRM_PASSWORD  --post-file=`$OPENQRM_POSTENCODE $STORAGE_STATUS_TMP` http://$OPENQRM_SERVER_IP/openqrm/base/plugins/iscsi-storage/iscsi-storage-action.php?iscsi_storage_command=get_ident; then			echo "ERROR: Could not post the iscsi-export status to the openQRM-server at $resource_openqrmserver!"
+		if ! wget -q $WGET_NO_CERT_CHECK -O /dev/null --http-user=$ISCSI_OPENQRM_USERNAME --http-password=$ISCSI_OPENQRM_PASSWORD  --post-file=`$OPENQRM_POSTENCODE $STORAGE_STATUS_TMP` $openqrm_web_protocol://$OPENQRM_SERVER_IP/openqrm/base/plugins/iscsi-storage/iscsi-storage-action.php?iscsi_storage_command=get_ident; then
+			echo "ERROR: Could not post the iscsi-export status to the openQRM-server at $resource_openqrmserver!"
 			echo "ERROR: Could not post the iscsi-export status to the openQRM-server at $resource_openqrmserver!" | logger
 		fi
 		rm -f $STORAGE_STATUS_TMP
diff --git a/trunk/src/plugins/linux-vserver/etc/init.d/linux-vserver b/trunk/src/plugins/linux-vserver/etc/init.d/linux-vserver
--- a/trunk/src/plugins/linux-vserver/etc/init.d/linux-vserver
+++ b/trunk/src/plugins/linux-vserver/etc/init.d/linux-vserver
@@ -29,6 +29,12 @@ elif [ -f $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf ]; then
 	. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
 	openqrm_server_get_config
 	OPENQRM_SERVER_IP=$OPENQRM_SERVER_IP_ADDRESS
+    export resource_openqrmserver=$OPENQRM_SERVER_IP_ADDRESS
+    export openqrm_web_protocol=$OPENQRM_WEB_PROTOCOL
+fi
+# define wget to use with https
+if [ "$openqrm_web_protocol" == "https" ]; then
+    WGET_NO_CERT_CHECK="--no-check-certificate"
 fi
 
 # do not start on the intitrd
@@ -41,8 +47,8 @@ function linux_vserver_start() {
 	linux_vserver_stop 1>/dev/null 2>&1
 	# download the initrd
 	mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/linux-vserver/etc/templates
-	if ! wget -q -O $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/linux-vserver/etc/templates/openqrm-initrd-default.tgz http://$OPENQRM_SERVER_IP/openqrm/boot-service/openqrm-initrd-default.tgz; then
-		echo "ERROR: Could not download http://$OPENQRM_SERVER_IP/openqrm/boot-service/openqrm-initrd-default.tgz"
+	if ! wget -q $WGET_NO_CERT_CHECK -O $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/linux-vserver/etc/templates/openqrm-initrd-default.tgz $openqrm_web_protocol://$OPENQRM_SERVER_IP/openqrm/boot-service/openqrm-initrd-default.tgz; then
+		echo "ERROR: Could not download $openqrm_web_protocol://$OPENQRM_SERVER_IP/openqrm/boot-service/openqrm-initrd-default.tgz"
 		return 1
 	fi
 	# start all vifs
diff --git a/trunk/src/plugins/vmware-esx/bin/openqrm-vmware-esx-monitord b/trunk/src/plugins/vmware-esx/bin/openqrm-vmware-esx-monitord
--- a/trunk/src/plugins/vmware-esx/bin/openqrm-vmware-esx-monitord
+++ b/trunk/src/plugins/vmware-esx/bin/openqrm-vmware-esx-monitord
@@ -25,7 +25,10 @@ PASSWORD=$5
 MONITORD_LOCKFILE="/var/run/openqrm-vmware-esx-monitord"
 OPENQRM_RESOURCE_PARAMETER_FILE="/var/openqrm/openqrm-resource.conf"
 export LANG=C
-
+# define wget to use with https
+if [ "$openqrm_web_protocol" == "https" ]; then
+    WGET_NO_CERT_CHECK="--no-check-certificate"
+fi
 
 # stop and exit
 if [ "$MONITOR_CMD" == "stop" ]; then
@@ -79,14 +82,26 @@ if [ ! -f "$OPENQRM_RESOURCE_PARAMETER_FILE" ]; then
 	# remove whitespaces
 	resource_mac=`echo $resource_mac`
 	echo "Using $resource_ip/$resource_mac"
-	wget -q -O $OPENQRM_RESOURCE_PARAMETER_FILE "http://$OPENQRM_SERVER_IP/openqrm/action/resource-monitor.php?resource_command=get_parameter&resource_id=$resource_id&resource_mac=$resource_mac&resource_ip=$resource_ip"
-	sleep 3
-	if [ ! -f "$OPENQRM_RESOURCE_PARAMETER_FILE" ]; then
-		echo "ERROR: Could not integrate the VMware ESX server into the openQRM-server at $OPENQRM_SERVER_IP!"
-		rm -f $MONITORD_LOCKFILE
-		exit 1
-	fi
+    # try https first
+	wget -q $WGET_NO_CERT_CHECK -O $OPENQRM_RESOURCE_PARAMETER_FILE "https://$OPENQRM_SERVER_IP/openqrm/action/resource-monitor.php?resource_command=get_parameter&resource_id=$resource_id&resource_mac=$resource_mac&resource_ip=$resource_ip"
+	sleep 2
+    # check if https was successfull
+    if ! grep resource_openqrmserver $OPENQRM_RESOURCE_PARAMETER_FILE 1>/dev/null 2>&1; then
+        # try http
+        wget -q -O $OPENQRM_RESOURCE_PARAMETER_FILE "http://$OPENQRM_SERVER_IP/openqrm/action/resource-monitor.php?resource_command=get_parameter&resource_id=$resource_id&resource_mac=$resource_mac&resource_ip=$resource_ip"
+        sleep 2
+        # check if http was successfull
+        if ! grep resource_openqrmserver $OPENQRM_RESOURCE_PARAMETER_FILE 1>/dev/null 2>&1; then
+            echo "ERROR: Could not integrate the VMware ESX server into the openQRM-server at $OPENQRM_SERVER_IP!"
+            rm -f $MONITORD_LOCKFILE
+            exit 1
+        fi
+    fi
 	. $OPENQRM_RESOURCE_PARAMETER_FILE
+    # define wget to use with https
+    if [ "$openqrm_web_protocol" == "https" ]; then
+        WGET_NO_CERT_CHECK="--no-check-certificate"
+    fi
 
 	# gather some more details to create the appliance on the openQRM-server
 	local_server_root_device=`mount | grep ' / ' | awk {' print $1 '}`
@@ -94,12 +109,12 @@ if [ ! -f "$OPENQRM_RESOURCE_PARAMETER_FILE" ]; then
 	local_server_kernel_version=`uname -r`
 
 	# now we integrate it via the local-sever plugin
-	if ! wget -O /dev/null -q "http://$OPENQRM_SERVER_IP/openqrm/action/vmware-esx-integrate.php?USER=$USER&PASSWORD=$PASSWORD&local_server_command=integrate&local_server_id=$resource_id&local_server_root_device=$local_server_root_device&local_server_root_device_type=$local_server_root_device_type&local_server_kernel_version=$local_server_kernel_version"; then
+	if ! wget -O /dev/null $WGET_NO_CERT_CHECK -q "$openqrm_web_protocol://$OPENQRM_SERVER_IP/openqrm/action/vmware-esx-integrate.php?USER=$USER&PASSWORD=$PASSWORD&local_server_command=integrate&local_server_id=$resource_id&local_server_root_device=$local_server_root_device&local_server_root_device_type=$local_server_root_device_type&local_server_kernel_version=$local_server_kernel_version"; then
 		echo "ERROR: Could not create the appliance resource$resouce_id on the openQRM-server!"
 		sleep 2
 		echo "NOTCIE: Removing the system from openQRM because of errors !"
 		# try to remove components from the local-server appliance
-		if ! wget -O /dev/null -q  "http://$OPENQRM_SERVER/openqrm/action/vmware-esx-integrate.php?USER=$USER&PASSWORD=$PASSWORD&local_server_command=remove&local_server_id=$resource_id"; then
+		if ! wget -O /dev/null $WGET_NO_CERT_CHECK -q  "$openqrm_web_protocol://$OPENQRM_SERVER/openqrm/action/vmware-esx-integrate.php?USER=$USER&PASSWORD=$PASSWORD&local_server_command=remove&local_server_id=$resource_id"; then
 			echo "WARNING: Could not remove the appliance resource$resouce_id from the openQRM-server!"
 		fi
 		rm -f $MONITORD_LOCKFILE
@@ -130,6 +145,6 @@ fi
 # loop
 HNAME=`hostname`
 while(true); do
-	wget -q -O /dev/null "http://$OPENQRM_SERVER_IP/openqrm/action/resource-monitor.php?resource_command=update_info&resource_id=$resource_id&resource_hostname=$HNAME&resource_state=active&resource_event=statistics"
+	wget -q -O /dev/null $WGET_NO_CERT_CHECK "$openqrm_web_protocol://$OPENQRM_SERVER_IP/openqrm/action/resource-monitor.php?resource_command=update_info&resource_id=$resource_id&resource_hostname=$HNAME&resource_state=active&resource_event=statistics"
 	sleep 20
 done
