progressing with task [ 1940898 ] ng: update path / backup/restore for plugins
git-svn-id: http://openqrm.svn.sourceforge.net/svnroot/openqrm@705 f7cd0d49-994a-0410-81fc-ecfcdc9cdbae

diff --git a/trunk/src/etc/db/mysql/openqrm-mysql-functions b/trunk/src/etc/db/mysql/openqrm-mysql-functions
--- a/trunk/src/etc/db/mysql/openqrm-mysql-functions
+++ b/trunk/src/etc/db/mysql/openqrm-mysql-functions
@@ -12,16 +12,22 @@ fi
 openqrm_server_get_config
 OPENQRM_DATABASE_INIT="$OPENQRM_SERVER_BASE_DIR/openqrm/etc/db/mysql/openqrm-mysql-init.sql"
 
+if ! which mysql 1>/dev/null 2>&1; then
+	echo "ERROR: Mysql client 'mysql' not installed/found on this system"
+	exit 1
+else
+	export MYSQL_CLIENT=`which mysql`
+fi
+if ! which mysqldump 1>/dev/null 2>&1; then
+	echo "ERROR: Mysql 'mysqldump' not installed/found on this system"
+	exit 1
+else
+	export MYSQL_DUMP=`which mysqldump`
+fi
+
+
 
 function initialize_database() {
-
-	if ! which mysql 1>/dev/null 2>&1; then
-		echo "ERROR: Mysql client 'mysql' not installed/found on this system"
-		return 1
-	else
-		MYSQL_CLIENT=`which mysql`
-	fi
-
 	# set the dbname in the sql init-script
 	OPENQRM_DATABASE_INIT_TMP=/tmp/openqrm-mysql-init.sql
 	cat $OPENQRM_DATABASE_INIT |	\
@@ -43,10 +49,57 @@ function initialize_database() {
 	return $RET
 }
 
+function backup_database() {
+	local SQL=$1
+	echo "Creating backup of the openQRM-database at $SQL"
+	if [ -z "$OPENQRM_DATABASE_PASSWORD" ]; then
+		$MYSQL_DUMP -u $OPENQRM_DATABASE_USER --host $OPENQRM_DATABASE_SERVER $OPENQRM_DATABASE_NAME > $SQL
+		RET=$?
+	else
+		$MYSQL_DUMP -u $OPENQRM_DATABASE_USER -p$OPENQRM_DATABASE_PASSWORD --host $OPENQRM_DATABASE_SERVER  $OPENQRM_DATABASE_NAME > $SQL
+		RET=$?
+	fi
+	return $RET
 
+}
+
+function restore_database() {
+	local SQL=$1
+	echo "Restoring the openQRM-database from $SQL"
+	if [ -z "$OPENQRM_DATABASE_PASSWORD" ]; then
+		$MYSQL_CLIENT -u $OPENQRM_DATABASE_USER --host $OPENQRM_DATABASE_SERVER $OPENQRM_DATABASE_NAME < $SQL
+		RET=$?
+	else
+		$MYSQL_CLIENT -u $OPENQRM_DATABASE_USER -p$OPENQRM_DATABASE_PASSWORD --host $OPENQRM_DATABASE_SERVER $OPENQRM_DATABASE_NAME < $SQL
+		RET=$?
+	fi
+	return $RET
+
+}
+
+function drop_database() {
+	echo "Dropping the openQRM-database"
+	if [ -z "$OPENQRM_DATABASE_PASSWORD" ]; then
+		$MYSQL_CLIENT -u $OPENQRM_DATABASE_USER --host $OPENQRM_DATABASE_SERVER -e "drop database $OPENQRM_DATABASE_NAME" 1>/dev/null 2>&1
+		RET=$?
+	else
+		$MYSQL_CLIENT -u $OPENQRM_DATABASE_USER -p$OPENQRM_DATABASE_PASSWORD --host $OPENQRM_DATABASE_SERVER -e "drop database $OPENQRM_DATABASE_NAME" 1>/dev/null 2>&1
+		RET=$?
+	fi
+	return $RET
+}
 
 case "$1" in
 	init)
 		initialize_database
+		;;
+	backup)
+		backup_database $2
+		;;
+	restore)
+		restore_database $2
+		;;
+	drop)
+		drop_database
 		;;
 esac
diff --git a/trunk/src/etc/db/postgres/openqrm-postgres-functions b/trunk/src/etc/db/postgres/openqrm-postgres-functions
--- a/trunk/src/etc/db/postgres/openqrm-postgres-functions
+++ b/trunk/src/etc/db/postgres/openqrm-postgres-functions
@@ -10,15 +10,21 @@ fi
 OPENQRM_DATABASE_INIT="$OPENQRM_SERVER_BASE_DIR/openqrm/etc/db/postgres/openqrm-postgres-init.sql"
 	OPENQRM_DATABASE_INIT_TMP=/tmp/openqrm-postgres-init.sql
 
+if ! which psql 1>/dev/null 2>&1; then
+	echo "ERROR: Postgres client 'psql' not installed/found on this system"
+	exit 1
+else
+	POSTGRES_CLIENT=`which psql`
+fi
+if ! which pg_dump 1>/dev/null 2>&1; then
+	echo "ERROR: Postgres 'pg_dump' not installed/found on this system"
+	exit 1
+else
+	POSTGRES_DUMP=`which pg_dump`
+fi
+
+
 function initialize_database() {
-
-	if ! which psql 1>/dev/null 2>&1; then
-		echo "ERROR: Postgres client 'psql' not installed/found on this system"
-		return 1
-	else
-		POSTGRES_CLIENT=`which psql`
-	fi
-
 	echo "Initializing the openQRM-database"
 	cat $OPENQRM_DATABASE_INIT |	\
 		sed -e "s/OPENQRM_SERVER_IP_ADDRESS/$OPENQRM_SERVER_IP_ADDRESS/g"	\
@@ -34,9 +40,39 @@ function initialize_database() {
 
 
 
+function backup_database() {
+	local SQL=$1
+	echo "Creating backup of the openQRM-database at $SQL"
+	su - postgres -c "$POSTGRES_DUMP -U $OPENQRM_DATABASE_USER $OPENQRM_DATABASE_NAME > $SQL"
+	return $RET
+
+}
+
+function restore_database() {
+	local SQL=$1
+	echo "Restoring the openQRM-database from $SQL"
+	su - postgres -c "$POSTGRES_CLIENT -d $OPENQRM_DATABASE_NAME --set openqrmdbuser=$OPENQRM_DATABASE_USER -f $SQL"
+	return $RET
+}
+
+function drop_database() {
+	echo "Dropping the openQRM-database"
+	su - postgres -c "dropdb $OPENQRM_DATABASE_NAME" 1>/dev/null 2>&1
+	return $RET
+}
+
 
 case "$1" in
 	init)
 		initialize_database
+		;;
+	backup)
+		backup_database $2
+		;;
+	restore)
+		restore_database $2
+		;;
+	drop)
+		drop_database
 		;;
 esac
