fixed for centos where kvm is named qemu-kvm
git-svn-id: http://openqrm.svn.sourceforge.net/svnroot/openqrm@1512 f7cd0d49-994a-0410-81fc-ecfcdc9cdbae

diff --git a/trunk/src/plugins/kvm/etc/templates/openqrm-kvm-vm b/trunk/src/plugins/kvm/etc/templates/openqrm-kvm-vm
--- a/trunk/src/plugins/kvm/etc/templates/openqrm-kvm-vm
+++ b/trunk/src/plugins/kvm/etc/templates/openqrm-kvm-vm
@@ -2,8 +2,11 @@
 
 KVM=`which kvm`
 if [ "$KVM" == "" ]; then
-	echo "ERROR: kvm ist not installed on this system !" | logger
-	exit 1
+    KVM=`which qemu-kvm`
+    if [ "$KVM" == "" ]; then
+        echo "ERROR: kvm ist not installed on this system !" | logger
+        exit 1
+    fi
 fi
 # source the component config files
 VM_CONF_DIR=`dirname $0`
