got lvm-storage working on the cmdline
git-svn-id: http://openqrm.svn.sourceforge.net/svnroot/openqrm@223 f7cd0d49-994a-0410-81fc-ecfcdc9cdbae

diff --git a/trunk/src/plugins/lvm-storage/bin/openqrm-lvm-storage b/trunk/src/plugins/lvm-storage/bin/openqrm-lvm-storage
--- a/trunk/src/plugins/lvm-storage/bin/openqrm-lvm-storage
+++ b/trunk/src/plugins/lvm-storage/bin/openqrm-lvm-storage
@@ -1,5 +1,198 @@
 #!/bin/bash
 
 # this script automatically manages nfs and iscsi on lvm
+if [ "$OPENQRM_SERVER_BASE_DIR" == "" ]; then
+	OPENQRM_SERVER_BASE_DIR=$(dirname $0)/../../../..
+	OPENQRM_SERVER_BASE_DIR=$(pushd $OPENQRM_SERVER_BASE_DIR > /dev/null && echo $PWD && popd > /dev/null)
+fi
+. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/lvm-storage/include/openqrm-plugin-lvm-storage-functions
 
+
+# let only root run this script
+WHOAMI=`whoami`
+if [ "$WHOAMI" != "root" ]; then
+	echo "ERROR: Please run this script as root!"
+	exit 6
+fi
+
+function lvm_storage_usage() {
+	echo "Usage : $0 add/remove/snap/list <-n image-name> <-v volume-group> <-t nfs/iscsi>"
+	echo "             [-m size in MB]"
+	echo "             [-s image-snapshot-name]"
+	exit 1
+}
+
+
+LVM_COMMAND=$1
+shift
+
+while [ $# -ne 0 ]; do
+	case "$1" in
+		-n)
+			LVM_IMAGE_NAME=$2
+			shift
+			;;
+		-m)
+			LVM_IMAGE_SIZE=$2
+			shift
+			;;
+		-s)
+			LVM_IMAGE_SNAPSHOT_NAME=$2
+			shift
+			;;
+		-t)
+			LVM_IMAGE_TYPE=$2
+			shift
+			;;
+		-v)
+			LVM_STORAGE_SERVER_VOLUME_GROUP=$2
+			shift
+			;;
+		*)
+			echo "ERROR: Free commandline arguments are not allowed"
+			lvm_storage_usage
+			exit 6
+			;;
+	esac
+	shift
+done
+
+
+
+
+# main
+if [ "$LVM_COMMAND" == "" ]; then
+	lvm_storage_usage
+fi
+if [ "$LVM_COMMAND" != "list" ]; then
+	if [ "$LVM_IMAGE_NAME" == "" ]; then
+		lvm_storage_usage
+	fi
+	if [ "$LVM_STORAGE_SERVER_VOLUME_GROUP" == "" ]; then
+		lvm_storage_usage
+	fi
+	if [ "$LVM_IMAGE_TYPE" == "" ]; then
+		lvm_storage_usage
+	fi
+fi
+
+# load required lvm modules
+modprobe dm-mod 1>/dev/null
+modprobe dm-snapshot 1>/dev/null
+# give time to settle
+sleep 2
+
+if [ "$LVM_COMMAND" != "list" ]; then
+	# check if volume group exists
+	if ! `vgdisplay | grep $LVM_STORAGE_SERVER_VOLUME_GROUP 1>/dev/null`; then
+		echo "ERROR: Could not find volume-group $LVM_STORAGE_SERVER_VOLUME_GROUP on the storage-server"
+		exit 1
+	fi
+fi
+
+case "$LVM_COMMAND" in 
+
+	add)
+	
+		if [ "$LVM_IMAGE_SIZE" == "" ]; then
+			LVM_IMAGE_SIZE=$DEFAULT_IMAGE_SIZE
+			echo "Using default size of $DEFAULT_IMAGE_SIZE MB!"
+			echo "... press return to continue"
+			read
+		fi
+		export LVM_IMAGE_SIZE
+		echo -n "Creating logical volume $LVM_IMAGE_NAME size $LVM_IMAGE_SIZE MB using volume group $LVM_STORAGE_SERVER_VOLUME_GROUP"
+
+		lvcreate -L$LVM_IMAGE_SIZE -n$LVM_IMAGE_NAME $LVM_STORAGE_SERVER_VOLUME_GROUP
+
+		if [ "$LVM_IMAGE_TYPE" == "iscsi" ]; then
+			echo "Detected Iscsi-image. Adding to $IETDCONF"
+			check_iscsi_target
+			lvm_storage_lock aquire
+			manage_iscsi add
+			lvm_storage_lock release
+		elif [ "$LVM_IMAGE_TYPE" == "nfs" ]; then
+			# we mount them and add to exports
+			echo "Detected NFS-image. Mounting and adding $LVM_IMAGE_NAME to /etc/fstab + /etc/exports"
+			lvm_storage_lock aquire
+			manage_fstab add
+			manage_nfs add
+			lvm_storage_lock release
+		fi
+
+		;;
+
+	remove)
+
+		echo -n "Removing logical volume $LVM_IMAGE_NAME on volume group $LVM_STORAGE_SERVER_VOLUME_GROUP"
+
+		if [ "$LVM_IMAGE_TYPE" == "iscsi" ]; then
+			echo "Detected Iscsi-image. Removing from $IETDCONF"
+			check_iscsi_target
+			lvm_storage_lock aquire
+			manage_iscsi remove
+			lvm_storage_lock release
+		elif [ "$LVM_IMAGE_TYPE" == "nfs" ]; then
+			echo "Detected NFS-image. Removing from /etc/exports"
+			lvm_storage_lock aquire
+			manage_nfs remove
+			manage_fstab remove
+			lvm_storage_lock release
+		fi
+
+		# give time to settle
+		sync
+		sleep 2
+		lvchange -a n /dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME
+		lvremove -f /dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME
+		;;
+
+	snap)
+		if [ "$LVM_IMAGE_SNAPSHOT_NAME" == "" ]; then
+			echo "ERROR: Please give a name for the snapshot using the -s cmdline parmeter"
+			echo
+			lvm_storage_usage
+		fi
+		if [ "$LVM_IMAGE_SIZE" == "" ]; then
+			LVM_IMAGE_SIZE=$DEFAULT_IMAGE_SIZE
+			echo "Using default size of $DEFAULT_IMAGE_SIZE MB!"
+			echo "... press return to continue"
+			read
+		fi
+		export LVM_IMAGE_SIZE
+		
+		# check that source fs-images exist
+		if ! `lvdisplay /dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME 1>/dev/null`; then
+			echo "ERROR: Could not find /dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME on the storage-server"
+			exit 1
+		fi
+		echo -n "Creating snapshot size $LVM_IMAGE_SIZE from logical volume $LVM_IMAGE_NAME -> $LVM_IMAGE_SNAPSHOT_NAME"
+		lvcreate --size $LVM_IMAGE_SIZE""m --snapshot --name $LVM_IMAGE_SNAPSHOT_NAME /dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME
+		export LVM_IMAGE_NAME=$LVM_IMAGE_SNAPSHOT_NAME
+
+		if [ "$LVM_IMAGE_TYPE" == "iscsi" ]; then
+			echo "Detected Iscsi-image. Adding to $IETDCONF"
+			check_iscsi_target
+			lvm_storage_lock aquire
+			manage_iscsi add
+			lvm_storage_lock release
+		elif [ "$LVM_IMAGE_TYPE" == "nfs" ]; then
+			echo "Detected NFS-image. Mounting and adding $IMAGE_NAME to /etc/fstab + /etc/exports"
+			lvm_storage_lock aquire
+			manage_fstab add
+			manage_nfs add snap
+			lvm_storage_lock release
+		fi
+		;;
+
+	list)
+		lvm lvs
+		;;
+
+	*)
+		lvm_storage_usage
+		;;
+
+
+esac
 
diff --git a/trunk/src/plugins/lvm-storage/include/openqrm-plugin-lvm-storage-functions b/trunk/src/plugins/lvm-storage/include/openqrm-plugin-lvm-storage-functions
--- a/trunk/src/plugins/lvm-storage/include/openqrm-plugin-lvm-storage-functions
+++ b/trunk/src/plugins/lvm-storage/include/openqrm-plugin-lvm-storage-functions
@@ -1,3 +1,156 @@
 #!/bin/bash
 # this is the functions file for the lvm-storage-plugin
 
+
+# iscsi-target config file
+IETDCONF=/etc/ietd.conf
+
+# some definitions
+DEFAULT_IMAGE_SIZE=5000
+LVM_MGMT_LOCK_FILE=/var/run/lvm-storage/lvm-storage-plugin.lock
+LVM_MGMT_LOCK_DELAY=5
+LVM_MGMT_LOCK_RETRY=100
+LVM_MGMT_LOCK_TIMEOUT=500
+MAX_UMOUNT_LOOP=5
+LV_SIZE_DEFAULT=5000
+ISCSI_TARGET_URL=http://iscsitarget.sourceforge.net/
+
+
+################ common lvm-storage functions
+
+# logs for lvm_storage
+function lvm_storage_log() {
+	local COMPONENT=$1
+	shift
+	local MESSAGE=$@
+	logger -i -t "lvm-storage plug-in" "$COMPONENT : $MESSAGE"
+}
+
+
+# locking function
+function lvm_storage_lock() {
+	local COMMAND=$1
+	local RET=1
+	
+	if [ ! -d `dirname $LVM_MGMT_LOCK_FILE` ]; then
+		mkdir -p `dirname $LVM_MGMT_LOCK_FILE`
+	fi
+	case "$COMMAND" in
+		aquire)
+				lockfile -s $LVM_MGMT_LOCK_DELAY -r $LVM_MGMT_LOCK_RETRY -l $LVM_MGMT_LOCK_TIMEOUT $LVM_MGMT_LOCK_FILE
+				RET=$?
+				lvm_storage_log lvm_storage_lock "Aquired the lock"
+				return $RET
+				;;
+		release)
+				/bin/rm -f $LVM_MGMT_LOCK_FILE
+				RET=$?
+				lvm_storage_log lvm_storage_lock "Released the lock"
+				return $RET
+				;;
+		*)
+			lvm_storage_log lvm_storage_lock "No such command. Try 'aquire' or 'release'"
+			return 1
+			;;	
+	esac
+}
+
+
+
+################ lvm-storage functions
+
+
+function check_iscsi_target() {
+	# iscsi-target installed ?
+	if ! ls $IETDCONF 1>/dev/null; then
+		echo "ERROR: Iscsi Enterprise Target not installed !"
+		echo "ERROR: For managing Iscsi filesystem-images please download and install from"
+		echo "       $ISCSI_TARGET_URL"
+		lvm_storage_log lvm-storage-functions "ERROR: Iscsi Enterprise Target not installed !"
+		lvm_storage_lock release
+		return 1
+	fi			
+}
+
+
+
+function manage_fstab() {
+	case "$1" in
+		add)
+			echo "/dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME    /$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME      ext3    defaults        1 1" >> /etc/fstab
+			;;
+		remove)
+			cat /etc/fstab | sed -e "s#^/dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME.*##g" > /tmp/fstab.tmp-update
+			/bin/mv -f /tmp/fstab.tmp-update /etc/fstab
+			;;
+	esac
+}
+
+
+function manage_nfs() {
+	case "$1" in
+		add)
+			if [ "$2" != "snap" ]; then
+				lvm_storage_log qrm-lvm-nfs-manage "NOTICE: creating ext3 filesytem on /dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME"
+				if ! mkfs.ext3 /dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME; then
+					lvm_storage_log lvm-storage-functions "ERROR: Could not create ext3 filesytem on /dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME"
+					manage_fstab remove
+					lvm_storage_lock release
+					return 1
+				fi
+			fi
+			mkdir -p /$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME
+			if ! `mount /dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME /$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME`; then
+				lvm_storage_log lvm-storage-functions "ERROR: Could not mount /dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME at /$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME"
+				manage_fstab remove
+				lvm_storage_lock release
+				return 1
+			fi
+			echo "/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME	*(rw,insecure,no_root_squash,async)" >> /etc/exports
+			/etc/init.d/nfs reload
+			;;
+		remove)
+			cat /etc/exports | sed -e "s#^/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME.*##g" > /tmp/exports.tmp-update
+			/bin/mv -f /tmp/exports.tmp-update /etc/exports
+			/etc/init.d/nfs reload
+			while ! `umount /$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME`; do
+				echo "ERROR: Could not umount /$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME, trying again ..."
+				lvm_storage_log lvm-storage-functions "ERROR: Could not umount /$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME, trying again ..."
+				if [ "$UMOUNT_LOOP" = "$MAX_UMOUNT_LOOP" ]; then
+					echo "ERROR: Could not umount /$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME. Giving up !!!" 2>1
+					lvm_storage_log lvm-storage-functions "ERROR: Could not umount /$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME. Giving up !!!"
+					manage_fstab remove
+					lvm_storage_lock release
+					return 20
+				fi
+				UMOUNT_LOOP=$(( UMOUNT_LOOP + 1 ))
+				sleep 2
+			done
+			rmdir /$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME
+			;;
+	esac
+}
+
+
+
+function manage_iscsi() {
+
+	if ! check_iscsi_target; then
+		return
+	fi
+	case "$1" in
+		add)
+			IMAGE_LUN=`cat $IETDCONF | grep Lun | awk {' print $2 '} | sort -n -r | head -n 1`
+			IMAGE_LUN=$(( IMAGE_LUN + 1 ))
+			echo "	Lun $IMAGE_LUN Path=/dev/mapper/$LVM_STORAGE_SERVER_VOLUME_GROUP-$LVM_IMAGE_NAME,Type=fileio" >> $IETDCONF
+			nohup /etc/init.d/iscsi-target restart
+			;;
+		remove)
+			cat $IETDCONF | sed -e "s#.*$LVM_STORAGE_SERVER_VOLUME_GROUP-$LVM_IMAGE_NAME.*##g" > /tmp/ietd.conf.tmp-update
+			/bin/mv -f /tmp/ietd.conf.tmp-update $IETDCONF
+			nohup /etc/init.d/iscsi-target restart
+			;;
+	esac
+}
+
+
